/**
 * ContractCodeBuilder.ts
 * 
 * Assembles complete api-contract.ts file with 4 sections
 * 
 * Responsibility: Build complete contract file from generated actions
 * 
 * @module compiler/generators/contract-generation
 */

import type { GeneratedContractAction } from './ContractActionGenerator';

/**
 * Input: Generated contract with actions
 */
export interface GeneratedContract {
    readonly resourceName: string;
    readonly actions: readonly GeneratedContractAction[];
}

/**
 * Output: Complete contract file
 */
export interface BuiltContractCode {
    readonly code: string;
    readonly lineCount: number;
    readonly contractCount: number;
    readonly sections: readonly SectionInfo[];
}

/**
 * Section metadata for tracking line ranges
 */
export interface SectionInfo {
    readonly name: string;
    readonly startLine: number;
    readonly endLine: number;
}

/**
 * ContractCodeBuilder - Assemble complete api-contract.ts file
 * 
 * Builds 4 sections:
 * 1. Zod Schemas - Runtime validation schemas
 * 2. Inferred Types - TypeScript types from schemas
 * 3. Validators - Validation helper functions
 * 4. Exports - Centralized exports object
 * 
 * @example
 * ```typescript
 * const builder = new ContractCodeBuilder();
 * 
 * const result = builder.buildContractFile([{
 *   resourceName: 'Register',
 *   actions: [{
 *     name: 'create',
 *     schemaLines: ['  create: z.object({', '    name: z.string()', '  })'],
 *     typeLines: ['  create: {', '    name: string', '  }'],
 *     fieldCount: 1
 *   }]
 * }]);
 * 
 * // result.code contains complete file with all 4 sections
 * // result.sections tracks line ranges for each section
 * ```
 */
export class ContractCodeBuilder {
    /**
     * Build complete contract file from generated contracts
     * 
     * @param contracts - Array of generated contracts with actions
     * @returns Complete contract file code with metadata
     */
    buildContractFile(
        contracts: readonly GeneratedContract[]
    ): BuiltContractCode {
        const lines: string[] = [];
        const sections: SectionInfo[] = [];

        // Header comment + imports
        lines.push('/**');
        lines.push(' * Runtime contract validation schemas');
        lines.push(' * Generated by ContractGeneratorPass');
        lines.push(' */');
        lines.push("import { z } from 'zod';");
        lines.push('');

        // Section 1: Zod Schemas
        const schemasStart = lines.length;
        lines.push('// ========== SECTION 1: Zod Schemas ==========');

        if (contracts.length === 0) {
            lines.push('// No contracts generated');
        } else {
            contracts.forEach((contract, index) => {
                this.buildSchemaSection(lines, contract);
                if (index < contracts.length - 1) {
                    lines.push('');
                }
            });
        }

        lines.push('');
        const schemasEnd = lines.length - 1;
        sections.push({ name: 'schemas', startLine: schemasStart, endLine: schemasEnd });

        // Section 2: Inferred Types
        const typesStart = lines.length;
        lines.push('// ========== SECTION 2: Inferred Types ==========');

        if (contracts.length === 0) {
            lines.push('// No types generated');
        } else {
            contracts.forEach((contract, index) => {
                this.buildTypeSection(lines, contract);
                if (index < contracts.length - 1) {
                    lines.push('');
                }
            });
        }

        lines.push('');
        const typesEnd = lines.length - 1;
        sections.push({ name: 'types', startLine: typesStart, endLine: typesEnd });

        // Section 3: Validators
        const validatorsStart = lines.length;
        lines.push('// ========== SECTION 3: Validators ==========');

        if (contracts.length === 0) {
            lines.push('// No validators generated');
        } else {
            contracts.forEach(contract => {
                this.buildValidatorSection(lines, contract);
            });
        }

        lines.push('');
        const validatorsEnd = lines.length - 1;
        sections.push({ name: 'validators', startLine: validatorsStart, endLine: validatorsEnd });

        // Section 4: Exports
        const exportsStart = lines.length;
        lines.push('// ========== SECTION 4: Exports ==========');

        if (contracts.length === 0) {
            lines.push('// No exports generated');
        } else {
            this.buildExportsSection(lines, contracts);
        }

        const exportsEnd = lines.length - 1;
        sections.push({ name: 'exports', startLine: exportsStart, endLine: exportsEnd });

        const code = lines.join('\n');

        return {
            code,
            lineCount: lines.length,
            contractCount: contracts.length,
            sections
        };
    }

    /**
     * Build Section 1: Zod Schemas
     */
    private buildSchemaSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        lines.push(`export const ${resourceName}ContractSchema = {`);

        actions.forEach((action, index) => {
            action.schemaLines.forEach(line => {
                lines.push(line);
            });

            // Add comma after each action except last
            if (index < actions.length - 1) {
                const lastLine = lines[lines.length - 1];
                lines[lines.length - 1] = lastLine + ',';
            }
        });

        lines.push('};');
    }

    /**
     * Build Section 2: Inferred Types
     */
    private buildTypeSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        lines.push(`export type ${resourceName}Contract = {`);

        actions.forEach((action, index) => {
            // Type inference from schema
            const actionName = action.name;
            const schemaRef = `typeof ${resourceName}ContractSchema.${actionName}`;
            lines.push(`  ${actionName}: z.infer<${schemaRef}>${index < actions.length - 1 ? ',' : ''}`);
        });

        lines.push('};');
    }

    /**
     * Build Section 3: Validators
     */
    private buildValidatorSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        actions.forEach(action => {
            const functionName = `validate${resourceName}${this.capitalize(action.name)}`;
            lines.push(`export const ${functionName} = (data: unknown) => {`);
            lines.push(`  return ${resourceName}ContractSchema.${action.name}.parse(data);`);
            lines.push('};');
            lines.push('');
        });
    }

    /**
     * Build Section 4: Exports
     */
    private buildExportsSection(
        lines: string[],
        contracts: readonly GeneratedContract[]
    ): void {
        lines.push('export const ContractSchemas = {');

        contracts.forEach((contract, index) => {
            const comma = index < contracts.length - 1 ? ',' : '';
            lines.push(`  ${contract.resourceName}: ${contract.resourceName}ContractSchema${comma}`);
        });

        lines.push('};');
    }

    /**
     * Capitalize first letter of string
     */
    private capitalize(str: string): string {
        return str.charAt(0).toUpperCase() + str.slice(1);
    }
}
