/**
 * ContractCodeBuilder.ts
 * 
 * Active Consumer Orchestrator: Assembles complete api-contract.ts file with 4 sections.
 * 
 * Follows Rule 14: 0 wildcard re-exports (`0 export * from`), active consumption,
 * and pure flow declaration.
 * 
 * @module compiler/generators/contract-generation/ContractCodeBuilder
 */

import {
    GeneratedContract,
    ResponseSchema,
    BuiltContractCode,
    SectionInfo,
    buildResponseSchemasSection,
    buildResponseTypesSection,
    buildResponseValidatorsSection,
    buildSchemaSection,
    buildTypeSection,
    buildValidatorSection,
    buildErrorSection,
    buildExportsSection
} from './builder';

export class ContractCodeBuilder {
    buildContractFile(
        contracts: readonly GeneratedContract[],
        responseSchemas: readonly ResponseSchema[] = []
    ): BuiltContractCode {
        const lines: string[] = [];
        const sections: SectionInfo[] = [];

        lines.push('/**');
        lines.push(' * Runtime contract validation schemas');
        lines.push(' * Generated by ContractGeneratorPass');
        lines.push(' */');
        lines.push("import { z } from 'zod';");
        lines.push('');

        // Section 0: Response Schemas (show/index)
        if (responseSchemas.length > 0) {
            const responseSchemasStart = lines.length;
            lines.push('// ========== RESPONSE SCHEMAS ==========');
            buildResponseSchemasSection(lines, responseSchemas);
            lines.push('');
            sections.push({
                name: 'response-schemas',
                startLine: responseSchemasStart,
                endLine: lines.length - 1
            });
        }

        const requestContracts = contracts.filter(c => c.actions.length > 0);

        // Section 1: Zod Schemas (REQUEST schemas)
        const schemasStart = lines.length;
        lines.push('// ========== REQUEST SCHEMAS ==========');
        if (requestContracts.length === 0) {
            lines.push('// No request schemas generated');
        } else {
            requestContracts.forEach((contract, index) => {
                buildSchemaSection(lines, contract);
                if (index < requestContracts.length - 1) {
                    lines.push('');
                }
            });
        }
        lines.push('');
        sections.push({ name: 'request-schemas', startLine: schemasStart, endLine: lines.length - 1 });

        // Section 2: Inferred Types
        const typesStart = lines.length;
        lines.push('// ========== INFERRED TYPES ==========');
        if (requestContracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No types generated');
        } else {
            if (responseSchemas.length > 0) {
                buildResponseTypesSection(lines, responseSchemas);
                if (requestContracts.length > 0) {
                    lines.push('');
                }
            }
            requestContracts.forEach((contract, index) => {
                buildTypeSection(lines, contract);
                if (index < requestContracts.length - 1) {
                    lines.push('');
                }
            });
        }
        lines.push('');
        sections.push({ name: 'types', startLine: typesStart, endLine: lines.length - 1 });

        // Section 3: Validators
        const validatorsStart = lines.length;
        lines.push('// ========== VALIDATORS ==========');
        if (requestContracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No validators generated');
        } else {
            if (responseSchemas.length > 0) {
                buildResponseValidatorsSection(lines, responseSchemas);
                if (requestContracts.length > 0) {
                    lines.push('');
                }
            }
            requestContracts.forEach(contract => {
                buildValidatorSection(lines, contract);
            });
        }

        // Error Schemas & Validators (CDA SSOT)
        buildErrorSection(lines);
        sections.push({ name: 'validators', startLine: validatorsStart, endLine: lines.length - 1 });

        // Section 4: Exports
        const exportsStart = lines.length;
        lines.push('// ========== EXPORTS ==========');
        if (requestContracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No exports generated');
        } else {
            buildExportsSection(lines, requestContracts, responseSchemas);
        }
        sections.push({ name: 'exports', startLine: exportsStart, endLine: lines.length - 1 });

        return {
            code: lines.join('\n'),
            lineCount: lines.length,
            contractCount: contracts.length,
            sections
        };
    }
}

const defaultContractCodeBuilder = new ContractCodeBuilder();

export function formatContractFile(
    contracts: readonly GeneratedContract[],
    responseSchemas: readonly ResponseSchema[] = []
): BuiltContractCode {
    return defaultContractCodeBuilder.buildContractFile(contracts, responseSchemas);
}

export {
    GeneratedContract,
    ResponseSchema,
    BuiltContractCode,
    SectionInfo
};
