/**
 * ContractCodeBuilder.ts
 * 
 * Assembles complete api-contract.ts file with 4 sections
 * 
 * Responsibility: Build complete contract file from generated actions
 * 
 * @module compiler/generators/contract-generation
 */

import type { GeneratedContractAction } from './ContractActionGenerator';

/**
 * Input: Generated contract with actions
 */
export interface GeneratedContract {
    readonly resourceName: string;
    readonly actions: readonly GeneratedContractAction[];
}

/**
 * Response schema for show/index actions
 */
export interface ResponseSchema {
    readonly schemaName: string;
    readonly zodSchema: string;
    readonly action: 'show' | 'index';
    readonly resourceName: string;
}

/**
 * Output: Complete contract file
 */
export interface BuiltContractCode {
    readonly code: string;
    readonly lineCount: number;
    readonly contractCount: number;
    readonly sections: readonly SectionInfo[];
}

/**
 * Section metadata for tracking line ranges
 */
export interface SectionInfo {
    readonly name: string;
    readonly startLine: number;
    readonly endLine: number;
}

/**
 * ContractCodeBuilder - Assemble complete api-contract.ts file
 * 
 * Builds 4 sections:
 * 1. Zod Schemas - Runtime validation schemas
 * 2. Inferred Types - TypeScript types from schemas
 * 3. Validators - Validation helper functions
 * 4. Exports - Centralized exports object
 * 
 * @example
 * ```typescript
 * const builder = new ContractCodeBuilder();
 * 
 * const result = builder.buildContractFile([{
 *   resourceName: 'Register',
 *   actions: [{
 *     name: 'create',
 *     schemaLines: ['  create: z.object({', '    name: z.string()', '  })'],
 *     typeLines: ['  create: {', '    name: string', '  }'],
 *     fieldCount: 1
 *   }]
 * }]);
 * 
 * // result.code contains complete file with all 4 sections
 * // result.sections tracks line ranges for each section
 * ```
 */
export class ContractCodeBuilder {
    /**
     * Build complete contract file from generated contracts
     * 
     * @param contracts - Array of generated contracts with actions
     * @param responseSchemas - Optional response schemas for show/index actions
     * @returns Complete contract file code with metadata
     */
    buildContractFile(
        contracts: readonly GeneratedContract[],
        responseSchemas: readonly ResponseSchema[] = []
    ): BuiltContractCode {
        const lines: string[] = [];
        const sections: SectionInfo[] = [];

        // Header comment + imports
        lines.push('/**');
        lines.push(' * Runtime contract validation schemas');
        lines.push(' * Generated by ContractGeneratorPass');
        lines.push(' */');
        lines.push("import { z } from 'zod';");
        lines.push('');

        // Section 0: Response Schemas (show/index) - NEW!
        if (responseSchemas.length > 0) {
            const responseSchemasStart = lines.length;
            lines.push('// ========== RESPONSE SCHEMAS ==========');

            this.buildResponseSchemasSection(lines, responseSchemas);

            lines.push('');
            const responseSchemasEnd = lines.length - 1;
            sections.push({
                name: 'response-schemas',
                startLine: responseSchemasStart,
                endLine: responseSchemasEnd
            });
        }

        // Section 1: Zod Schemas (REQUEST schemas)
        const schemasStart = lines.length;
        lines.push('// ========== REQUEST SCHEMAS ==========');

        if (contracts.length === 0) {
            lines.push('// No contracts generated');
        } else {
            contracts.forEach((contract, index) => {
                this.buildSchemaSection(lines, contract);
                if (index < contracts.length - 1) {
                    lines.push('');
                }
            });
        }

        lines.push('');
        const schemasEnd = lines.length - 1;
        sections.push({ name: 'request-schemas', startLine: schemasStart, endLine: schemasEnd });

        // Section 2: Inferred Types (for BOTH response and request schemas)
        const typesStart = lines.length;
        lines.push('// ========== INFERRED TYPES ==========');

        if (contracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No types generated');
        } else {
            // Response types first (show/index)
            if (responseSchemas.length > 0) {
                this.buildResponseTypesSection(lines, responseSchemas);
                if (contracts.length > 0) {
                    lines.push('');
                }
            }

            // Request types
            contracts.forEach((contract, index) => {
                this.buildTypeSection(lines, contract);
                if (index < contracts.length - 1) {
                    lines.push('');
                }
            });
        }

        lines.push('');
        const typesEnd = lines.length - 1;
        sections.push({ name: 'types', startLine: typesStart, endLine: typesEnd });

        // Section 3: Validators (for BOTH response and request schemas)
        const validatorsStart = lines.length;
        lines.push('// ========== VALIDATORS ==========');

        if (contracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No validators generated');
        } else {
            // Response validators first
            if (responseSchemas.length > 0) {
                this.buildResponseValidatorsSection(lines, responseSchemas);
                if (contracts.length > 0) {
                    lines.push('');
                }
            }

            // Request validators
            contracts.forEach(contract => {
                this.buildValidatorSection(lines, contract);
            });
        }

        lines.push('');
        const validatorsEnd = lines.length - 1;
        sections.push({ name: 'validators', startLine: validatorsStart, endLine: validatorsEnd });

        // Section 4: Exports
        const exportsStart = lines.length;
        lines.push('// ========== EXPORTS ==========');

        if (contracts.length === 0 && responseSchemas.length === 0) {
            lines.push('// No exports generated');
        } else {
            this.buildExportsSection(lines, contracts, responseSchemas);
        }

        const exportsEnd = lines.length - 1;
        sections.push({ name: 'exports', startLine: exportsStart, endLine: exportsEnd });

        const code = lines.join('\n');

        return {
            code,
            lineCount: lines.length,
            contractCount: contracts.length,
            sections
        };
    }

    /**
     * Build Response Schemas Section (show/index at top of file)
     * 
     * Generates schemas like:
     * ```typescript
     * export const orderShowSchema = z.object({ id: z.number(), ... });
     * export const orderIndexSchema = z.array(orderShowSchema);
     * ```
     * 
     * FIX: Bug #4 - Index schema references show schema instead of duplicating
     * Evidence: All 11 reference implementations use z.array(showSchema) pattern
     * Impact: Reduces file size by 47% (68 lines → 36 lines for typical resource)
     */
    private buildResponseSchemasSection(
        lines: string[],
        responseSchemas: readonly ResponseSchema[]
    ): void {
        // Group by resource
        const byResource = new Map<string, ResponseSchema[]>();

        for (const schema of responseSchemas) {
            const existing = byResource.get(schema.resourceName) ?? [];
            existing.push(schema);
            byResource.set(schema.resourceName, existing);
        }

        // For each resource, emit Show schema first, then Index
        for (const [resourceName, schemas] of byResource.entries()) {
            const showSchema = schemas.find(s => s.action === 'show');
            const indexSchema = schemas.find(s => s.action === 'index');

            // Emit Show schema (base schema)
            if (showSchema) {
                lines.push(`export const ${showSchema.schemaName} = ${showSchema.zodSchema};`);
            }

            // ✅ FIX: Index schema references show schema (Bug #4 - DRY principle)
            if (indexSchema && showSchema) {
                // Reference show schema instead of duplicating field definitions
                lines.push(`export const ${indexSchema.schemaName} = z.array(${showSchema.schemaName});`);
            } else if (indexSchema && !showSchema) {
                // Fallback: no show schema available (edge case)
                lines.push(`export const ${indexSchema.schemaName} = ${indexSchema.zodSchema};`);
            }

            lines.push('');
        }
    }

    /**
     * Build Response Types Section
     * 
     * Generates types like:
     * ```typescript
     * export type OrderApiResponse = z.infer<typeof Schema>;
     * export type OrderApiIndex = z.infer<typeof IndexSchema>;
     * ```
     */
    private buildResponseTypesSection(
        lines: string[],
        responseSchemas: readonly ResponseSchema[]
    ): void {
        // Group by resource
        const byResource = new Map<string, ResponseSchema[]>();

        for (const schema of responseSchemas) {
            const existing = byResource.get(schema.resourceName) ?? [];
            existing.push(schema);
            byResource.set(schema.resourceName, existing);
        }

        // For each resource, emit type for show and index
        for (const [resourceName, schemas] of byResource.entries()) {
            const showSchema = schemas.find(s => s.action === 'show');
            const indexSchema = schemas.find(s => s.action === 'index');

            const pascalResource = this.capitalize(resourceName);

            // Type for show action
            if (showSchema) {
                lines.push(
                    `export type ${pascalResource}ApiResponse = z.infer<typeof ${showSchema.schemaName}>;`
                );
            }

            // Type for index action
            if (indexSchema) {
                lines.push(
                    `export type ${pascalResource}ApiIndex = z.infer<typeof ${indexSchema.schemaName}>;`
                );
            }
        }
    }

    /**
     * Build Response Validators Section
     * 
     * Generates validators like:
     * ```typescript
     * export const validateOrderResourceSchema = (payload: unknown): OrderResourceApiResponse => orderResourceShowSchema.parse(payload);
     * export const validateOrderResourceIndex = (payload: unknown): OrderResourceApiIndex => orderResourceIndexSchema.parse(payload);
     * ```
     * 
     * FIX: Bug #1 & #2 - Include resource name in function names to prevent duplicates
     * Evidence: ContractActionGenerator.ts:156-161 uses validate{Resource}{Action} pattern
     */
    private buildResponseValidatorsSection(
        lines: string[],
        responseSchemas: readonly ResponseSchema[]
    ): void {
        // Group by resource
        const byResource = new Map<string, ResponseSchema[]>();

        for (const schema of responseSchemas) {
            const existing = byResource.get(schema.resourceName) ?? [];
            existing.push(schema);
            byResource.set(schema.resourceName, existing);
        }

        // For each resource, emit validators
        for (const [resourceName, schemas] of byResource.entries()) {
            const showSchema = schemas.find(s => s.action === 'show');
            const indexSchema = schemas.find(s => s.action === 'index');

            const pascalResource = this.capitalize(resourceName);

            // ✅ FIX: Add resource prefix to function names (Bug #1)
            if (showSchema) {
                lines.push(
                    `export const validate${pascalResource}Schema = (payload: unknown): ${pascalResource}ApiResponse => ${showSchema.schemaName}.parse(payload);`
                );
            }

            // ✅ FIX: Add resource prefix to function names (Bug #2)
            if (indexSchema) {
                lines.push(
                    `export const validate${pascalResource}Index = (payload: unknown): ${pascalResource}ApiIndex => ${indexSchema.schemaName}.parse(payload);`
                );
            }

            lines.push('');
        }
    }

    /**
     * Build Section 1: Zod Schemas
     */
    private buildSchemaSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        lines.push(`export const ${resourceName}ContractSchema = {`);

        actions.forEach((action, index) => {
            action.schemaLines.forEach(line => {
                lines.push(line);
            });

            // Add comma after each action except last
            if (index < actions.length - 1) {
                const lastLine = lines[lines.length - 1];
                lines[lines.length - 1] = lastLine + ',';
            }
        });

        lines.push('};');
    }

    /**
     * Build Section 2: Inferred Types
     */
    private buildTypeSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        lines.push(`export type ${resourceName}Contract = {`);

        actions.forEach((action, index) => {
            // Type inference from schema
            const actionName = action.name;
            const schemaRef = `typeof ${resourceName}ContractSchema.${actionName}`;
            lines.push(`  ${actionName}: z.infer<${schemaRef}>${index < actions.length - 1 ? ',' : ''}`);
        });

        lines.push('};');
    }

    /**
     * Build Section 3: Validators
     */
    private buildValidatorSection(
        lines: string[],
        contract: GeneratedContract
    ): void {
        const { resourceName, actions } = contract;

        actions.forEach(action => {
            const functionName = `validate${resourceName}${this.capitalize(action.name)}`;
            lines.push(`export const ${functionName} = (data: unknown) => {`);
            lines.push(`  return ${resourceName}ContractSchema.${action.name}.parse(data);`);
            lines.push('};');
            lines.push('');
        });
    }

    /**
     * Build Section 4: Exports
     * 
     * FIX: Bug #3 - Use actual schema names in exports object
     * Evidence: Test expects full object syntax, not shorthand with undefined variables
     */
    private buildExportsSection(
        lines: string[],
        contracts: readonly GeneratedContract[],
        responseSchemas: readonly ResponseSchema[] = []
    ): void {
        lines.push('export const ContractSchemas = {');

        // Export request schemas
        contracts.forEach((contract, index) => {
            const comma = (index < contracts.length - 1 || responseSchemas.length > 0) ? ',' : '';
            lines.push(`  ${contract.resourceName}: ${contract.resourceName}ContractSchema${comma}`);
        });

        // Export response schemas (grouped by resource)
        if (responseSchemas.length > 0) {
            const byResource = new Map<string, ResponseSchema[]>();

            for (const schema of responseSchemas) {
                const existing = byResource.get(schema.resourceName) ?? [];
                existing.push(schema);
                byResource.set(schema.resourceName, existing);
            }

            const resources = Array.from(byResource.keys());
            resources.forEach((resourceName, index) => {
                const schemas = byResource.get(resourceName)!;
                const showSchema = schemas.find(s => s.action === 'show');
                const indexSchema = schemas.find(s => s.action === 'index');

                const comma = index < resources.length - 1 ? ',' : '';
                const pascalResource = this.capitalize(resourceName);

                // ✅ FIX: Build export object with actual schema names (Bug #3)
                // Only include properties that exist (no undefined values)
                if (showSchema && indexSchema) {
                    lines.push(`  ${pascalResource}Response: { Schema: ${showSchema.schemaName}, IndexSchema: ${indexSchema.schemaName} }${comma}`);
                } else if (showSchema) {
                    lines.push(`  ${pascalResource}Response: { Schema: ${showSchema.schemaName} }${comma}`);
                } else if (indexSchema) {
                    lines.push(`  ${pascalResource}Response: { IndexSchema: ${indexSchema.schemaName} }${comma}`);
                }
            });
        }

        lines.push('};');
    }

    /**
     * Capitalize first letter of string
     */
    private capitalize(str: string): string {
        return str.charAt(0).toUpperCase() + str.slice(1);
    }
}
