/**
 * ConstantsGenerator.ts
 *
 * Active Consumer Orchestrator for constants.ts code generation.
 * Pure flow declaration: coordinates API_URL, API_ENDPOINTS, ROUTES, and Enums sections.
 *
 * @module cli/generators/ConstantsGenerator
 */

import { RouteManifest } from '@routesync/core';
import path from 'path';
import fs from 'fs-extra';
import {
  resolveRouteKey,
  buildApiEndpointsLines,
  buildRoutesLines,
  buildEnumsLines
} from './constants';

export class ConstantsGenerator {
  static getRouteKey(routePath: string): string {
    return resolveRouteKey(routePath);
  }

  static getConstantLines(manifest: RouteManifest): string[] {
    const lines: string[] = [];
    lines.push(``);
    lines.push(`/* =========================`);
    lines.push(`   APPLICATION CONSTANTS`);
    lines.push(`========================= */`);
    lines.push(``);

    // 1. API_URL
    const defaultBaseURL = manifest.baseURL || 'http://localhost/api';
    lines.push(`export const API_URL = process.env.NEXT_PUBLIC_API_URL || '${defaultBaseURL}'`);
    lines.push(``);

    // 2. API_ENDPOINTS
    lines.push(...buildApiEndpointsLines(manifest));

    // 3. ROUTES
    lines.push(...buildRoutesLines(manifest));

    // 4. Status Enums
    lines.push(...buildEnumsLines(manifest));

    return lines;
  }

  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const lines = ConstantsGenerator.getConstantLines(manifest);
    lines.unshift(`// Auto-generated by routesync. Do not edit manually.`);
    await fs.writeFile(path.join(outputDir, 'constants.ts'), lines.join('\n'));

    // Clean up any legacy enums.js or enums.d.ts inside node_modules if it exists
    const sdkDir = path.resolve(outputDir, '../../node_modules/routesync');
    if (fs.existsSync(sdkDir)) {
      const enumsJs = path.join(sdkDir, 'dist', 'enums.js');
      const enumsDts = path.join(sdkDir, 'dist', 'enums.d.ts');
      if (fs.existsSync(enumsJs)) await fs.remove(enumsJs);
      if (fs.existsSync(enumsDts)) await fs.remove(enumsDts);
    }
  }
}