import { RouteManifest, ParsedRoute } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { buildGeneratedRoutes, toTypeName } from './names'

export class HookGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)
    lines.push(`import { useApiQuery, useApiMutation } from 'routesync/react'`)
    lines.push(`import { api } from './api'`)
    lines.push(``)

    const grouped = buildGeneratedRoutes(manifest.routes)
    const modelNames = (manifest.models || []).map(m => m.name)

    for (const [group, routes] of Object.entries(grouped)) {
      for (const route of routes) {
        const method = route.method.toUpperCase()
        const hookName = HookGenerator.toHookName(group, route.actionName)
        
        const contractName = `${toTypeName(group)}${toTypeName(route.actionName)}Contract`
        const hasParams = route.path.includes(':') || route.path.includes('{')
        const hasBody = route.schema?.body
        const requiresOptions = hasParams || hasBody

        if (method === 'GET') {
          lines.push(`/**`)
          lines.push(` * @deprecated Generated hooks will become optional in v2.`)
          lines.push(` * Prefer \`useApiQuery(api.${group}.${route.actionName}, ...args)\` for future compatibility.`)
          lines.push(` */`)
          lines.push(`export function ${hookName}(...args: [options${requiresOptions ? '' : '?'}: import('./api').${contractName}['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').${contractName}['response'], import('./types').ApiError>]) {`)
          // Destructure args explicitly so TS doesn't spread undefined into useApiQuery
          lines.push(`  const [options, queryOptions] = args`)
          lines.push(`  return useApiQuery<import('./api').${contractName}['response'], import('./api').${contractName}['request']['params'], import('./api').${contractName}['request']['body'], import('./types').ApiError>(api.${group}.${route.actionName}, options, queryOptions)`)
          lines.push(`}`)
          lines.push(``)
        } else {
          lines.push(`/**`)
          lines.push(` * @deprecated Generated hooks will become optional in v2.`)
          lines.push(` * Prefer \`useApiMutation(api.${group}.${route.actionName}, options)\` for future compatibility.`)
          lines.push(` */`)
          lines.push(`export function ${hookName}() {`)
          lines.push(`  return useApiMutation(api.${group}.${route.actionName})`)
          lines.push(`}`)
          lines.push(``)
        }
      }
    }

    await fs.writeFile(path.join(outputDir, 'hooks.ts'), lines.join('\n'))
  }

  private static toHookName(group: string, actionName: string): string {
    return `use${toTypeName(group)}${toTypeName(actionName)}`
  }
}
