import { RouteManifest } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { toTypeName } from './names'
import { classifyRoutes, buildResourceMap, buildGroupedRoutes } from './route-classifier'

export class QueryKeyGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const classified = classifyRoutes(manifest.routes, manifest.frontend?.groupAliases)
    const resources  = buildResourceMap(classified)

    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)

    // ── 1. Entity constants ───────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   ENTITY CONSTANTS`)
    lines.push(`========================= */`)
    lines.push(`export const Entity = {`)
    for (const groupName of resources.keys()) {
      lines.push(`  ${groupName.toUpperCase()}: "${groupName}",`)
    }
    lines.push(`} as const`)
    lines.push(``)
    lines.push(`type EntityValue = (typeof Entity)[keyof typeof Entity]`)
    lines.push(``)

    // ── 2. Base factory ───────────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BASE FACTORY (GENERIC)`)
    lines.push(`========================= */`)
    lines.push(`const createBaseQueryKey = <T extends EntityValue>(entity: T) => ({`)
    lines.push(`  all:     ()                         => [entity] as const,`)
    lines.push(`  lists:   ()                         => [entity, "list"] as const,`)
    lines.push(`  list:    (filters?: Record<string, unknown>) =>`)
    lines.push(`             [entity, "list", filters ?? {}] as const,`)
    lines.push(`  details: ()                         => [entity, "detail"] as const,`)
    lines.push(`  detail:  (id: string | number)      => [entity, "detail", id] as const,`)
    lines.push(`})`)
    lines.push(``)

    // ── 3. Query key registry ─────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   QUERY KEY REGISTRY`)
    lines.push(`========================= */`)
    lines.push(`export const QueryKey = {`)

    const backwardExports: string[] = []

    for (const [groupName, resource] of resources) {
      const KEY   = groupName.toUpperCase()
      const Title = toTypeName(groupName)
      const isCrud = !!(resource.index && resource.show)

      backwardExports.push(`export const ${groupName}Keys = QueryKey.${groupName}`)

      lines.push(`  /* ===== ${Title.toUpperCase()} ===== */`)
      const actionKeyLines = resource.all.map(route => {
        if (route.hasParams) {
          return `    ${route.actionName}: (params?: string | number | Record<string, unknown>) => [Entity.${KEY}, "${route.actionName}", params ?? {}] as const,`
        }
        return `    ${route.actionName}: () => [Entity.${KEY}, "${route.actionName}"] as const,`
      })

      if (isCrud) {
        lines.push(`  ${groupName}: {`)
        lines.push(`    ...createBaseQueryKey(Entity.${KEY}),`)
        lines.push(...actionKeyLines)
        lines.push(`  },`)
      } else {
        // Singleton / action-based resource (e.g. cart, profile, auth)
        lines.push(`  ${groupName}: {`)
        lines.push(`    all: () => [Entity.${KEY}] as const,`)
        lines.push(...actionKeyLines)
        lines.push(`  },`)
      }

      lines.push(``)
    }

    lines.push(`} as const`)
    lines.push(``)

    // ── 4. Backward-compat exports ────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BACKWARD COMPATIBLE EXPORTS`)
    lines.push(`========================= */`)
    for (const exp of backwardExports) {
      lines.push(exp)
    }
    lines.push(``)

    await fs.writeFile(path.join(outputDir, 'query-key.ts'), lines.join('\n'))
  }
}
