import {
  RouteManifest,
  CrudResourceGroupDescriptor,
  SingletonResourceGroupDescriptor,
  CustomResourceGroupDescriptor
} from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { classifyDomainGraph, ClassifiedDomainGraph, ClassifiedRoute } from './route-classifier'

function lowerCrudQueryKeyBlock(
  group: CrudResourceGroupDescriptor<ClassifiedRoute>,
  actionKeyLines: readonly string[]
): readonly string[] {
  return [
    `  ${group.groupName}: {`,
    `    ...createBaseQueryKey<typeof Entity.${group.keyName}, ${group.primaryKeyType}>(Entity.${group.keyName}),`,
    ...actionKeyLines,
    `  },`
  ]
}

function lowerNonCrudQueryKeyBlock(
  group: SingletonResourceGroupDescriptor<ClassifiedRoute> | CustomResourceGroupDescriptor<ClassifiedRoute>,
  actionKeyLines: readonly string[]
): readonly string[] {
  return [
    `  ${group.groupName}: {`,
    `    all: () => [Entity.${group.keyName}] as const,`,
    ...actionKeyLines,
    `  },`
  ]
}

export class QueryKeyGenerator {
  static async generate(
    manifest: RouteManifest,
    outputDir: string,
    domainGraph?: ClassifiedDomainGraph<ClassifiedRoute>
  ): Promise<void> {
    const graph = domainGraph ?? classifyDomainGraph(manifest)

    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)

    // ── 1. Entity constants ───────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   ENTITY CONSTANTS`)
    lines.push(`========================= */`)
    lines.push(`export const Entity = {`)
    for (const group of graph.resourceGroupGraph.all) {
      lines.push(`  ${group.keyName}: "${group.groupName}",`)
    }
    lines.push(`} as const`)
    lines.push(``)
    lines.push(`type EntityValue = (typeof Entity)[keyof typeof Entity]`)
    lines.push(``)

    // ── 2. Base factory ───────────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BASE FACTORY (GENERIC)`)
    lines.push(`========================= */`)
    lines.push(`const createBaseQueryKey = <T extends EntityValue, TId = string | number, TFilter = Record<string, unknown>>(entity: T) => ({`)
    lines.push(`  all:     ()                         => [entity] as const,`)
    lines.push(`  lists:   ()                         => [entity, "list"] as const,`)
    lines.push(`  list:    (filters?: TFilter)        =>`)
    lines.push(`             [entity, "list", filters ?? {}] as const,`)
    lines.push(`  details: ()                         => [entity, "detail"] as const,`)
    lines.push(`  detail:  (id: TId)                  => [entity, "detail", id] as const,`)
    lines.push(`})`)
    lines.push(``)

    // ── 3. Query key registry ─────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   QUERY KEY REGISTRY`)
    lines.push(`========================= */`)
    lines.push(`export const QueryKey = {`)

    const backwardExports: string[] = []

    for (const group of graph.resourceGroupGraph.all) {
      const KEY   = group.keyName
      const Title = group.titleName

      backwardExports.push(`export const ${group.groupName}Keys = QueryKey.${group.groupName}`)

      lines.push(`  /* ===== ${Title.toUpperCase()} ===== */`)
      const actionKeyLines = group.all.map(route => {
        if (route.hasParams) {
          return `    ${route.actionName}: (params?: string | number | Record<string, unknown>) => [Entity.${KEY}, "${route.actionName}", params ?? {}] as const,`
        }
        return `    ${route.actionName}: () => [Entity.${KEY}, "${route.actionName}"] as const,`
      })

      // Typed dataflow lowering: direct projection based on guaranteed domain discriminator
      const blockLines = group.isCrud
        ? lowerCrudQueryKeyBlock(group, actionKeyLines)
        : lowerNonCrudQueryKeyBlock(group, actionKeyLines)

      lines.push(...blockLines)
      lines.push(``)
    }

    lines.push(`} as const`)
    lines.push(``)

    // ── 4. Backward-compat exports ────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BACKWARD COMPATIBLE EXPORTS`)
    lines.push(`========================= */`)
    for (const exp of backwardExports) {
      lines.push(exp)
    }
    lines.push(``)

    await fs.writeFile(path.join(outputDir, 'query-key.ts'), lines.join('\n'))
  }
}
