import { RouteManifest, matchResourceGroup } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { classifyDomainGraph, ClassifiedDomainGraph, ClassifiedRoute } from './route-classifier'

export class QueryKeyGenerator {
  static async generate(
    manifest: RouteManifest,
    outputDir: string,
    domainGraph?: ClassifiedDomainGraph<ClassifiedRoute>
  ): Promise<void> {
    const graph = domainGraph ?? classifyDomainGraph(manifest)

    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)

    // ── 1. Entity constants ───────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   ENTITY CONSTANTS`)
    lines.push(`========================= */`)
    lines.push(`export const Entity = {`)
    for (const group of graph.resourceGroups) {
      lines.push(`  ${group.keyName}: "${group.groupName}",`)
    }
    lines.push(`} as const`)
    lines.push(``)
    lines.push(`type EntityValue = (typeof Entity)[keyof typeof Entity]`)
    lines.push(``)

    // ── 2. Base factory ───────────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BASE FACTORY (GENERIC)`)
    lines.push(`========================= */`)
    lines.push(`const createBaseQueryKey = <T extends EntityValue, TId = string | number, TFilter = Record<string, unknown>>(entity: T) => ({`)
    lines.push(`  all:     ()                         => [entity] as const,`)
    lines.push(`  lists:   ()                         => [entity, "list"] as const,`)
    lines.push(`  list:    (filters?: TFilter)        =>`)
    lines.push(`             [entity, "list", filters ?? {}] as const,`)
    lines.push(`  details: ()                         => [entity, "detail"] as const,`)
    lines.push(`  detail:  (id: TId)                  => [entity, "detail", id] as const,`)
    lines.push(`})`)
    lines.push(``)

    // ── 3. Query key registry ─────────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   QUERY KEY REGISTRY`)
    lines.push(`========================= */`)
    lines.push(`export const QueryKey = {`)

    const backwardExports: string[] = []

    for (const group of graph.resourceGroups) {
      const KEY   = group.keyName
      const Title = group.titleName
      const idType = group.primaryKeyType

      backwardExports.push(`export const ${group.groupName}Keys = QueryKey.${group.groupName}`)

      lines.push(`  /* ===== ${Title.toUpperCase()} ===== */`)
      const actionKeyLines = group.all.map(route => {
        if (route.hasParams) {
          return `    ${route.actionName}: (params?: string | number | Record<string, unknown>) => [Entity.${KEY}, "${route.actionName}", params ?? {}] as const,`
        }
        return `    ${route.actionName}: () => [Entity.${KEY}, "${route.actionName}"] as const,`
      })

      // 0-if catamorphic rendering via matchResourceGroup
      const emitCrudKey = () => {
        lines.push(`  ${group.groupName}: {`)
        lines.push(`    ...createBaseQueryKey<typeof Entity.${KEY}, ${idType}>(Entity.${KEY}),`)
        lines.push(...actionKeyLines)
        lines.push(`  },`)
      }

      matchResourceGroup(group, {
        full_crud: emitCrudKey,
        read_only_crud: emitCrudKey,
        flexible_crud: emitCrudKey,
        crud: emitCrudKey,
        singleton: () => {
          lines.push(`  ${group.groupName}: {`)
          lines.push(`    all: () => [Entity.${KEY}] as const,`)
          lines.push(...actionKeyLines)
          lines.push(`  },`)
        },
        custom: () => {
          lines.push(`  ${group.groupName}: {`)
          lines.push(`    all: () => [Entity.${KEY}] as const,`)
          lines.push(...actionKeyLines)
          lines.push(`  },`)
        }
      })

      lines.push(``)
    }

    lines.push(`} as const`)
    lines.push(``)

    // ── 4. Backward-compat exports ────────────────────────────────────────
    lines.push(`/* =========================`)
    lines.push(`   BACKWARD COMPATIBLE EXPORTS`)
    lines.push(`========================= */`)
    for (const exp of backwardExports) {
      lines.push(exp)
    }
    lines.push(``)

    await fs.writeFile(path.join(outputDir, 'query-key.ts'), lines.join('\n'))
  }
}
