import { RouteManifest, camelCase } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { buildGeneratedRoutes } from './names'

export class SchemaGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const lines: string[] = []
    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)
    lines.push(`import { z } from 'zod'`)
    lines.push(``)

    // Generate Zod schemas for explicit models
    if (manifest.models && manifest.models.length > 0) {
      for (const model of manifest.models) {
        lines.push(`export const ${model.name}Schema = z.object({`)
        const hidden = Array.isArray(model.hidden) ? model.hidden : []
        const casts = model.casts || {}

        for (const col of model.columns) {
          const isHidden = hidden.includes(col.name)
          const castType = casts[col.name]
          
          let zType = this.mapSqlTypeToZod(col.type)
          if (castType) {
            zType = this.mapCastToZod(castType, zType)
          }

          if (col.nullable) {
            zType += '.nullable()'
          }
          if (isHidden) {
            zType += '.optional()'
          }

          const safeName = camelCase(col.name).match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelCase(col.name) : `"${camelCase(col.name)}"`
          lines.push(`  ${safeName}: ${zType},`)
        }
        
        const appends = Array.isArray(model.appends) ? model.appends : []
        for (const append of appends) {
          const safeAppend = camelCase(append).match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelCase(append) : `"${camelCase(append)}"`
          lines.push(`  ${safeAppend}: z.unknown().optional(), // appended attribute`)
        }

        if (model.accessors) {
          for (const [key, accessor] of Object.entries(model.accessors)) {
            if (hidden.includes(key)) continue
            const safeName = camelCase(key).match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelCase(key) : `"${camelCase(key)}"`
            const expr = (accessor as any)?.expression
            let zType = 'z.unknown()'
            if (expr && expr.type) {
              if (expr.type === 'number') zType = 'z.number()'
              else if (expr.type === 'boolean') zType = 'z.boolean()'
              else if (expr.type === 'string') zType = 'z.string()'
            }
            lines.push(`  ${safeName}: ${zType}.optional(), // accessor attribute`)
          }
        }

        lines.push(`})`)
        lines.push(``)
      }
    }

    // Generate Zod schemas for request body rules
    const grouped = buildGeneratedRoutes(manifest.routes)
    for (const [group, routes] of Object.entries(grouped)) {
      for (const route of routes) {
        if (route.schema && route.schema.rules && Object.keys(route.schema.rules).length > 0) {
          const TitleCaseGroup = group.charAt(0).toUpperCase() + group.slice(1)
          const TitleCaseAction = route.actionName.charAt(0).toUpperCase() + route.actionName.slice(1)
          const schemaName = TitleCaseGroup + TitleCaseAction + 'Schema'

          lines.push(`export const ${schemaName} = z.object({`)
          
          for (const [field, rules] of Object.entries(route.schema.rules)) {
            const ruleStr = Array.isArray(rules) ? rules.join('|') : String(rules)
            let zodRule = this.mapRulesToZod(ruleStr)
            
            if (!ruleStr.includes('required')) {
              zodRule += '.optional()'
            }
            if (ruleStr.includes('nullable')) {
              zodRule += '.nullable()'
            }
            
            const camelField = camelCase(field)
            const safeField = camelField.match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelField : `"${camelField}"`
            lines.push(`  ${safeField}: ${zodRule},`)
          }
          lines.push(`})`)
          lines.push(``)
        }
      }
    }

    await fs.writeFile(path.join(outputDir, 'schemas.ts'), lines.join('\n'))
  }

  /**
   * Map a Laravel validation rule string to a Zod type.
   * Default is z.string() — HTTP inputs are strings unless explicitly typed.
   */
  private static mapRulesToZod(ruleStr: string): string {
    if (ruleStr.includes('array')) return 'z.array(z.unknown())'
    if (ruleStr.includes('integer') || ruleStr.includes('numeric') || ruleStr.includes('digits')) return 'z.number()'
    if (ruleStr.includes('boolean') || ruleStr.includes('bool')) return 'z.boolean()'
    return 'z.string()'
  }

  private static mapSqlTypeToZod(sqlType: string): string {
    const type = sqlType.toLowerCase()
    if (type.includes('int') || type.includes('float') || type.includes('double') || type.includes('decimal') || type.includes('numeric')) {
      return 'z.number()'
    }
    if (type.includes('bool') || type.includes('tinyint(1)')) {
      return 'z.boolean()'
    }
    if (type.includes('json')) {
      return 'z.record(z.string(), z.unknown())'
    }
    const enumMatch = type.match(/^enum\((.*)\)$/)
    if (enumMatch && enumMatch[1]) {
      const values = enumMatch[1].split(',').map(v => v.trim().replace(/^'|'$/g, ''))
      return `z.union([${values.map(v => `z.literal('${v}')`).join(', ')}])`
    }
    return 'z.string()'
  }

  private static mapCastToZod(castType: string, defaultType: string): string {
    const type = castType.toLowerCase()
    if (type.includes('int') || type.includes('float') || type.includes('decimal') || type.includes('double')) {
      return 'z.number()'
    }
    if (type.includes('bool')) {
      return 'z.boolean()'
    }
    if (type.includes('array') || type.includes('json') || type.includes('collection') || type.includes('object')) {
      return 'z.record(z.string(), z.unknown())'
    }
    if (type.includes('date') || type.includes('datetime') || type.includes('string')) {
      return 'z.string()'
    }
    return defaultType
  }
}
