import { RouteManifest, ParsedRoute } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { buildGeneratedRoutes } from './names'

export class SDKGenerator {
  static async generate(manifest: RouteManifest, outputDir: string, options: any = {}): Promise<void> {
    const grouped = buildGeneratedRoutes(manifest.routes)
    const lines: string[] = []

    let usesZod = false
    const zodRoutes = new Set<string>()

    if (options.zod) {
      for (const [group, routes] of Object.entries(grouped)) {
        for (const route of routes) {
          if (route.schema?.rules) {
            usesZod = true
            zodRoutes.add(`${group}.${route.actionName}`)
          }
        }
      }
    }

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(`// Generated at: ${manifest.generatedAt}`)
    lines.push(``)
    lines.push(`import { defineApi } from 'routesync'`)
    if (usesZod) {
      lines.push(`import { z } from 'zod'`)
    }
    lines.push(``)
    lines.push(`export const api = defineApi({`)

    for (const [group, routes] of Object.entries(grouped)) {
      lines.push(`  ${group}: {`)

      for (const route of routes) {
        lines.push(`    ${route.actionName}: {`)
        lines.push(`      method: '${route.method}',`)
        lines.push(`      path: '${route.runtimePath}',`)
        if (route.auth) lines.push(`      auth: true,`)
        
        if (options.zod && route.schema?.rules) {
          const zodSchema = SDKGenerator.translateRulesToZod(route.schema.rules)
          lines.push(`      schema: {`)
          lines.push(`        body: ${zodSchema}`)
          lines.push(`      },`)
        }

        lines.push(`    },`)
      }

      lines.push(`  },`)
    }

    lines.push(`})`)
    lines.push(``)
    lines.push(`export default api`)

    await fs.writeFile(path.join(outputDir, 'api.ts'), lines.join('\n'))
  }

  private static translateRulesToZod(rules: Record<string, string | string[]>): string {
    const fields: string[] = []

    for (const [field, rawRules] of Object.entries(rules)) {
      let ruleArray: string[] = []
      if (typeof rawRules === 'string') {
        ruleArray = rawRules.split('|')
      } else if (Array.isArray(rawRules)) {
        ruleArray = rawRules
      }

      let isRequired = false
      let isNullable = false
      let isString = false
      let isNumeric = false
      let isArray = false
      let isBoolean = false
      let isEmail = false

      let min: string | null = null
      let max: string | null = null

      for (const rule of ruleArray) {
        if (typeof rule !== 'string') continue
        const r = rule.toLowerCase()
        if (r === 'required') isRequired = true
        if (r === 'nullable') isNullable = true
        if (r === 'string') isString = true
        if (r === 'numeric' || r === 'integer' || r === 'int') isNumeric = true
        if (r === 'array') isArray = true
        if (r === 'boolean' || r === 'bool') isBoolean = true
        if (r === 'email') isEmail = true
        
        if (r.startsWith('min:')) min = r.split(':')[1]
        if (r.startsWith('max:')) max = r.split(':')[1]
      }

      let zType = 'z.unknown()'
      if (isString) zType = 'z.string()'
      else if (isNumeric) zType = 'z.number()'
      else if (isBoolean) zType = 'z.boolean()'
      else if (isArray) zType = 'z.array(z.unknown())'
      else if (isEmail) zType = 'z.string()'

      if (isEmail && zType === 'z.string()') zType += '.email()'
      if (min && !isNaN(Number(min))) zType += `.min(${min})`
      if (max && !isNaN(Number(max))) zType += `.max(${max})`

      if (!isRequired) zType += '.optional()'
      if (isNullable) zType += '.nullable()'

      fields.push(`          "${field}": ${zType}`)
    }

    return `z.object({\n${fields.join(',\n')}\n        })`
  }
}
