import type { RouteManifest } from '@routesync/core';
import path from 'path';
import fs from 'fs-extra';
import { classifyRoutes, buildGroupedRoutes } from './route-classifier';
import { emitApiObjectLines } from './sdk';

export class SDKGenerator {
  static async generate(
    manifest: RouteManifest,
    outputDir?: string,
    options: Record<string, unknown> = {}
  ): Promise<string> {
    const classified = classifyRoutes(manifest.routes, manifest.frontend?.groupAliases);
    const grouped = buildGroupedRoutes(classified);

    const usesZod = Boolean(options.zod);
    const usedContracts = new Set<string>();
    const usedPayloadContracts = new Set<string>();
    const usedMappers = new Set<string>();

    const apiBodyLines = emitApiObjectLines(grouped, {
      usesZod,
      usedContracts,
      usedPayloadContracts,
      usedMappers
    });

    const lines: string[] = [];
    lines.push('// Auto-generated by routesync. Do not edit manually.');
    lines.push(`// Generated at: ${manifest.generatedAt}`);
    lines.push('');
    lines.push("import { defineApi, endpoint } from 'routesync'");
    lines.push("import { API_URL, API_ENDPOINTS, ROUTES, Enums } from './constants'");

    if (usedContracts.size > 0) {
      lines.push(`import { ${Array.from(usedContracts).sort().join(', ')} } from './contract/api-contract'`);
    }
    if (usedPayloadContracts.size > 0) {
      lines.push(`import { ${Array.from(usedPayloadContracts).sort().join(', ')} } from './contract/api-schema'`);
    }
    if (usedMappers.size > 0) {
      lines.push(`import { ${Array.from(usedMappers).sort().join(', ')} } from './mappers/api-mapper'`);
    }
    lines.push('');

    lines.push(...apiBodyLines);
    lines.push('');
    lines.push('export default api');
    lines.push('');

    const result = lines.join('\n');
    if (outputDir) {
      await fs.writeFile(path.join(outputDir, 'api.ts'), result);
    }
    return result;
  }
}
