import { RouteManifest, ParsedRoute } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { buildGeneratedRoutes } from './names'

export class SDKGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const grouped = buildGeneratedRoutes(manifest.routes)
    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(`// Generated at: ${manifest.generatedAt}`)
    lines.push(``)
    lines.push(`import { defineApi } from 'routesync'`)
    lines.push(``)
    lines.push(`export const api = defineApi({`)

    for (const [group, routes] of Object.entries(grouped)) {
      lines.push(`  ${group}: {`)

      for (const route of routes) {
        lines.push(`    ${route.actionName}: {`)
        lines.push(`      method: '${route.method}',`)
        lines.push(`      path: '${route.runtimePath}',`)
        if (route.auth) lines.push(`      auth: true,`)
        lines.push(`    },`)
      }

      lines.push(`  },`)
    }

    lines.push(`})`)
    lines.push(``)
    lines.push(`export default api`)

    await fs.writeFile(path.join(outputDir, 'api.ts'), lines.join('\n'))
  }
}
