/**
 * TypeScriptWriter.ts
 * Write generated TypeScript code to file system
 * 
 * Handles:
 * - File structure creation (types/, mappers/, etc.)
 * - Code formatting and headers
 * - Index.ts generation for re-exports
 */

import fs from 'fs-extra'
import path from 'path'
import type { CompilerOutput } from './CompilerBridge'

/**
 * TypeScriptWriter class
 * Write compiler output ke file system dengan proper structure
 */
export class TypeScriptWriter {
    /**
     * Write output to files with proper structure
     * 
     * @param output - CompilerOutput dari CompilerBridge
     * @param outputDir - Directory untuk write files
     */
    static async write(output: CompilerOutput, outputDir: string): Promise<void> {
        console.log('[TypeScriptWriter] Writing files...')

        // Create types directory
        const typesDir = path.join(outputDir, 'types')
        await fs.ensureDir(typesDir)

        // Write generated.ts
        const generatedPath = path.join(typesDir, 'generated.ts')
        const generatedContent = this.formatGeneratedFile(output)
        await fs.writeFile(generatedPath, generatedContent, 'utf-8')
        console.log(`  ✓ types/generated.ts (${generatedContent.length} chars)`)

        // Write index.ts
        const indexPath = path.join(typesDir, 'index.ts')
        const indexContent = this.formatIndexFile(output)
        await fs.writeFile(indexPath, indexContent, 'utf-8')
        console.log(`  ✓ types/index.ts (re-exports)`)

        // Write mappers directory (placeholder for now)
        const mappersDir = path.join(outputDir, 'mappers')
        await fs.ensureDir(mappersDir)
        const mappersIndexPath = path.join(mappersDir, 'index.ts')
        await fs.writeFile(mappersIndexPath, this.formatMappersIndex(), 'utf-8')
        console.log(`  ✓ mappers/index.ts (placeholder)`)

        // Write root index.ts
        const rootIndexPath = path.join(outputDir, 'index.ts')
        const rootIndexContent = this.formatRootIndex()
        await fs.writeFile(rootIndexPath, rootIndexContent, 'utf-8')
        console.log(`  ✓ index.ts (root exports)`)

        // Print summary
        this.printSummary(output)
    }

    /**
     * Format generated.ts content dengan header
     */
    private static formatGeneratedFile(output: CompilerOutput): string {
        const lines = [
            '/**',
            ' * Generated TypeScript types',
            ' * @generated by RouteSync CompilerBridge',
            ` * @timestamp ${new Date().toISOString()}`,
            ' * DO NOT EDIT - This file is auto-generated',
            ' */',
            '',
            '// Imports',
            ...output.imports.map(imp => imp),
            '',
            '// Type definitions',
            output.code,
            '',
            '// Interfaces',
            ...output.interfaces.map(iface => iface),
            ''
        ]

        return lines.join('\n')
    }

    /**
     * Format types/index.ts content
     */
    private static formatIndexFile(output: CompilerOutput): string {
        const lines = [
            '/**',
            ' * Type exports',
            ' * @generated by RouteSync CompilerBridge',
            ' */',
            '',
            '// Re-export all types',
            "export * from './generated'",
            ''
        ]

        return lines.join('\n')
    }

    /**
     * Format mappers/index.ts content (placeholder)
     */
    private static formatMappersIndex(): string {
        const lines = [
            '/**',
            ' * Response mappers',
            ' * @generated by RouteSync CompilerBridge',
            ' */',
            '',
            '// Mappers will be generated here',
            'export const mappers = {}',
            ''
        ]

        return lines.join('\n')
    }

    /**
     * Format root index.ts content
     */
    private static formatRootIndex(): string {
        const lines = [
            '/**',
            ' * RouteSync Generated API',
            ' * @generated by RouteSync CompilerBridge',
            ' */',
            '',
            '// Export all types',
            "export * from './types'",
            '',
            '// Export all mappers',
            "export * from './mappers'",
            ''
        ]

        return lines.join('\n')
    }

    /**
     * Print generation summary
     */
    private static printSummary(output: CompilerOutput): void {
        console.log('')
        console.log('  📊 Generation Summary:')
        console.log(`     Types: ${output.metadata.typeCount}`)
        console.log(`     Interfaces: ${output.metadata.interfaceCount}`)
        console.log(`     Lines of code: ${output.metadata.linesOfCode}`)

        if (output.metadata.warnings.length > 0) {
            console.log('')
            console.log(`  ⚠️  Warnings (${output.metadata.warnings.length}):`)
            output.metadata.warnings.forEach(w => console.log(`     - ${w}`))
        }

        console.log('')
        console.log('  ✅ TypeScript generation complete!')
    }
}
