import { RouteManifest, camelCase } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { toTypeName, toMethodName } from './names'

export class TypeGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const lines: string[] = []
    
    const hasSchemas = manifest.routes.some(r => r.schema && Object.keys(r.schema).length > 0)

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)

    lines.push(`export interface ApiResponse<T = unknown> {`)
    lines.push(`  success: boolean`)
    lines.push(`  message?: string`)
    lines.push(`  data: T`)
    lines.push(`  meta?: PaginationMeta`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export interface PaginationMeta {`)
    lines.push(`  current_page: number`)
    lines.push(`  last_page: number`)
    lines.push(`  per_page: number`)
    lines.push(`  total: number`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export interface ApiError {`)
    lines.push(`  success: false`)
    lines.push(`  message: string`)
    lines.push(`  errors?: Record<string, string[]>`)
    lines.push(`  status?: number`)
    lines.push(`}`)
    lines.push(``)

    // Generate explicit models if they exist
    if (manifest.models && manifest.models.length > 0) {
      for (const model of manifest.models) {
        lines.push(`export interface ${model.name} {`)
        for (const col of model.columns) {
          if (model.hidden && model.hidden.includes(col.name)) continue;
          const tsType = this.mapSqlTypeToTs(col.type);
          const finalTsType = col.nullable ? `${tsType} | null` : tsType;
          const safeName = camelCase(col.name).match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelCase(col.name) : `"${camelCase(col.name)}"`;
          lines.push(`  ${safeName}: ${finalTsType}`)
        }
        if (model.appends && model.appends.length > 0) {
          for (const append of model.appends) {
            const safeAppend = camelCase(append).match(/^[a-zA-Z_$][a-zA-Z0-9_$]*$/) ? camelCase(append) : `"${camelCase(append)}"`;
            lines.push(`  ${safeAppend}?: unknown`)
          }
        }
        lines.push(`}`)
        lines.push(``)
      }
    } else {
      // Generate placeholder types per resource if no models extracted
      const resources = new Set(
        manifest.routes.map((r) => r.path.replace(/^\//, '').split('/')[0])
      )

      for (const resource of resources) {
        const typeName = toTypeName(resource ?? '')
        lines.push(`export interface ${typeName} {`)
        lines.push(`  id: number`)
        lines.push(`  // TODO: Add ${resource} fields`)
        lines.push(`  createdAt?: string`)
        lines.push(`  updatedAt?: string`)
        lines.push(`}`)
        lines.push(``)
      }
    }
    // Zod schemas are now generated by SchemaGenerator

    await fs.writeFile(path.join(outputDir, 'types.ts'), lines.join('\n'))
  }

  private static mapSqlTypeToTs(sqlType: string): string {
    const type = sqlType.toLowerCase();
    if (type.includes('int') || type.includes('decimal') || type.includes('float') || type.includes('double')) return 'number';
    if (type.includes('bool') || type.includes('tinyint(1)')) return 'boolean';
    if (type.includes('json')) return 'unknown'; // Use unknown for JSON to enforce type-checking
    return 'string';
  }
}
