import { RouteManifest } from '@routesync/core'
import path from 'path'
import fs from 'fs-extra'
import { toTypeName } from './names'

export class TypeGenerator {
  static async generate(manifest: RouteManifest, outputDir: string): Promise<void> {
    const lines: string[] = []

    lines.push(`// Auto-generated by routesync. Do not edit manually.`)
    lines.push(``)
    lines.push(`export interface ApiResponse<T = any> {`)
    lines.push(`  success: boolean`)
    lines.push(`  message?: string`)
    lines.push(`  data: T`)
    lines.push(`  meta?: PaginationMeta`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export interface PaginationMeta {`)
    lines.push(`  current_page: number`)
    lines.push(`  last_page: number`)
    lines.push(`  per_page: number`)
    lines.push(`  total: number`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export interface ApiError {`)
    lines.push(`  success: false`)
    lines.push(`  message: string`)
    lines.push(`  errors?: Record<string, string[]>`)
    lines.push(`  status?: number`)
    lines.push(`}`)
    lines.push(``)

    // Generate placeholder types per resource
    const resources = new Set(
      manifest.routes.map((r) => r.path.replace(/^\//, '').split('/')[0])
    )

    for (const resource of resources) {
      const typeName = toTypeName(resource ?? '')
      lines.push(`export interface ${typeName} {`)
      lines.push(`  id: number`)
      lines.push(`  // TODO: Add ${resource} fields`)
      lines.push(`  created_at?: string`)
      lines.push(`  updated_at?: string`)
      lines.push(`}`)
      lines.push(``)
    }

    await fs.writeFile(path.join(outputDir, 'types.ts'), lines.join('\n'))
  }
}
