import { relationGate, relationEqual } from '../../../semantic/foundation/semanticRelations';
/** Immutable constructors for scanner-level PHP syntax AST. */
import type { SourceRange, AstIdentifier, PhpArgument, PhpArrayEntry, PhpAstValue, PhpAstValueNode, PhpClosureCapture, PhpParameter, PhpPropertyPath, PhpBlock, PhpArrayKey, PhpBinaryOperator, PhpUnaryOperator, PhpCastType, PhpMatchArm, PhpStatement, PhpAccessMode, PhpAssignmentOperator, PhpIfAlternative, PhpForeachTarget, PhpForClause, PhpCatchClause, PhpFinallyClause, PhpSwitchCase } from './phpAstTypes';

export const PhpAstFactory = Object.freeze({
    stringLiteral(value: string): PhpAstValueNode { return Object.freeze({ kind: 'literal', literalType: 'string', value }); },
    interpolatedString(parts: readonly import('./phpAstExpressionTypes').PhpInterpolatedStringPart[]): PhpAstValueNode { return Object.freeze({ kind: 'interpolated_string', parts: Object.freeze([...parts]) }); },
    numberLiteral(raw: string): PhpAstValueNode { return Object.freeze({ kind: 'literal', literalType: 'number', value: Number(raw) }); },
    booleanLiteral(value: boolean): PhpAstValueNode { return Object.freeze({ kind: 'literal', literalType: 'boolean', value }); },
    nullLiteral(): PhpAstValueNode { return Object.freeze({ kind: 'literal', literalType: 'null' }); },
    variableReference(name: AstIdentifier): PhpAstValueNode { return Object.freeze({ kind: 'variable_reference', name }); },
    magicConstant(value: import('./phpAstExpressionTypes').PhpMagicConstant): PhpAstValueNode { return Object.freeze({ kind: 'magic_constant', value }); },
    constantReference(name: AstIdentifier): PhpAstValueNode { return Object.freeze({ kind: 'constant_reference', name }); },
    propertyPath(root: AstIdentifier, steps: readonly AstIdentifier[]): PhpPropertyPath {
        const frozen = Object.freeze([...steps]);
        return relationGate(
            relationEqual(frozen.length, 0),
            () => Object.freeze({ kind: 'single' as const, root, steps: [] as const }),
            () => Object.freeze({ kind: 'chain' as const, root, steps: frozen }),
        );
    },
    propertyAccess(target: PhpPropertyPath, receiver: PhpAstValue, property: AstIdentifier, access: PhpAccessMode): PhpAstValueNode { return Object.freeze({ kind: 'property_access', target, receiver, property, access }); },
    methodChain(target: PhpPropertyPath, receiver: PhpAstValue, property: AstIdentifier, args: readonly PhpArgument[], access: PhpAccessMode): PhpAstValueNode { return Object.freeze({ kind: 'method_chain', target, receiver, property, arguments: Object.freeze([...args]), access }); },
    resourceSingle(resourceName: AstIdentifier, argument: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'resource_single', resourceName, argument }); },
    resourceCollection(resourceName: AstIdentifier, argument: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'resource_collection', resourceName, argument }); },
    staticCall(className: AstIdentifier, method: AstIdentifier, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'static_call', className, method, arguments: Object.freeze([...args]) }); },
    classReference(className: AstIdentifier): PhpAstValueNode { return Object.freeze({ kind: 'class_reference', className }); },
    classConstant(owner: AstIdentifier, name: AstIdentifier): PhpAstValueNode { return Object.freeze({ kind: 'class_constant', owner, name }); },
    construct(className: AstIdentifier, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'construct', className, arguments: Object.freeze([...args]) }); },
    dynamicConstruct(classExpression: PhpAstValue, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'dynamic_construct', classExpression, arguments: Object.freeze([...args]) }); },
    anonymousClassConstruct(value: import('./phpAstExpressionTypes').PhpAnonymousClass, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'anonymous_class_construct', class: value, arguments: Object.freeze([...args]) }); },
    instanceOf(expression: PhpAstValue, className: AstIdentifier): PhpAstValueNode { return Object.freeze({ kind: 'instance_of', expression, className }); },
    ternaryExpression(condition: PhpAstValue, trueBranch: PhpAstValue, falseBranch: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'ternary_expression', condition, trueBranch, falseBranch }); },
    arrayAccess(target: PhpAstValue, index: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'array_access', target, index }); },
    functionCall(functionName: AstIdentifier, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'function_call', functionName, arguments: Object.freeze([...args]) }); },
    callableCall(callable: PhpAstValue, args: readonly PhpArgument[]): PhpAstValueNode { return Object.freeze({ kind: 'callable_call', callable, arguments: Object.freeze([...args]) }); },
    shortTernary(condition: PhpAstValue, falseBranch: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'short_ternary', condition, falseBranch }); },
    nullCoalesce(left: PhpAstValue, right: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'null_coalesce', left, right }); },
    binaryExpression(operator: PhpBinaryOperator, left: PhpAstValue, right: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'binary_expression', operator, left, right }); },
    unaryExpression(operator: PhpUnaryOperator, operand: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'unary_expression', operator, operand }); },
    castExpression(castType: PhpCastType, operand: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'cast_expression', castType, operand }); },
    nestedArray(entries: readonly PhpArrayEntry[]): PhpAstValueNode { return Object.freeze({ kind: 'nested_array', entries: Object.freeze([...entries]) }); },
    matchConditional(conditions: readonly PhpAstValue[], value: PhpAstValue): PhpMatchArm { return Object.freeze({ kind: 'conditional', conditions: Object.freeze([...conditions]), value }); },
    matchDefault(value: PhpAstValue): PhpMatchArm { return Object.freeze({ kind: 'default', value }); },
    matchExpression(subject: PhpAstValue, arms: readonly PhpMatchArm[]): PhpAstValueNode { return Object.freeze({ kind: 'match_expression', subject, arms: Object.freeze([...arms]) }); },
    variableAssignment(names: readonly AstIdentifier[]): import('./phpAstTypes').PhpAssignmentTarget { return Object.freeze({ kind: 'variables', names: Object.freeze([...names]) }); },
    assignment(target: import('./phpAstTypes').PhpAssignmentTarget, operator: PhpAssignmentOperator, reference: import('./phpAstTypes').PhpAssignmentReference, value: PhpAstValue, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'assignment', target, operator, reference, value, source }); },
    assignmentExpression(target: import('./phpAstTypes').PhpAssignmentTarget, operator: PhpAssignmentOperator, reference: import('./phpAstTypes').PhpAssignmentReference, value: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'assignment_expression', target, operator, reference, value }); },
    ifStatement(condition: PhpAstValue, thenBlock: PhpBlock, alternative: PhpIfAlternative, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'if_statement', condition, thenBlock, alternative, source }); },
    foreachStatement(iterable: PhpAstValue, target: PhpForeachTarget, body: PhpBlock, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'foreach_statement', iterable, target, body, source }); },
    forStatement(initializer: PhpForClause, condition: PhpForClause, update: PhpForClause, body: PhpBlock, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'for_statement', initializer, condition, update, body, source }); },
    whileStatement(condition: PhpAstValue, body: PhpBlock, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'while_statement', condition, body, source }); },
    switchStatement(subject: PhpAstValue, cases: readonly PhpSwitchCase[], source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'switch_statement', subject, cases: Object.freeze([...cases]), source }); },
    tryStatement(body: PhpBlock, catches: readonly PhpCatchClause[], finallyBlock: PhpFinallyClause, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'try_statement', body, catches: Object.freeze([...catches]), finallyBlock, source }); },
    throwStatement(expression: PhpAstValue, source: import('./phpAstTypes').TokenDescriptor): PhpStatement { return Object.freeze({ kind: 'throw_statement', expression, source }); },
    closure(parameters: readonly PhpParameter[], captures: readonly PhpClosureCapture[], returnType: import('./phpAstExpressionTypes').PhpClosureReturnTypeAst, body: PhpBlock): PhpAstValueNode { return Object.freeze({ kind: 'closure', parameters: Object.freeze([...parameters]), captures: Object.freeze([...captures]), returnType, body }); },
    arrowFunction(parameters: readonly PhpParameter[], body: PhpAstValue): PhpAstValueNode { return Object.freeze({ kind: 'arrow_function', parameters: Object.freeze([...parameters]), body }); },
    unsupported(tokens: readonly import('./phpAstTypes').TokenDescriptor[]): PhpAstValueNode { return Object.freeze({ kind: 'unsupported', reason: 'unclassified_expression', tokens: Object.freeze([...tokens]) }); },
});
