/**
 * MapperCodeBuilder.ts
 *
 * Pure Functional Code Builder for API Read Mappers.
 * Transforms ResourceMapperDefinition structures into strongly-typed TypeScript mapping functions.
 * Pure Zero-Map Template Emission (0 .map per field, 0 loop, 0 regex guessing).
 *
 * @module compiler/generators/mapper-generation
 */

import type { ResourceMapperDefinition } from '../../artifacts/ResourceMappersArtifact';

export interface MapperCodeBuilderOptions {
    readonly emitComments?: boolean;
}

/**
 * Formats single ResourceMapperDefinition with 0 .map per field.
 * Complete body is already resolved at Upstream Origin Boundary.
 */
export function formatResourceMapper(def: ResourceMapperDefinition): string {
    return `export const ${def.functionName} = (api: ${def.apiType}): ${def.transformedType} => ({\n${def.body}\n});`;
}

const commentHeaders = [
    '',
    '// Auto-generated by RouteSync MapperGeneratorPass. Do not edit directly.\n\n'
] as const;

export class MapperCodeBuilder {
    private readonly emitComments: boolean;

    constructor({ emitComments = true }: MapperCodeBuilderOptions = {}) {
        this.emitComments = emitComments;
        Object.freeze(this);
    }

    build(definitions: readonly ResourceMapperDefinition[]): string {
        const readTypeImports = new Set<string>();
        for (const def of definitions) {
            if (def.transformedType) {
                readTypeImports.add(def.transformedType);
            }
        }

        const imports: string[] = [];
        if (readTypeImports.size > 0) {
            const sorted = Array.from(readTypeImports).sort();
            imports.push(`import type {\n  ${sorted.join(',\n  ')}\n} from '../types/api-read';`);
        }

        const mappers = definitions
            .map(def => formatResourceMapper(def))
            .join('\n\n');

        const header = commentHeaders[Number(this.emitComments)];
        const importBlock = imports.length > 0 ? `${imports.join('\n\n')}\n\n` : '';

        return `${header}${importBlock}${mappers}\n`;
    }
}