import type { MigrationAst } from '../../../types/upstream/ast';
import type { ColumnDefinition, DatabaseType, ForeignKeyAction, ForeignKey, IndexDefinition } from '../../../types/upstream/databaseVocabulary';
import type { MigrationOperation } from '../../../types/upstream/migration';
import type { Sequence, Columns, Indexes, ForeignKeys } from '../../../types/upstream/collections';
import type { PrimitiveVocabulary, Presence, Nullability } from '../../../types/upstream/primitiveVocabulary';
import type { SourceSpan } from '../../../types/upstream/provenance';
import type { SourceFile, TableName, DomainTypeName } from '../../../types/upstream/names';
import { createColumnName, createIndexName, createTableName } from '../../../types/domain/modelValueFactories';
import type { TokenDescriptor } from '../LaravelSourceLexer';
import type { PhpMethodAst } from '../lexer/phpMethodAstTypes';

export type MigrationSourceAst = {
    readonly kind: 'migration_source_ast';
    readonly methods: readonly PhpMethodAst[];
    readonly tokens: readonly TokenDescriptor[];
    readonly source: SourceSpan;
};

export type MigrationProducerInput = {
    readonly source: MigrationSourceAst;
    readonly file: SourceFile;
    readonly sourceSpan: SourceSpan;
};

export interface MigrationProducer {
    readonly produce: (input: MigrationProducerInput) => MigrationAst;
}

const seq = <T>(items: readonly T[]): Sequence<T> => items.reduceRight<Sequence<T>>((tail, head) => ({ kind: 'cons', head, tail }), { kind: 'empty' });
const primitive = (kind: PrimitiveVocabulary['kind']): PrimitiveVocabulary => ({ kind });
const nullability = (nullable: boolean): Nullability => nullable ? { kind: 'nullable' } : { kind: 'non_nullable' };
const presence: Presence = { kind: 'required' };
const truth = (value: boolean) => ({ kind: 'truth_value' as const, value });

function source(file: string, line = 0): SourceSpan {
    return { kind: 'source_span', file: { kind: 'source_file', value: { kind: 'string_value', value: file } }, start: { kind: 'number_value', value: line }, end: { kind: 'number_value', value: line } };
}

function databaseType(method: string): DatabaseType {
    switch (method) {
        case 'boolean': return { kind: 'boolean' };
        case 'json': case 'jsonb': return { kind: 'json' };
        case 'text': case 'longText': case 'mediumText': return { kind: 'text' };
        case 'timestamp': case 'dateTime': case 'date': return { kind: 'date_time' };
        case 'decimal': case 'float': case 'double': return { kind: 'decimal', precision: { kind: 'number_value', value: 0 }, scale: { kind: 'number_value', value: 0 } };
        case 'id': case 'bigInteger': case 'unsignedBigInteger': case 'foreignId': return { kind: 'integer', width: { kind: 'big' }, signed: truth(!method.startsWith('unsigned') && method !== 'foreignId') };
        case 'integer': case 'unsignedInteger': return { kind: 'integer', width: { kind: 'normal' }, signed: truth(!method.startsWith('unsigned')) };
        case 'tinyInteger': case 'unsignedTinyInteger': return { kind: 'integer', width: { kind: 'tiny' }, signed: truth(!method.startsWith('unsigned')) };
        case 'smallInteger': case 'unsignedSmallInteger': return { kind: 'integer', width: { kind: 'small' }, signed: truth(!method.startsWith('unsigned')) };
        default: return { kind: 'string', length: { kind: 'number_value', value: 255 } };
    }
}

function column(method: string, name: string, nullable: boolean, primary: boolean, file: string, line: number): ColumnDefinition {
    const database = databaseType(method);
    const semantic: PrimitiveVocabulary = database.kind === 'boolean' ? primitive('boolean') : database.kind === 'json' ? primitive('json') : database.kind === 'date_time' ? primitive('date_time') : database.kind === 'integer' || database.kind === 'decimal' ? primitive('number') : primitive('string');
    return { kind: 'column', name: createColumnName(name), databaseType: database, semanticType: semantic, presence, nullability: nullability(nullable), default: { kind: 'none' }, primary: truth(method === 'id' || primary), autoGenerated: truth(method === 'id'), source: source(file, line) };
}

function collectIndexArguments(tokens: readonly TokenDescriptor[], start: number): { readonly columns: readonly string[]; readonly name: string | undefined } {
    let cursor = start;
    while (cursor < tokens.length && tokens[cursor].value !== '(' && tokens[cursor].value !== ';') cursor += 1;
    if (tokens[cursor]?.value !== '(') return { columns: [], name: undefined };
    cursor += 1;
    const columns: string[] = [];
    let arrayDepth = 0;
    let sawArray = false;
    let arrayClosed = false;
    let explicitName: string | undefined;
    for (; cursor < tokens.length && tokens[cursor].value !== ';'; cursor += 1) {
        const value = tokens[cursor].value;
        if (value === '[') { sawArray = true; arrayDepth += 1; continue; }
        if (value === ']') { arrayDepth = Math.max(0, arrayDepth - 1); arrayClosed = true; continue; }
        if (tokens[cursor].type !== 'STRING') continue;
        if (arrayDepth > 0 || (!sawArray && columns.length === 0)) columns.push(value);
        else if (explicitName === undefined && (!sawArray || arrayClosed)) explicitName = value;
    }
    return { columns, name: explicitName };
}

function createOperations(tokens: readonly TokenDescriptor[], file: string): readonly MigrationOperation[] {
    const operations: MigrationOperation[] = [];
    for (let i = 0; i + 4 < tokens.length; i += 1) {
        if (tokens[i].value !== 'Schema' || tokens[i + 1].value !== '::') continue;
        const action = tokens[i + 2].value;
        if (action !== 'create' && action !== 'table') continue;
        const table = tokens[i + 4];
        if (!table || table.type !== 'STRING') continue;
        const columns: ColumnDefinition[] = [];
        const indexItems: IndexDefinition[] = [];
        const foreignKeyItems: ForeignKey[] = [];
        let k = i + 5;
        while (k < tokens.length && tokens[k].value !== '{') k += 1;
        for (k += 1; k + 3 < tokens.length && tokens[k].value !== '}'; k += 1) {
            if (tokens[k].value !== '$table' || (tokens[k + 1].value !== '->' && tokens[k + 1].value !== '?->')) continue;
            const method = tokens[k + 2].value;
            const name = tokens[k + 4]?.type === 'STRING' ? tokens[k + 4].value : method === 'id' ? 'id' : undefined;
            if (!name && method !== 'timestamps' && method !== 'softDeletes') continue;
            if (method === 'timestamps') { columns.push(column('timestamp', 'created_at', true, false, file, tokens[k].line), column('timestamp', 'updated_at', true, false, file, tokens[k].line)); continue; }
            if (method === 'softDeletes') { columns.push(column('timestamp', 'deleted_at', true, false, file, tokens[k].line)); continue; }
            let nullable = false;
            let primary = false;
            let chainedUnique = false;
            let chainedIndex = false;
            for (let p = k + 5; p < Math.min(tokens.length, k + 30) && tokens[p].value !== ';'; p += 1) {
                if (tokens[p].value === 'nullable') nullable = true;
                if (tokens[p].value === 'primary') primary = true;
                if (tokens[p].value === 'unique') chainedUnique = true;
                if (tokens[p].value === 'index') chainedIndex = true;
            }
            columns.push(column(method, name as string, nullable, primary, file, tokens[k].line));
            if (method !== 'foreignId' && (chainedUnique || chainedIndex)) {
                const suffix = chainedUnique ? 'unique' : 'index';
                indexItems.push({ kind: 'index', columns: { kind: 'column_names', items: seq([createColumnName(name as string)]) }, unique: truth(chainedUnique), name: createIndexName(`${table.value}_${name}_${suffix}`), source: source(file, tokens[k].line) });
            }
        }
        const tableName: TableName = createTableName(table.value);
        for (let m = i + 5; m + 3 < tokens.length && tokens[m].value !== '}'; m += 1) {
            if (tokens[m].value !== '$table' || (tokens[m + 1].value !== '->' && tokens[m + 1].value !== '?->')) continue;
            const method = tokens[m + 2].value;
            const args: string[] = [];
            for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) if (tokens[a].type === 'STRING') args.push(tokens[a].value);
            const span = source(file, tokens[m].line);
            if (method === 'unique' || method === 'index') {
                const parsedIndex = collectIndexArguments(tokens, m + 3);
                if (parsedIndex.columns.length > 0) {
                    const unique = truth(method === 'unique');
                    const indexName = parsedIndex.name ?? `${table.value}_${parsedIndex.columns.join('_')}_${method}`;
                    indexItems.push({ kind: 'index', columns: { kind: 'column_names', items: seq(parsedIndex.columns.map(createColumnName)) }, unique, name: createIndexName(indexName), source: span });
                }
            }
            if (method === 'foreignId' && args.length > 0) {
                const columnName = args[0];
                let constrained = false;
                let onDelete: ForeignKeyAction = { kind: 'no_action' };
                for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) {
                    if (tokens[a].value === 'constrained') constrained = true;
                    if (tokens[a].value === 'cascadeOnDelete') onDelete = { kind: 'cascade' };
                    if (tokens[a].value === 'nullOnDelete') onDelete = { kind: 'set_null' };
                    if (tokens[a].value === 'restrictOnDelete') onDelete = { kind: 'restrict' };
                }
                if (constrained) {
                    const constrainedArgument = (() => {
                        for (let a = m + 3; a + 2 < Math.min(tokens.length, m + 40) && tokens[a].value !== ';'; a += 1) if (tokens[a].value === 'constrained' && tokens[a + 2]?.type === 'STRING') return tokens[a + 2].value;
                        return undefined;
                    })();
                    const base = columnName.endsWith('_id') ? columnName.slice(0, -3) : columnName;
                    const targetTable = constrainedArgument ?? `${base}s`;
                    const referencesModel: DomainTypeName = { kind: 'domain_type_name', value: { kind: 'string_value', value: targetTable } };
                    foreignKeyItems.push({ kind: 'foreign_key', column: createColumnName(columnName), referencesModel, referencesColumn: createColumnName('id'), onDelete, onUpdate: { kind: 'no_action' }, source: span });
                }
            }
            if (method === 'foreign' && args.length > 0) {
                let referencesColumn = 'id';
                let referencesTable = '';
                let onDelete: ForeignKeyAction = { kind: 'no_action' };
                for (let a = m + 3; a + 2 < Math.min(tokens.length, m + 40) && tokens[a].value !== ';'; a += 1) {
                    if (tokens[a].value === 'references' && tokens[a + 2]?.type === 'STRING') referencesColumn = tokens[a + 2].value;
                    if (tokens[a].value === 'on' && tokens[a + 2]?.type === 'STRING') referencesTable = tokens[a + 2].value;
                    if (tokens[a].value === 'cascadeOnDelete') onDelete = { kind: 'cascade' };
                    if (tokens[a].value === 'nullOnDelete') onDelete = { kind: 'set_null' };
                    if (tokens[a].value === 'restrictOnDelete') onDelete = { kind: 'restrict' };
                }
                if (referencesTable.length > 0) foreignKeyItems.push({ kind: 'foreign_key', column: createColumnName(args[0]), referencesModel: { kind: 'domain_type_name', value: { kind: 'string_value', value: referencesTable } }, referencesColumn: createColumnName(referencesColumn), onDelete, onUpdate: { kind: 'no_action' }, source: span });
            }
        }
        operations.push({ kind: 'create_table', table: tableName, columns: { kind: 'columns', items: seq(columns) }, indexes: { kind: 'indexes', items: seq(indexItems) }, foreignKeys: { kind: 'foreign_keys', items: seq(foreignKeyItems) } });
    }
    return Object.freeze(operations);
}

export const migrationProducer: MigrationProducer = {
    produce: (input) => {
        const operations = createOperations(input.source.tokens, input.file.value.value);
        return {
            kind: 'migration_ast',
            definition: {
                kind: 'migration_definition',
                file: input.file,
                operations: { kind: 'migration_operations', items: seq(operations) },
                source: input.sourceSpan,
            },
            source: input.sourceSpan,
        };
    },
};
