import type { MigrationAst } from '../../../types/upstream/ast';
import type { ColumnDefinition, DatabaseType } from '../../../types/upstream/databaseVocabulary';
import type { MigrationOperation } from '../../../types/upstream/migration';
import type { Sequence, Columns, Indexes, ForeignKeys } from '../../../types/upstream/collections';
import type { PrimitiveVocabulary, Presence, Nullability } from '../../../types/upstream/primitiveVocabulary';
import type { SourceSpan } from '../../../types/upstream/provenance';
import type { SourceFile, TableName } from '../../../types/upstream/names';
import { createColumnName, createTableName } from '../../../types/domain/modelValueFactories';
import { LaravelSourceLexer, type TokenDescriptor } from '../LaravelSourceLexer';
import { collectPhpFiles } from './scannerUtils';
import { readSourceText } from './scannerUtils';
import * as path from 'node:path';

const seq = <T>(items: readonly T[]): Sequence<T> => items.reduceRight<Sequence<T>>((tail, head) => ({ kind: 'cons', head, tail }), { kind: 'empty' });
const source = (file: string, line = 0): SourceSpan => ({ kind: 'source_span', file: { kind: 'source_file', value: { kind: 'string_value', value: file } }, start: { kind: 'number_value', value: line }, end: { kind: 'number_value', value: line } });
const primitive = (kind: PrimitiveVocabulary['kind']): PrimitiveVocabulary => ({ kind });
const nullability = (nullable: boolean): Nullability => nullable ? { kind: 'nullable' } : { kind: 'non_null' };
const presence: Presence = { kind: 'required' };
const truth = (value: boolean) => ({ kind: 'truth_value' as const, value });

function databaseType(method: string): DatabaseType {
  switch (method) {
    case 'boolean': return { kind: 'boolean' };
    case 'json': case 'jsonb': return { kind: 'json' };
    case 'text': case 'longText': case 'mediumText': return { kind: 'text' };
    case 'timestamp': case 'dateTime': case 'date': return { kind: 'date_time' };
    case 'decimal': case 'float': case 'double': return { kind: 'decimal', precision: { kind: 'number_value', value: 0 }, scale: { kind: 'number_value', value: 0 } };
    case 'integer': case 'unsignedInteger': case 'tinyInteger': case 'smallInteger': case 'bigInteger': case 'unsignedBigInteger': case 'foreignId': return { kind: 'integer', width: { kind: 'normal' }, signed: truth(!method.startsWith('unsigned') && method !== 'foreignId') };
    default: return { kind: 'string', length: { kind: 'number_value', value: 255 } };
  }
}
function column(method: string, name: string, nullable: boolean, file: string, line: number): ColumnDefinition {
  const database = databaseType(method);
  const semantic: PrimitiveVocabulary = database.kind === 'boolean' ? primitive('boolean') : database.kind === 'json' ? primitive('json') : database.kind === 'date_time' ? primitive('date_time') : database.kind === 'integer' || database.kind === 'decimal' ? primitive('number') : primitive('string');
  return { kind: 'column', name: createColumnName(name), databaseType: database, semanticType: semantic, presence, nullability: nullability(nullable), default: { kind: 'none' }, primary: truth(method === 'id'), autoGenerated: truth(method === 'id'), source: source(file, line) };
}
function createOperations(tokens: readonly TokenDescriptor[], file: string): readonly MigrationOperation[] {
  const operations: MigrationOperation[] = [];
  for (let i = 0; i + 4 < tokens.length; i += 1) {
    if (tokens[i].value !== 'Schema' || tokens[i + 1].value !== '::') continue;
    const action = tokens[i + 2].value;
    if (action !== 'create' && action !== 'table') continue;
    const table = tokens[i + 4];
    if (!table || table.type !== 'STRING') continue;
    const columns: ColumnDefinition[] = [];
    let k = i + 5;
    while (k < tokens.length && tokens[k].value !== '{') k += 1;
    for (k += 1; k + 3 < tokens.length && tokens[k].value !== '}'; k += 1) {
      if (tokens[k].value !== '$table' || (tokens[k + 1].value !== '->' && tokens[k + 1].value !== '?->')) continue;
      const method = tokens[k + 2].value;
      const name = tokens[k + 4]?.type === 'STRING' ? tokens[k + 4].value : method === 'id' ? 'id' : undefined;
      if (!name && method !== 'timestamps' && method !== 'softDeletes') continue;
      if (method === 'timestamps') { columns.push(column('timestamp', 'created_at', true, file, tokens[k].line), column('timestamp', 'updated_at', true, file, tokens[k].line)); continue; }
      if (method === 'softDeletes') { columns.push(column('timestamp', 'deleted_at', true, file, tokens[k].line)); continue; }
      let nullable = false;
      for (let p = k + 5; p < Math.min(tokens.length, k + 18) && tokens[p].value !== ';'; p += 1) if (tokens[p].value === 'nullable') nullable = true;
      columns.push(column(method, name as string, nullable, file, tokens[k].line));
    }
    const tableName: TableName = createTableName(table.value);
    const cols: Columns = { kind: 'columns', items: seq(columns) };
    const indexes: Indexes = { kind: 'indexes', items: { kind: 'empty' } };
    const foreignKeys: ForeignKeys = { kind: 'foreign_keys', items: { kind: 'empty' } };
    operations.push({ kind: 'create_table', table: tableName, columns: cols, indexes, foreignKeys });
  }
  return Object.freeze(operations);
}
export async function scanMigrationAsts(projectRoot: string): Promise<readonly MigrationAst[]> {
  const directory = path.join(projectRoot, 'database', 'migrations');
  const files = await collectPhpFiles(directory);
  const asts: MigrationAst[] = [];
  for (const file of files) {
    const tokens = LaravelSourceLexer.tokenize(await readSourceText(file));
    const operations = createOperations(tokens, file);
    if (operations.length === 0) continue;
    const span = source(file);
    asts.push({ kind: 'migration_ast', definition: { kind: 'migration_definition', file: { kind: 'source_file', value: { kind: 'string_value', value: file } } as SourceFile, operations: { kind: 'migration_operations', items: seq(operations) }, source: span }, source: span });
  }
  return Object.freeze(asts);
}
