import type { SourceProjectIdentity } from '../../../types/upstream/highLevelSourceModel';
import type { MigrationAst } from '../../../types/upstream/ast';
import type { ColumnDefinition, DatabaseType, ForeignKeyAction } from '../../../types/upstream/databaseVocabulary';
import type { MigrationOperation } from '../../../types/upstream/migration';
import type { Sequence, Columns, Indexes, ForeignKeys } from '../../../types/upstream/collections';
import type { PrimitiveVocabulary, Presence, Nullability } from '../../../types/upstream/primitiveVocabulary';
import type { SourceSpan } from '../../../types/upstream/provenance';
import type { SourceFile, TableName, DomainTypeName } from '../../../types/upstream/names';
import { createColumnName, createTableName } from '../../../types/domain/modelValueFactories';
import { createIndexName } from '../../../types/domain/modelValueFactories';
import { LaravelSourceLexer, type TokenDescriptor } from '../LaravelSourceLexer';
import { collectPhpFiles } from './scannerUtils';
import { readSourceText } from './scannerUtils';
import * as path from 'node:path';

const seq = <T>(items: readonly T[]): Sequence<T> => items.reduceRight<Sequence<T>>((tail, head) => ({ kind: 'cons', head, tail }), { kind: 'empty' });
const source = (file: string, line = 0): SourceSpan => ({ kind: 'source_span', file: { kind: 'source_file', value: { kind: 'string_value', value: file } }, start: { kind: 'number_value', value: line }, end: { kind: 'number_value', value: line } });
const primitive = (kind: PrimitiveVocabulary['kind']): PrimitiveVocabulary => ({ kind });
const nullability = (nullable: boolean): Nullability => nullable ? { kind: 'nullable' } : { kind: 'non_nullable' };
const presence: Presence = { kind: 'required' };
const truth = (value: boolean) => ({ kind: 'truth_value' as const, value });

function databaseType(method: string): DatabaseType {
  switch (method) {
    case 'boolean': return { kind: 'boolean' };
    case 'json': case 'jsonb': return { kind: 'json' };
    case 'text': case 'longText': case 'mediumText': return { kind: 'text' };
    case 'timestamp': case 'dateTime': case 'date': return { kind: 'date_time' };
    case 'decimal': case 'float': case 'double': return { kind: 'decimal', precision: { kind: 'number_value', value: 0 }, scale: { kind: 'number_value', value: 0 } };
    case 'id': case 'bigInteger': case 'unsignedBigInteger': case 'foreignId': return { kind: 'integer', width: { kind: 'big' }, signed: truth(!method.startsWith('unsigned') && method !== 'foreignId') };
    case 'integer': case 'unsignedInteger': return { kind: 'integer', width: { kind: 'normal' }, signed: truth(!method.startsWith('unsigned')) };
    case 'tinyInteger': case 'unsignedTinyInteger': return { kind: 'integer', width: { kind: 'tiny' }, signed: truth(!method.startsWith('unsigned')) };
    case 'smallInteger': case 'unsignedSmallInteger': return { kind: 'integer', width: { kind: 'small' }, signed: truth(!method.startsWith('unsigned')) };
    default: return { kind: 'string', length: { kind: 'number_value', value: 255 } };
  }
}
function column(method: string, name: string, nullable: boolean, primary: boolean, file: string, line: number): ColumnDefinition {
  const database = databaseType(method);
  const semantic: PrimitiveVocabulary = database.kind === 'boolean' ? primitive('boolean') : database.kind === 'json' ? primitive('json') : database.kind === 'date_time' ? primitive('date_time') : database.kind === 'integer' || database.kind === 'decimal' ? primitive('number') : primitive('string');
  return { kind: 'column', name: createColumnName(name), databaseType: database, semanticType: semantic, presence, nullability: nullability(nullable), default: { kind: 'none' }, primary: truth(method === 'id' || primary), autoGenerated: truth(method === 'id'), source: source(file, line) };
}
function collectIndexArguments(tokens: readonly TokenDescriptor[], start: number): { readonly columns: readonly string[]; readonly name: string | undefined } {
  let cursor = start;
  while (cursor < tokens.length && tokens[cursor].value !== '(' && tokens[cursor].value !== ';') cursor += 1;
  if (tokens[cursor]?.value !== '(') return { columns: [], name: undefined };
  cursor += 1;
  const columns: string[] = [];
  let arrayDepth = 0;
  let sawArray = false;
  let arrayClosed = false;
  let explicitName: string | undefined;
  for (; cursor < tokens.length && tokens[cursor].value !== ';'; cursor += 1) {
    const value = tokens[cursor].value;
    if (value === '[') { sawArray = true; arrayDepth += 1; continue; }
    if (value === ']') { arrayDepth = Math.max(0, arrayDepth - 1); arrayClosed = true; continue; }
    if (tokens[cursor].type !== 'STRING') continue;
    if (arrayDepth > 0 || (!sawArray && columns.length === 0)) columns.push(value);
    else if (explicitName === undefined && (!sawArray || arrayClosed)) explicitName = value;
  }
  return { columns, name: explicitName };
}
function createOperations(tokens: readonly TokenDescriptor[], file: string): readonly MigrationOperation[] {
  const operations: MigrationOperation[] = [];
  for (let i = 0; i + 4 < tokens.length; i += 1) {
    if (tokens[i].value !== 'Schema' || tokens[i + 1].value !== '::') continue;
    const action = tokens[i + 2].value;
    if (action !== 'create' && action !== 'table') continue;
    const table = tokens[i + 4];
    if (!table || table.type !== 'STRING') continue;
    const columns: ColumnDefinition[] = [];
    const indexItems: import('../../../types/upstream/databaseVocabulary').IndexDefinition[] = [];
    const foreignKeyItems: import('../../../types/upstream/databaseVocabulary').ForeignKey[] = [];
    let k = i + 5;
    while (k < tokens.length && tokens[k].value !== '{') k += 1;
    for (k += 1; k + 3 < tokens.length && tokens[k].value !== '}'; k += 1) {
      if (tokens[k].value !== '$table' || (tokens[k + 1].value !== '->' && tokens[k + 1].value !== '?->')) continue;
      const method = tokens[k + 2].value;
      const name = tokens[k + 4]?.type === 'STRING' ? tokens[k + 4].value : method === 'id' ? 'id' : undefined;
      if (!name && method !== 'timestamps' && method !== 'softDeletes') continue;
      if (method === 'timestamps') { columns.push(column('timestamp', 'created_at', true, false, file, tokens[k].line), column('timestamp', 'updated_at', true, false, file, tokens[k].line)); continue; }
      if (method === 'softDeletes') { columns.push(column('timestamp', 'deleted_at', true, false, file, tokens[k].line)); continue; }
      let nullable = false;
      let primary = false;
      let chainedUnique = false;
      let chainedIndex = false;
      for (let p = k + 5; p < Math.min(tokens.length, k + 30) && tokens[p].value !== ';'; p += 1) {
        if (tokens[p].value === 'nullable') nullable = true;
        if (tokens[p].value === 'primary') primary = true;
        if (tokens[p].value === 'unique') chainedUnique = true;
        if (tokens[p].value === 'index') chainedIndex = true;
      }
      columns.push(column(method, name as string, nullable, primary, file, tokens[k].line));
      if (method !== 'foreignId' && (chainedUnique || chainedIndex)) {
        const suffix = chainedUnique ? 'unique' : 'index';
        indexItems.push({
          kind: 'index',
          columns: { kind: 'column_names', items: seq([createColumnName(name as string)]) },
          unique: truth(chainedUnique),
          name: createIndexName(`${table.value}_${name}_${suffix}`),
          source: source(file, tokens[k].line)
        });
      }
    }
    const tableName: TableName = createTableName(table.value);

    const indexes: Indexes = { kind: 'indexes', items: seq([]) };
    const foreignKeys: ForeignKeys = { kind: 'foreign_keys', items: seq([]) };
    // Preserve schema semantics directly from the migration tokens. These are
    // AST facts, not downstream guesses.
    for (let m = i + 5; m + 3 < tokens.length && tokens[m].value !== '}'; m += 1) {
      if (tokens[m].value !== '$table' || (tokens[m + 1].value !== '->' && tokens[m + 1].value !== '?->')) continue;
      const method = tokens[m + 2].value;
      const args: string[] = [];
      for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) {
        if (tokens[a].type === 'STRING') args.push(tokens[a].value);
        if (tokens[a].value === '->' && tokens[a + 1]?.value === 'cascadeOnDelete') break;
      }
      const span = source(file, tokens[m].line);
      if (method === 'unique' || method === 'index') {
        const parsedIndex = collectIndexArguments(tokens, m + 3);
        const indexColumns = parsedIndex.columns;
        if (indexColumns.length > 0) {
          const unique = truth(method === 'unique');
          const indexName = parsedIndex.name ?? `${table.value}_${indexColumns.join('_')}_${method}`;
          indexItems.push({ kind: 'index', columns: { kind: 'column_names', items: seq(indexColumns.map(createColumnName)) }, unique, name: createIndexName(indexName), source: span });
        }
      }
      if (method === 'foreignId' && args.length > 0) {
        const columnName = args[0];
        let constrained = false;
        let onDelete: ForeignKeyAction = { kind: 'no_action' };
        for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) {
          if (tokens[a].value === 'constrained') constrained = true;
          if (tokens[a].value === 'cascadeOnDelete') onDelete = { kind: 'cascade' };
          if (tokens[a].value === 'nullOnDelete') onDelete = { kind: 'set_null' };
          if (tokens[a].value === 'restrictOnDelete') onDelete = { kind: 'restrict' };
        }
        let chainedUnique = false;
        let chainedIndex = false;
        for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) {
          if (tokens[a].value === 'unique') chainedUnique = true;
          if (tokens[a].value === 'index') chainedIndex = true;
        }
        if (chainedUnique || chainedIndex) {
          const suffix = chainedUnique ? 'unique' : 'index';
          indexItems.push({ kind: 'index', columns: { kind: 'column_names', items: seq([createColumnName(columnName)]) }, unique: truth(chainedUnique), name: createIndexName(`${table.value}_${columnName}_${suffix}`), source: span });
        }
        if (constrained) {
          const constrainedArgument = (() => {
            for (let a = m + 3; a + 2 < Math.min(tokens.length, m + 40) && tokens[a].value !== ';'; a += 1) {
              if (tokens[a].value === 'constrained' && tokens[a + 2]?.type === 'STRING') return tokens[a + 2].value;
            }
            return undefined;
          })();
          const base = columnName.endsWith('_id') ? columnName.slice(0, -3) : columnName;
          const targetTable = constrainedArgument ?? `${base}s`;
          const referencesModel: DomainTypeName = { kind: 'domain_type_name', value: { kind: 'string_value', value: targetTable } };
          foreignKeyItems.push({ kind: 'foreign_key', column: createColumnName(columnName), referencesModel, referencesColumn: createColumnName('id'), onDelete, onUpdate: { kind: 'no_action' }, source: span });
        }
      }
      if (method !== 'unique' && method !== 'index' && method !== 'foreignId' && method !== 'foreign' && method !== 'timestamps' && method !== 'softDeletes') {
        const columnName = args[0];
        if (columnName) {
          let chainedUnique = false;
          let chainedIndex = false;
          for (let a = m + 3; a < Math.min(tokens.length, m + 30) && tokens[a].value !== ';'; a += 1) {
            if (tokens[a].value === 'unique') chainedUnique = true;
            if (tokens[a].value === 'index') chainedIndex = true;
          }
          if (chainedUnique || chainedIndex) {
            const unique = truth(chainedUnique);
            const suffix = chainedUnique ? 'unique' : 'index';
            indexItems.push({ kind: 'index', columns: { kind: 'column_names', items: seq([createColumnName(columnName)]) }, unique, name: createIndexName(`${table.value}_${columnName}_${suffix}`), source: span });
          }
        }
      }

      if (method === 'foreign' && args.length > 0) {
        let referencesColumn = 'id';
        let referencesTable = '';
        let onDelete: ForeignKeyAction = { kind: 'no_action' };
        for (let a = m + 3; a + 2 < Math.min(tokens.length, m + 40) && tokens[a].value !== ';'; a += 1) {
          if (tokens[a].value === 'references' && tokens[a + 2]?.type === 'STRING') referencesColumn = tokens[a + 2].value;
          if (tokens[a].value === 'on' && tokens[a + 2]?.type === 'STRING') referencesTable = tokens[a + 2].value;
          if (tokens[a].value === 'cascadeOnDelete') onDelete = { kind: 'cascade' };
          if (tokens[a].value === 'nullOnDelete') onDelete = { kind: 'set_null' };
          if (tokens[a].value === 'restrictOnDelete') onDelete = { kind: 'restrict' };
        }
        if (referencesTable.length > 0) foreignKeyItems.push({ kind: 'foreign_key', column: createColumnName(args[0]), referencesModel: { kind: 'domain_type_name', value: { kind: 'string_value', value: referencesTable } }, referencesColumn: createColumnName(referencesColumn), onDelete, onUpdate: { kind: 'no_action' }, source: span });
      }
    }

    const cols: Columns = { kind: 'columns', items: seq(columns) };
    operations.push({ kind: 'create_table', table: tableName, columns: cols, indexes: { kind: 'indexes', items: seq(indexItems) }, foreignKeys: { kind: 'foreign_keys', items: seq(foreignKeyItems) } });
  }
  return Object.freeze(operations);
}
export async function scanMigrationAsts(sourceProject: SourceProjectIdentity): Promise<readonly MigrationAst[]> {
    const sourceRoot = sourceProject.root.value.value;
  const directory = path.join(sourceRoot, 'database', 'migrations');
  const files = await collectPhpFiles(directory);
  const asts: MigrationAst[] = [];
  for (const file of files) {
    const tokens = LaravelSourceLexer.tokenize(await readSourceText(file));
    const operations = createOperations(tokens, file);
    if (operations.length === 0) continue;
    const span = source(file);
    asts.push({ kind: 'migration_ast', definition: { kind: 'migration_definition', file: { kind: 'source_file', value: { kind: 'string_value', value: file } } as SourceFile, operations: { kind: 'migration_operations', items: seq(operations) }, source: span }, source: span });
  }
  return Object.freeze(asts);
}
