import type { Assignment } from './assignment';
import type { Expression } from './expression';
import type { ActionName, ControllerName, DomainTypeName, ExceptionName, RequestName, VariableName } from './names';
import type { ResponseContract } from './response';
import type { SourceSpan } from './provenance';
import type { CatchHandlers, ControllerStatements } from './collections';
import type { HttpStatusCode } from './valueObjects';
export type RequestBinding = { readonly kind: 'bound_request'; readonly name: RequestName } | { readonly kind: 'no_request' };
export type CatchHandler = { readonly kind: 'catch_handler'; readonly variable: VariableName; readonly exception: ExceptionName; readonly body: ControllerStatements; readonly source: SourceSpan };
export type ConditionalBranches = { readonly kind: 'then_only'; readonly whenTrue: ControllerStatements } | { readonly kind: 'then_else'; readonly whenTrue: ControllerStatements; readonly whenFalse: ControllerStatements };
export type ControllerStatement = { readonly kind: 'assignment'; readonly value: Assignment; readonly source: SourceSpan } | { readonly kind: 'expression'; readonly value: Expression; readonly source: SourceSpan } | { readonly kind: 'return'; readonly expression: Expression; readonly response: ResponseContract; readonly source: SourceSpan } | { readonly kind: 'conditional'; readonly condition: Expression; readonly branches: ConditionalBranches; readonly source: SourceSpan } | { readonly kind: 'for_each'; readonly iterable: Expression; readonly variable: VariableName; readonly body: ControllerStatements; readonly source: SourceSpan } | { readonly kind: 'transaction'; readonly body: ControllerStatements; readonly source: SourceSpan } | { readonly kind: 'try'; readonly body: ControllerStatements; readonly catches: CatchHandlers; readonly source: SourceSpan } | { readonly kind: 'throw'; readonly error: Expression; readonly source: SourceSpan } | { readonly kind: 'abort'; readonly status: HttpStatusCode; readonly message: Expression; readonly source: SourceSpan };
export type ControllerAction = { readonly kind: 'controller_action'; readonly controller: ControllerName; readonly action: ActionName; readonly domain: DomainTypeName; readonly request: RequestBinding; readonly statements: ControllerStatements; readonly response: ResponseContract; readonly source: SourceSpan };
