import type { ColumnName, DomainTypeName, IndexName, TableName } from './names';
import type { Expression } from './expression';
import type { PrimitiveVocabulary, Presence } from './primitiveVocabulary';
import type { NumberValue, StringValues, TruthValue } from './valueObjects';
import type { SourceSpan } from './provenance';
import type { Columns, ForeignKeys, Indexes } from './collections';
export type IntegerWidth = { readonly kind: 'tiny' } | { readonly kind: 'small' } | { readonly kind: 'medium' } | { readonly kind: 'normal' } | { readonly kind: 'big' };
export type DatabaseType = { readonly kind: 'integer'; readonly width: IntegerWidth; readonly signed: TruthValue } | { readonly kind: 'decimal'; readonly precision: NumberValue; readonly scale: NumberValue } | { readonly kind: 'string'; readonly length: NumberValue } | { readonly kind: 'text' } | { readonly kind: 'boolean' } | { readonly kind: 'date_time' } | { readonly kind: 'json' } | { readonly kind: 'enum'; readonly values: StringValues };
export type ColumnDefault = { readonly kind: 'none' } | { readonly kind: 'literal'; readonly expression: Expression } | { readonly kind: 'expression'; readonly expression: Expression };
export type ColumnDefinition = { readonly kind: 'column'; readonly name: ColumnName; readonly databaseType: DatabaseType; readonly semanticType: PrimitiveVocabulary; readonly presence: Presence; readonly nullability: import('./primitiveVocabulary').Nullability; readonly default: ColumnDefault; readonly primary: TruthValue; readonly autoGenerated: TruthValue; readonly source: SourceSpan };
export type ForeignKeyAction = { readonly kind: 'no_action' } | { readonly kind: 'cascade' } | { readonly kind: 'restrict' } | { readonly kind: 'set_null' };
export type ForeignKey = { readonly kind: 'foreign_key'; readonly column: ColumnName; readonly referencesModel: DomainTypeName; readonly referencesColumn: ColumnName; readonly onDelete: ForeignKeyAction; readonly onUpdate: ForeignKeyAction; readonly source: SourceSpan };
export type IndexDefinition = { readonly kind: 'index'; readonly columns: import('./collections').ColumnNames; readonly unique: TruthValue; readonly name: IndexName; readonly source: SourceSpan };

