import type { ModelSemanticDefinition, ModelSemanticProperty } from '../domain/models';
import type { ClassName, ColumnName, ConstantName, DomainTypeName, MethodName, ModelName, PropertyName, RelationName, SourceFile, TableName } from './names';
import type { Cardinality, SemanticValue } from './primitiveVocabulary';
import type { TruthValue } from './valueObjects';
import type { ResolvedExpression } from './expression';
import type { PropertySurface } from './property';
import type { TypeExpression } from './typeVocabulary';
import type { SourceSpan } from './provenance';
import type { ModelAccessors, ModelCasts, ModelConstants, ModelMethods, ModelRelations, ModelTraits, Properties, PropertyNames, Columns, ForeignKeys } from './collections';
export type ModelInheritance =
  | { readonly kind: 'eloquent_model' }
  | { readonly kind: 'authenticatable' }
  | { readonly kind: 'class'; readonly name: ClassName };
export type ModelIdentity = { readonly kind: 'model_identity'; readonly name: ModelName; readonly shortName: ModelName; readonly table: TableName; readonly inheritance: ModelInheritance };
export type ModelKeyKind = { readonly kind: 'integer' } | { readonly kind: 'big_integer' } | { readonly kind: 'string' } | { readonly kind: 'uuid' } | { readonly kind: 'ulid' };
export type ModelKey = { readonly kind: 'primary_key'; readonly column: ColumnName; readonly type: ModelKeyKind; readonly semanticType: TypeExpression; readonly autoGenerated: TruthValue };
export type ModelBehavior = { readonly kind: 'model_behavior'; readonly incrementing: TruthValue; readonly softDeletes: TruthValue; readonly timestamps: TruthValue };
export type ModelExposure = { readonly kind: 'model_exposure'; readonly fillable: PropertyNames; readonly guarded: PropertyNames; readonly hidden: PropertyNames; readonly appends: PropertyNames };
export type ModelSourceCapabilities = { readonly kind: 'model_source_capabilities'; readonly traits: ModelTraits };
export type RelationKind = { readonly kind: 'has_one' } | { readonly kind: 'has_many' } | { readonly kind: 'belongs_to' } | { readonly kind: 'belongs_to_many' } | { readonly kind: 'has_one_through' } | { readonly kind: 'has_many_through' } | { readonly kind: 'morph_to' } | { readonly kind: 'morph_one' } | { readonly kind: 'morph_many' } | { readonly kind: 'morph_to_many' } | { readonly kind: 'morphed_by_many' };
export type RelationKeyOrigin = { readonly kind: 'convention' } | { readonly kind: 'explicit' };
export type RelationKey = { readonly kind: 'convention' } | { readonly kind: 'explicit'; readonly foreign: ColumnName; readonly local: ColumnName };
export type ModelRelation = { readonly kind: 'model_relation'; readonly name: RelationName; readonly target: ModelName; readonly relation: RelationKind; readonly cardinality: Cardinality; readonly key: RelationKey; readonly source: SourceSpan };
export type ModelCast = { readonly kind: 'model_cast'; readonly property: PropertyName; readonly target: import('./expression').CastType; readonly source: SourceSpan };
export type ModelSchema = { readonly kind: 'model_schema'; readonly columns: import('./collections').ModelColumnFacts; readonly foreignKeys: ForeignKeys; readonly indexes: import('./collections').Indexes };
export type ModelConstant = { readonly kind: 'model_constant'; readonly name: ConstantName; readonly value: import('./expression').Expression; readonly source: SourceSpan };
export type ModelMethod = { readonly kind: 'model_method'; readonly name: MethodName; readonly result: TypeExpression; readonly body: SourceSpan; readonly source: SourceSpan };
export type ModelAccessor = { readonly kind: 'model_accessor'; readonly name: PropertyName; readonly expression: ResolvedExpression; readonly source: SourceSpan };
export type ModelDefinition = { readonly kind: 'model'; readonly identity: ModelIdentity; readonly source: SourceSpan; readonly file: SourceFile; readonly key: ModelKey; readonly behavior: ModelBehavior; readonly exposure: ModelExposure; readonly capabilities: ModelSourceCapabilities; readonly surface: PropertySurface; readonly semanticProperties: readonly ModelSemanticProperty[]; readonly schema: ModelSchema; readonly properties: Properties; readonly relations: ModelRelations; readonly casts: ModelCasts; readonly computed: ModelAccessors; readonly constants: ModelConstants; readonly methods: ModelMethods; readonly semantic: ModelSemanticDefinition };
