// Generated by TypeScriptGenerator
// File: types/api-read.ts

export interface RegisterResponseTransformed {
    success: boolean;
    message: string;
    data: string;
}

export interface OrderDetailResourceTransformed {
    id: string;
    produkItemId: string;
    produk: string;
    qty: string;
    harga: string;
    subtotal: string;
}

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
    id: string;
    status: string;
    totalHarga: string;
    invoiceNumber: string;
    paymentStatus: string;
    financialStatus: string;
    fulfillmentStatus: string;
    subtotalMinor: string;
    discountMinor: string;
    shippingMinor: string;
    taxMinor: string;
    totalHargaMinor: string;
    items: string;
    promotion: string;
    shipping: string;
    createdAt: string;
}

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
    id: string;
    orderId: string;
    invoiceNumber: string;
    metode: string;
    detail: string;
    status: string;
    paidAt: string;
    provider: string;
    providerTxnId: string;
    gatewayStatus: string;
    amountMinor: string;
    refundAmountMinor: string;
    items: string;
    promotion: string;
    gateway: string;
    totalHarga: string;
}

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
    id: string;
    nama: string;
    deskripsi: string;
    image: string;
    imageUrl: string;
    categoryId: string;
    categoryName: string;
    harga: string;
    stok: string;
    rating: string;
    reviewCount: string;
}

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]
