// Auto-generated by routesync. Do not edit manually.

/* =========================
   APPLICATION CONSTANTS
========================= */

export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/api'

export const API_ENDPOINTS = {
  API_ADMIN_PRODUK: '/api/admin/produk',
  API_BUY_NOW: '/api/buy-now',
  API_CART: '/api/cart',
  API_CART_ITEMS: '/api/cart/items',
  API_CART_ITEM: (produkItemId: number) => `/api/cart/items/${produkItemId}`,
  API_CART_PROMO: '/api/cart/promo',
  API_CATEGORIES: '/api/categories',
  API_CHECKOUT: '/api/checkout',
  API_FORGOT_PASSWORD: '/api/forgot-password',
  API_KERANJANG: '/api/keranjang',
  API_LOGIN: '/api/login',
  API_LOGOUT: '/api/logout',
  API_OAUTH_PROVIDER_CALLBACK: (provider: string) => `/api/oauth/${provider}/callback`,
  API_OAUTH_PROVIDER_REDIRECT: (provider: string) => `/api/oauth/${provider}/redirect`,
  API_ORDERS: '/api/orders',
  API_ORDERS_DETAIL: (id: number) => `/api/orders/${id}`,
  API_ORDERS_DETAIL_INVOICE: (id: number) => `/api/orders/${id}/invoice`,
  API_PAYMENT_ORDER_ID: (orderId: number) => `/api/payment/${orderId}`,
  API_PAYMENT_WEBHOOK: '/api/payment/webhook',
  API_PRODUK: '/api/produk',
  API_PRODUK_DETAIL: (id: number) => `/api/produk/${id}`,
  API_PRODUK_DETAIL_REVIEWS: (id: number) => `/api/produk/${id}/reviews`,
  API_PROFILE: '/api/profile',
  API_REGISTER: '/api/register',
  API_RESET_PASSWORD: '/api/reset-password',
  API_SOCIAL_LOGIN: '/api/social/login',
  API_WISHLIST: '/api/wishlist',
  API_WISHLIST_PRODUK_ITEM_ID: (produkItemId: number) => `/api/wishlist/${produkItemId}`,
} as const

export const ROUTES = {
  HOME: '/',
  API_OAUTH_PROVIDER_REDIRECT: (provider: string) => `/api/oauth/${provider}/redirect`,
  API_OAUTH_PROVIDER_CALLBACK: (provider: string) => `/api/oauth/${provider}/callback`,
  API_CATEGORIES: '/api/categories',
  API_PRODUK: '/api/produk',
  API_PRODUK_DETAIL: (id: number) => `/api/produk/${id}`,
  API_PRODUK_DETAIL_REVIEWS: (id: number) => `/api/produk/${id}/reviews`,
  API_PROFILE: '/api/profile',
  API_ORDERS: '/api/orders',
  API_ORDERS_DETAIL: (id: number) => `/api/orders/${id}`,
  API_KERANJANG: '/api/keranjang',
  API_WISHLIST: '/api/wishlist',
  API_ORDERS_DETAIL_INVOICE: (id: number) => `/api/orders/${id}/invoice`,
} as const

export const Enums = {
  Order: {
    Status: {
      PENDING: 'pending',
      PAID: 'paid',
      CANCELED: 'canceled',
    } as const,
  },
  OrderFinancial: {
    FinancialStatus: {
      PENDING: 'pending',
      PAID: 'paid',
      PARTIALLY_REFUNDED: 'partially_refunded',
      REFUNDED: 'refunded',
      FAILED: 'failed',
      CANCELLED: 'cancelled',
    } as const,
  },
  OrderFulfillment: {
    FulfillmentStatus: {
      UNFULFILLED: 'unfulfilled',
      PROCESSING: 'processing',
      SHIPPED: 'shipped',
      COMPLETED: 'completed',
      CANCELLED: 'cancelled',
      RETURNED: 'returned',
    } as const,
  },
  Payment: {
    Status: {
      PENDING: 'pending',
      SUCCESS: 'success',
      FAILED: 'failed',
    } as const,
  },
  PromoCode: {
    DiscountType: {
      FIXED_MINOR: 'fixed_minor',
      PERCENT: 'percent',
    } as const,
  },
  User: {
    Role: {
      ADMIN: 'admin',
      USER: 'user',
    } as const,
  },
  Social: {
    Provider: {
      GOOGLE: 'google',
      FACEBOOK: 'facebook',
      APPLE: 'apple',
    } as const,
  },
} as const

export type OrderStatus = (typeof Enums.Order.Status)[keyof typeof Enums.Order.Status]
export type OrderFinancialFinancialStatus = (typeof Enums.OrderFinancial.FinancialStatus)[keyof typeof Enums.OrderFinancial.FinancialStatus]
export type OrderFulfillmentFulfillmentStatus = (typeof Enums.OrderFulfillment.FulfillmentStatus)[keyof typeof Enums.OrderFulfillment.FulfillmentStatus]
export type PaymentStatus = (typeof Enums.Payment.Status)[keyof typeof Enums.Payment.Status]
export type PromoCodeDiscountType = (typeof Enums.PromoCode.DiscountType)[keyof typeof Enums.PromoCode.DiscountType]
export type UserRole = (typeof Enums.User.Role)[keyof typeof Enums.User.Role]
export type SocialProvider = (typeof Enums.Social.Provider)[keyof typeof Enums.Social.Provider]
