// Auto-generated by routesync. Do not edit manually.

import { defineHooks, useAggregateCollectionIntent } from 'routesync/react'
import { api } from './api'
import { QueryKey } from './query-key'
import { runtimeManifest } from './routesync.runtime'
import type {
  AdminForm,
  CategoriesTransformed,
  ForgotPasswordForm,
  KeranjangTransformed,
  LaravelUnauthorizedError,
  LaravelValidationError,
  OauthForm,
  OauthRedirectTransformed,
  OrderResourceTransformed,
  ProdukItemResourceTransformed,
  ProfileTransformed,
  ResetPasswordForm,
  SocialForm,
  WishlistForm,
} from './types/index'
import type {
  CartPost2Payload,
} from './contract/api-schema'

export const typeOf = <T>() => ({} as T)

const baseHooks = defineHooks({
  register: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.register,
    actionKeys: {
      create: QueryKey.register.create,
    },
    endpoint: api.register,

    cache: {
      create: {
        invalidate: [
          QueryKey.register.all,
        ],
      },
    },
  },
  login: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.login,
    actionKeys: {
      create: QueryKey.login.create,
    },
    endpoint: api.login,

    cache: {
      create: {
        invalidate: [
          QueryKey.login.all,
        ],
      },
    },
  },
  oauth: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<OauthRedirectTransformed>(),
      create: typeOf<OauthForm['Get']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.oauth,
    actionKeys: {
      get: QueryKey.oauth.get,
      get2: QueryKey.oauth.get2,
      post: QueryKey.oauth.post,
    },
    endpoint: api.oauth,

    cache: {
      post: {
        invalidate: [
          QueryKey.oauth.get,
          QueryKey.oauth.get2,
          QueryKey.oauth.all,
        ],
      },
    },
  },
  social: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<SocialForm['Create']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.social,
    actionKeys: {
      post: QueryKey.social.post,
    },
    endpoint: api.social,

    cache: {
      post: {
        invalidate: [
          QueryKey.social.all,
        ],
      },
    },
  },
  forgotPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ForgotPasswordForm['Create']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.forgotPassword,
    actionKeys: {
      create: QueryKey.forgotPassword.create,
    },
    endpoint: api.forgotPassword,

    cache: {
      create: {
        invalidate: [
          QueryKey.forgotPassword.all,
        ],
      },
    },
  },
  resetPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ResetPasswordForm['Create']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelValidationError>(),
    },

    queryKey: QueryKey.resetPassword,
    actionKeys: {
      create: QueryKey.resetPassword.create,
    },
    endpoint: api.resetPassword,

    cache: {
      create: {
        invalidate: [
          QueryKey.resetPassword.all,
        ],
      },
    },
  },
  categories: {
    types: {
      list: typeOf<CategoriesTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.categories,
    actionKeys: {
      list: QueryKey.categories.list,
    },
    endpoint: api.categories,
  },
  produk: {
    types: {
      list: typeOf<ProdukItemResourceTransformed>(),
      detail: typeOf<ProdukItemResourceTransformed>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.produk,
    actionKeys: {
      list: QueryKey.produk.list,
      get: QueryKey.produk.get,
      get2: QueryKey.produk.get2,
      post: QueryKey.produk.post,
    },
    endpoint: api.produk,

    cache: {
      list: QueryKey.produk.lists,
      detail: QueryKey.produk.detail,
      post: {
        invalidate: [
          QueryKey.produk.lists,
          QueryKey.produk.get2,
          QueryKey.produk.all,
        ],
      },
    },
  },
  payment: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.payment,
    actionKeys: {
      post: QueryKey.payment.post,
      post2: QueryKey.payment.post2,
    },
    endpoint: api.payment,

    cache: {
      post: {
        invalidate: [
          QueryKey.payment.all,
        ],
      },
      post2: {
        invalidate: [
          QueryKey.payment.all,
        ],
      },
    },
  },
  profile: {
    types: {
      list: typeOf<ProfileTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.profile,
    actionKeys: {
      list: QueryKey.profile.list,
      put: QueryKey.profile.put,
      patch: QueryKey.profile.patch,
    },
    endpoint: api.profile,

    cache: {
      put: {
        invalidate: [
          QueryKey.profile.list,
          QueryKey.profile.all,
        ],
      },
      patch: {
        invalidate: [
          QueryKey.profile.list,
          QueryKey.profile.all,
        ],
      },
    },
  },
  orders: {
    types: {
      list: typeOf<OrderResourceTransformed>(),
      detail: typeOf<OrderResourceTransformed>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError>(),
    },

    queryKey: QueryKey.orders,
    actionKeys: {
      list: QueryKey.orders.list,
      get: QueryKey.orders.get,
      get2: QueryKey.orders.get2,
    },
    endpoint: api.orders,

    cache: {
      list: QueryKey.orders.lists,
      detail: QueryKey.orders.detail,
    },
  },
  cart: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<CartPost2Payload>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.cart,
    actionKeys: {
      post: QueryKey.cart.post,
      patch: QueryKey.cart.patch,
      delete: QueryKey.cart.delete,
      delete2: QueryKey.cart.delete2,
      post2: QueryKey.cart.post2,
      delete3: QueryKey.cart.delete3,
    },
    endpoint: api.cart,

    cache: {
      post: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      patch: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete2: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      post2: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete3: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
    },
  },
  checkout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.checkout,
    actionKeys: {
      create: QueryKey.checkout.create,
    },
    endpoint: api.checkout,

    cache: {
      create: {
        invalidate: [
          QueryKey.checkout.all,
        ],
      },
    },
  },
  buyNow: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.buyNow,
    actionKeys: {
      create: QueryKey.buyNow.create,
    },
    endpoint: api.buyNow,

    cache: {
      create: {
        invalidate: [
          QueryKey.buyNow.all,
        ],
      },
    },
  },
  keranjang: {
    types: {
      list: typeOf<KeranjangTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError>(),
    },

    queryKey: QueryKey.keranjang,
    actionKeys: {
      list: QueryKey.keranjang.list,
    },
    endpoint: api.keranjang,
  },
  wishlist: {
    types: {
      list: typeOf<ProdukItemResourceTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<WishlistForm['Create']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.wishlist,
    actionKeys: {
      list: QueryKey.wishlist.list,
      create: QueryKey.wishlist.create,
      remove: QueryKey.wishlist.remove,
    },
    endpoint: api.wishlist,

    cache: {
      create: {
        invalidate: [
          QueryKey.wishlist.list,
          QueryKey.wishlist.all,
        ],
      },
      remove: {
        invalidate: [
          QueryKey.wishlist.list,
          QueryKey.wishlist.all,
        ],
      },
    },
  },
  logout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.logout,
    actionKeys: {
      create: QueryKey.logout.create,
    },
    endpoint: api.logout,

    cache: {
      create: {
        invalidate: [
          QueryKey.logout.all,
          QueryKey.profile.all,
          QueryKey.orders.all,
          QueryKey.cart.all,
          QueryKey.checkout.all,
          QueryKey.buyNow.all,
          QueryKey.keranjang.all,
          QueryKey.wishlist.all,
          QueryKey.produk.all,
          QueryKey.payment.all,
          QueryKey.admin.all,
        ],
      },
    },
  },
  admin: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<AdminForm['Create']>(),
      update: typeOf<never>(),
      error: typeOf<LaravelUnauthorizedError | LaravelValidationError>(),
    },

    queryKey: QueryKey.admin,
    actionKeys: {
      post: QueryKey.admin.post,
    },
    endpoint: api.admin,

    cache: {
      post: {
        invalidate: [
          QueryKey.admin.all,
        ],
      },
    },
  },
}, runtimeManifest)

export const hooks = baseHooks

/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:26 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:26 (AuthController@register) | Request: app/Http/Requests/RegisterRequest.php:1 (RegisterRequest)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L26
 */
export const useRegister = hooks.register
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:43 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:43 (AuthController@login) | Request: app/Http/Requests/LoginRequest.php:1 (LoginRequest)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L43
 */
export const useLogin = hooks.login
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:77 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:77 (AuthController@oauthRedirect)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L77
 */
export const useOauth = hooks.oauth
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:155 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:155 (AuthController@socialLogin)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L155
 */
export const useSocial = hooks.social
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:220 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:220 (AuthController@forgotPassword)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L220
 */
export const useForgotPassword = hooks.forgotPassword
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:248 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:248 (AuthController@resetPassword)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L248
 */
export const useResetPassword = hooks.resetPassword
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/CategoryController.php:9 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/CategoryController.php:9 (CategoryController@index)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/CategoryController.php#L9
 */
export const useCategories = hooks.categories
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php:68 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php:68 (ProdukController@show) | Response: app/Http/Resources/ProdukItemResource.php:1 (ProdukItemResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php#L68
 */
export const useProduk = hooks.produk
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/PaymentController.php:51 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/PaymentController.php:51 (PaymentController@webhook)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/PaymentController.php#L51
 */
export const usePayment = hooks.payment
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProfileController.php:10 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProfileController.php:10 (ProfileController@show)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProfileController.php#L10
 */
export const useProfile = hooks.profile
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:30 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:30 (OrderController@show) | Response: app/Http/Resources/OrderResource.php:1 (OrderResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php#L30
 */
export const useOrders = hooks.orders
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:127 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:127 (OrderController@addItem) | Request: app/Http/Requests/StoreCartItemRequest.php:1 (StoreCartItemRequest) | Response: app/Http/Resources/OrderResource.php:1 (OrderResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php#L127
 */
export const useCart = hooks.cart
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:43 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:43 (OrderController@store) | Request: app/Http/Requests/StoreOrderRequest.php:1 (StoreOrderRequest) | Response: app/Http/Resources/OrderResource.php:1 (OrderResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php#L43
 */
export const useCheckout = hooks.checkout
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:65 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:65 (OrderController@buyNow) | Request: app/Http/Requests/StoreBuyNowRequest.php:1 (StoreBuyNowRequest) | Response: app/Http/Resources/OrderResource.php:1 (OrderResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php#L65
 */
export const useBuyNow = hooks.buyNow
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:114 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php:114 (OrderController@keranjang)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/OrderController.php#L114
 */
export const useKeranjang = hooks.keranjang
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/WishlistController.php:14 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/WishlistController.php:14 (WishlistController@index) | Response: app/Http/Resources/ProdukItemResource.php:1 (ProdukItemResource)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/WishlistController.php#L14
 */
export const useWishlist = hooks.wishlist
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:70 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php:70 (AuthController@logout)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/Auth/AuthController.php#L70
 */
export const useLogout = hooks.logout
/**
 * @provenance Route: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php:79 | Controller: /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php:79 (ProdukController@store)
 * @see /home/annas-zen/Documents/laragon-docker/www/toko-online/app/Http/Controllers/ProdukController.php#L79
 */
export const useAdmin = hooks.admin

export * from './query-key'
