/**
 * Runtime Helpers for Resource-Grouped API
 * Generated by RuntimeEmitter - Contract IR Architecture
 * 
 * Provides helper functions for the new api.ts structure:
 * - defineApi(): API configuration wrapper
 * - endpoint(): Endpoint configuration wrapper  
 * - typeOf<T>(): Type-safe phantom type carrier
 */

/* =========================================================
 * API CONFIGURATION HELPERS
 * ========================================================= */

/**
 * defineApi - Wrapper for API configuration
 * 
 * Provides type-safe API definition with resource grouping.
 * Returns the same object but with proper typing.
 */
export function defineApi<T>(config: T): T {
  return config
}

/**
 * endpoint - Wrapper for endpoint configuration
 * 
 * Provides type-safe endpoint definition with types/contract/mapper blocks.
 * Returns the same object but with proper typing.
 */
export function endpoint<T>(config: T): T {
  return config
}

/* =========================================================
 * TYPE CARRIERS (§27.1)
 * ========================================================= */

/**
 * typeOf<T>() - Type-safe phantom type carrier
 * 
 * Creates a type carrier without runtime cost for explicit type declarations.
 * Used in types block to make TypeScript types available at runtime structure.
 * 
 * Implementation: Returns undefined cast to T, gets stripped in production.
 * Usage: types: { show: typeOf<UserShow>() }
 */
export const typeOf = <T>(): T => undefined as unknown as T

/* =========================================================
 * TYPE EXTRACTION UTILITIES
 * ========================================================= */

/**
 * Extract types from API endpoint configuration
 */
export type ExtractTypes<T> = T extends { 
  endpoint(config: { types: infer U }): any 
} ? U : never

/**
 * Extract contract from API endpoint configuration  
 */
export type ExtractContract<T> = T extends { 
  endpoint(config: { contract: infer U }): any 
} ? U : never

/**
 * Extract mapper from API endpoint configuration
 */
export type ExtractMapper<T> = T extends { 
  endpoint(config: { mapper: infer U }): any 
} ? U : never

/* =========================================================
 * ACTION TYPE DEFINITIONS
 * ========================================================= */

/**
 * Standard CRUD actions supported by the API
 * 
 * Consistent vocabulary used across types/contract/mapper blocks (§27.6)
 */
export type ApiAction = 'index' | 'show' | 'create' | 'update' | 'destroy'

/**
 * HTTP methods mapped to semantic actions
 * 
 * Solves PUT/PATCH duplication by unifying to 'update' (§24.3)
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export const ACTION_TO_METHOD: Record<ApiAction, HttpMethod[]> = {
  index: ['GET'],
  show: ['GET'], 
  create: ['POST'],
  update: ['PUT', 'PATCH'], // Unified mapping
  destroy: ['DELETE']
}

/* =========================================================
 * ENDPOINT CONFIGURATION TYPES
 * ========================================================= */

/**
 * Configuration for a resource endpoint with types/contract/mapper
 */
export interface EndpointConfig<
  TTypes extends Record<string, any> = {},
  TContract extends Record<string, any> = {},
  TMapper extends Record<string, any> = {}
> {
  types: TTypes
  contract: TContract  
  mapper: TMapper
}

/**
 * Action-specific configuration within an endpoint
 */
export interface ActionConfig {
  body?: (...args: any[]) => any
  response: (...args: any[]) => any
}

/* =========================================================
 * USAGE EXAMPLES (for documentation)
 * ========================================================= */

/*
Example usage of the new API structure:

```typescript
import { defineApi, endpoint, typeOf } from './runtime'

export const api = defineApi({
  users: {
    endpoint({
      types: {
        index: typeOf<UserIndex>(),
        show: typeOf<UserShow>(),
        createForm: typeOf<UserForm["Create"]>(),
        createPayload: typeOf<UserApiCreate>(),
        response: typeOf<UserApiResponse>(),
      },
      contract: {
        index: {
          response: validateUserListResponse,
        },
        show: {
          response: validateUserItemResponse, 
        },
        create: {
          body: validateUserCreatePayload,
          response: validateUserItemResponse,
        }
      },
      mapper: {
        index: {
          response: toUserReadList,
        },
        show: {
          response: toUserRead,
        },
        create: {
          body: toApiUserCreate,
          response: toUserRead,
        }
      }
    })
  }
})

// Usage:
const users = await api.users.contract.index.response(data)
const user = await api.users.mapper.show.response(rawUser)  
const form: UserForm["Create"] = api.users.types.createForm
```
*/

export default {
  defineApi,
  endpoint,
  typeOf,
  ACTION_TO_METHOD
}
