/**
 * RouteSync Domain Types & Contracts.
 * Conforms to Rule 14: Zero wildcard re-exports (0 `export * from`).
 */

export {
    type DomainOperationEntry,
    type DomainConfigEntry,
    type DomainIntentConfig,
    type GroupAliasEntry,
    type DomainDefinitionEntry,
    type FrontendConfig,
    type PagePropEntry,
    type PageMetaEntry,
    type PageConfig,
    type ResourceRouteGroup,
    type RouteManifest,
    type ParsedChannel,
    BroadcastChannelKind,
    type BroadcastChannelDescriptor,
    type PublicBroadcastChannelDescriptor,
    type PrivateBroadcastChannelDescriptor,
    type PresenceBroadcastChannelDescriptor,
    type BroadcastChannelSpecification,
    type BroadcastChannelRegistry,
    BROADCAST_CHANNEL_REGISTRY,
    type BroadcastChannelVisitor,
    matchBroadcastChannel,
    type EndpointRequestContract,
    type ItemEndpointRequestContract,
    type ItemEndpointContract,
    type EndpointSuccessResponseContract,
    type EndpointErrorResponseContract,
    type EndpointResponseContract,
    type EndpointContract,
    ScannedEndpointContract,
    createEndpointContract,
    type EndpointResponseVisitor,
    matchEndpointResponse,
    getRouteContract,
    getManifestContractMap,
    DatabaseColumnKind,
    type SqlTypeFamily,
    type DatabaseColumnKindSpecification,
    type DatabaseColumnKindRegistry,
    DATABASE_COLUMN_KIND_REGISTRY,
    type DatabaseColumnKindVisitor,
    matchDatabaseColumnKind,
    DatabaseColumnTypeMapper,
    type ParsedColumn,
    EloquentCastKind,
    type EloquentCastKindSpecification,
    type EloquentCastKindRegistry,
    ELOQUENT_CAST_REGISTRY,
    type EloquentCastKindVisitor,
    matchEloquentCastKind,
    EloquentCastMapper,
    type ParsedCast,
    type ParsedAccessor,
    EloquentRelationType,
    type EloquentRelationCardinality,
    type EloquentRelationDescriptor,
    type EloquentRelationRegistry,
    ELOQUENT_RELATION_REGISTRY,
    EloquentRelationClassifier,
    type ParsedRelation,
    type SingleRelationDescriptor,
    type CollectionRelationDescriptor,
    type RelationCardinalityDescriptor,
    type RelationCardinalityVisitor,
    matchRelationCardinality,
    matchRelation,
    type EloquentRelationTypeVisitor,
    matchRelationType,
    ModelKeyType,
    type ModelKeyTypeSpecification,
    type ModelKeyTypeRegistry,
    MODEL_KEY_TYPE_REGISTRY,
    type ModelKeyTypeVisitor,
    matchModelKeyType,
    ModelKeyTypeMapper,
    type ParsedModel,
    ResourceFieldDescriptor,
    type ResourceFieldSemantic,
    ResourceExpressionKind,
    type ResourceFieldExpression,
    type AnyResourceFieldExpression,
    type ResourceExpressionCategory,
    type ResourceExpressionSpecification,
    type ResourceExpressionRegistry,
    RESOURCE_EXPRESSION_REGISTRY,
    type ResourceFieldExpressionVisitor,
    matchResourceFieldExpression,
    matchResourceExpression,
    ResourceFieldExpressionFactory,
    type ResourceAssignment,
    type ParsedResource,
    type ResourceFieldKind,
    CrudRole,
    PageEndpointKind,
    type PageEndpointKindSpecification,
    type PageEndpointKindRegistry,
    PAGE_ENDPOINT_REGISTRY,
    type PageEndpointDescriptor,
    type PageEndpointVisitor,
    matchPageEndpoint,
    RouteHookKind,
    type BaseRouteHookDescriptor,
    type QueryHookDescriptor,
    type MutationHookDescriptor,
    type InfiniteQueryHookDescriptor,
    type AnyRouteHookDescriptor,
    type RouteHookDescriptor,
    type HookKindSpecification,
    type HookKindRegistry,
    HOOK_KIND_REGISTRY,
    type RouteHookKindVisitor,
    matchRouteHookKind,
    matchHookKind,
    ScannedRouteHookDescriptor,
    type BaseCrudRoleDescriptor,
    type IndexCrudRoleDescriptor,
    type ShowCrudRoleDescriptor,
    type CreateCrudRoleDescriptor,
    type UpdateCrudRoleDescriptor,
    type DeleteCrudRoleDescriptor,
    type CustomCrudRoleDescriptor,
    type AnyCrudRoleDescriptor,
    type CrudRoleSpecification,
    type CrudRoleRegistry,
    CRUD_ROLE_REGISTRY,
    type CrudRoleVisitor,
    matchCrudRole,
    ScannedCrudRoleDescriptor,
    SdkResponseKind,
    InvalidationTargetKind,
    type InvalidationTarget,
    type SelfListInvalidationTarget,
    type ParentListInvalidationTarget,
    type ParentDetailInvalidationTarget,
    type AuthResourceInvalidationTarget,
    type AnyInvalidationTarget,
    type InvalidationTargetSpecification,
    type InvalidationTargetRegistry,
    INVALIDATION_TARGET_REGISTRY,
    type InvalidationTargetVisitor,
    matchInvalidationTarget,
    ScannedInvalidationTarget,
    type RouteCacheInvalidationDescriptor,
    ScannedRouteCacheInvalidationDescriptor,
    ScannedRouteInvalidationPayload,
    RoutePayloadMode,
    type BaseRouteExecutionSignature,
    type NoPayloadExecutionSignature,
    type RequiredPayloadExecutionSignature,
    type OptionalPayloadExecutionSignature,
    type AnyRouteExecutionSignature,
    type RouteExecutionSignature,
    type RoutePayloadModeSpecification,
    type RoutePayloadModeRegistry,
    ROUTE_PAYLOAD_MODE_REGISTRY,
    type RouteExecutionSignatureVisitor,
    matchRouteExecutionSignature,
    matchRoutePayloadMode,
    ScannedRouteExecutionSignature,
    RouteParameterLocation,
    RouteParameterType,
    type RouteParameterTypeSpecification,
    type RouteParameterTypeRegistry,
    ROUTE_PARAMETER_TYPE_REGISTRY,
    type RouteParameterTypeVisitor,
    matchRouteParameterType,
    type RouteParameter,
    type RouteParameterBinding,
    type RouteParameterConstraint,
    type PathParameterDescriptor,
    type QueryParameterDescriptor,
    type HeaderParameterDescriptor,
    type AnyRouteParameter,
    type RouteParameterLocationSpecification,
    type RouteParameterLocationRegistry,
    PARAMETER_LOCATION_REGISTRY,
    type RouteParameterVisitor,
    matchRouteParameter,
    DataProvenanceKind,
    type DataProvenanceKindSpecification,
    type DataProvenanceKindRegistry,
    DATA_PROVENANCE_REGISTRY,
    type ProvenanceSourceRef,
    type DataProvenanceVisitor,
    matchDataProvenance,
    type EndpointProvenanceDescriptor,
    ScannedEndpointProvenanceDescriptor,
    ResourceGroupKind,
    type ResourceGroupSpecification,
    type ResourceGroupRegistry,
    RESOURCE_GROUP_REGISTRY,
    type AvailableMutation,
    type AbsentMutation,
    type MutationCapability as MutationCapabilityType,
    MutationCapability,
    type BaseResourceGroupTypeSignature,
    type FullCrudTypeSignature,
    type ReadOnlyCrudTypeSignature,
    type FlexibleCrudTypeSignature,
    type SingletonTypeSignature,
    type CustomTypeSignature,
    type ResourceGroupTypeSignature,
    type ResourceGroupTypeSignatureParams,
    ScannedResourceGroupTypeSignature,
    type ResourceGroupIdentityTrait,
    type ResourceGroupQueryKeysTrait,
    type CrudEndpointsTrait,
    type StrictMutationEndpointsTrait,
    type FlexibleMutationEndpointsTrait,
    type ResourceGroupVisitorCapability,
    type ResourceGroupLoweringOperations,
    type BaseResourceGroupDescriptor,
    type BaseCrudResourceGroupDescriptor,
    type FullCrudResourceGroupDescriptor,
    type ReadOnlyCrudResourceGroupDescriptor,
    type FlexibleCrudResourceGroupDescriptor,
    type CrudResourceGroupDescriptor,
    type SingletonResourceGroupDescriptor,
    type CustomResourceGroupDescriptor,
    type ResourceGroupDescriptor,
    type BaseResourceGroupParams,
    type BaseCrudParams,
    type FullCrudParams,
    type ReadOnlyCrudParams,
    type FlexibleCrudParams,
    type CrudResourceGroupDescriptorParams,
    type SingletonResourceGroupDescriptorParams,
    type CustomResourceGroupDescriptorParams,
    AbstractResourceGroupDescriptor,
    AbstractCrudResourceGroupDescriptor,
    ScannedFullCrudResourceGroupDescriptor,
    ScannedReadOnlyCrudResourceGroupDescriptor,
    ScannedFlexibleCrudResourceGroupDescriptor,
    ScannedCrudResourceGroupDescriptor,
    ScannedSingletonResourceGroupDescriptor,
    ScannedCustomResourceGroupDescriptor,
    type ExhaustiveFineGrainedResourceGroupVisitor,
    type UnifiedCrudResourceGroupVisitor,
    type ResourceGroupVisitor,
    matchFineGrainedResourceGroup,
    matchUnifiedResourceGroup,
    matchResourceGroup,
    type ResourceGroupGraph,
    createResourceGroupGraph,
    ScannedResourceGroupGraph,
    type ClassifiedDomainGraph,
    ResponseShape,
    type ResponseShapeSpecification,
    type ResponseShapeRegistry,
    RESPONSE_SHAPE_REGISTRY,
    type ResponseShapeVisitor,
    matchResponseShape,
    PaginationKind,
    type BasePaginatedEnvelopeDescriptor,
    type LengthAwarePaginatedEnvelopeDescriptor,
    type CursorPaginatedEnvelopeDescriptor,
    type AnyPaginatedEnvelopeDescriptor,
    type PaginatedEnvelopeDescriptor,
    type PaginationKindSpecification,
    type PaginationKindRegistry,
    PAGINATION_KIND_REGISTRY,
    type PaginatedEnvelopeVisitor,
    matchPaginatedEnvelope,
    matchPaginationKind,
    PolymorphicMorphType,
    type BasePolymorphicRelationDescriptor,
    type MorphToRelationDescriptor,
    type MorphOneRelationDescriptor,
    type MorphManyRelationDescriptor,
    type MorphToManyRelationDescriptor,
    type MorphedByManyRelationDescriptor,
    type PolymorphicRelationDescriptor,
    type AnyPolymorphicRelationDescriptor,
    type PolymorphicRelationSpecification,
    type PolymorphicRelationRegistry,
    POLYMORPHIC_RELATION_REGISTRY,
    type PolymorphicRelationVisitor,
    matchPolymorphicRelation,
    matchPolymorphicMorphType,
    type ScannedPaginatedEnvelopeParams,
    ScannedPaginatedEnvelopeDescriptor,
    type ScannedPolymorphicRelationParams,
    ScannedPolymorphicRelationDescriptor,
    type RouteResponseAnalysis,
    ResponseDescriptorBase,
    type ResourceResponseParams,
    ResourceResponseDescriptor,
    type ModelResponseParams,
    ModelResponseDescriptor,
    VoidResponseDescriptor,
    type InlineResponseDescriptorParams,
    InlineResponseDescriptor,
    ResponseKind,
    type ResponseDescriptor,
    type ResponseKindSpecification,
    type ResponseDescriptorRegistry,
    RESPONSE_DESCRIPTOR_REGISTRY,
    type ResponseVisitor,
    matchResponse,
    type SdkResponseResolution,
    type VoidSdkResponseResolution,
    type RawSdkResponseResolution,
    type ValidatedSdkResponseResolution,
    type MappedSdkResponseResolution,
    type ValidatedAndMappedSdkResponseResolution,
    type AnySdkResponseResolution,
    type SdkResponseKindSpecification,
    type SdkResponseKindRegistry,
    SDK_RESPONSE_KIND_REGISTRY,
    type SdkResponseResolutionVisitor,
    matchSdkResponseResolution,
    matchSdkResponse,
    ScannedSdkResponseResolution,
    type ResponseMetadata,
    type RouteParameterSpecification,
    type RouteIdentityContract,
    type RouteBindingContract,
    type RouteCapabilityContract,
    type RouteProvenanceContract,
    type ParsedRoute,
    type GetCollectionRouteDescriptor,
    type GetItemRouteDescriptor,
    type MutationRouteDescriptor,
    type DeletionRouteDescriptor,
    type RouteDescriptor,
    type RouteClassifier,
    CRUD_DISPATCH_REGISTRY,
    classifyRoute,
    type RouteVisitor,
    matchRoute,
    RouteDescriptorKind,
    type RouteKindSpecification,
    type RouteDescriptorRegistry,
    ROUTE_DESCRIPTOR_REGISTRY,
    type RouteCollectionRegistry,
    ScannedRouteRegistry,
    HttpMethod,
    RouteActionKind,
    type HttpMethodSpecification,
    type HttpMethodRegistry,
    HTTP_METHOD_REGISTRY,
    type HttpMethodVisitor,
    matchHttpMethod,
    type RouteActionKindSpecification,
    type RouteActionKindRegistry,
    ROUTE_ACTION_KIND_REGISTRY,
    type RouteActionKindVisitor,
    matchRouteActionKind,
    HttpStatusCode,
    type KnownHttpStatusCode,
    type HttpStatusCodeCategory,
    type HttpStatusCodeSpecification,
    type HttpStatusCodeRegistry,
    HTTP_STATUS_CODE_REGISTRY,
    type HttpStatusCodeVisitor,
    matchHttpStatusCode,
    RequestContentType,
    type BaseRequestContentTypeDescriptor,
    type JsonRequestContentTypeDescriptor,
    type MultipartRequestContentTypeDescriptor,
    type UrlEncodedRequestContentTypeDescriptor,
    type NoneRequestContentTypeDescriptor,
    type RequestContentTypeDescriptor,
    type RequestContentTypeSpecification,
    type RequestContentTypeRegistry,
    REQUEST_CONTENT_TYPE_REGISTRY,
    ScannedRequestContentTypeDescriptor,
    type RequestContentTypeVisitor,
    matchRequestContentType,
    SecuritySchemeKind,
    type RouteSecurityDescriptor,
    type ScannedRouteSecurityParams,
    ScannedRouteSecurityDescriptor,
    RouteSecurityClassifier,
    type SecuritySchemeSpecification,
    type SecuritySchemeRegistry,
    SECURITY_SCHEME_REGISTRY,
    type RouteSecurityVisitor,
    matchRouteSecurity,
    type RateLimitDescriptor,
    RoutePolicyKind,
    type RoutePolicyKindSpecification,
    type RoutePolicyKindRegistry,
    ROUTE_POLICY_REGISTRY,
    type RoutePolicyVisitor,
    matchRoutePolicy,
    type RoutePolicyDescriptor,
    type RouteQueryParameter,
    type LaravelValidationError,
    type LaravelUnauthorizedError,
    type LaravelForbiddenError,
    type LaravelNotFoundError,
    type LaravelServerError,
    HttpErrorKind,
    type HttpErrorKindSpecification,
    type HttpErrorKindRegistry,
    HTTP_ERROR_KIND_REGISTRY,
    type HttpErrorSchemaRegistry,
    HTTP_ERROR_SCHEMA_REGISTRY,
    type HttpErrorVisitor,
    matchHttpError,
    type HttpErrorResponseDescriptor,
    type HttpErrorSchema,
    type HttpErrorSchemaField,
    ValidationRuleKind,
    type BaseValidationRuleNode,
    type RequiredValidationRuleNode,
    type RequiredWithValidationRuleNode,
    type NullableValidationRuleNode,
    type OptionalValidationRuleNode,
    type StringValidationRuleNode,
    type NumberValidationRuleNode,
    type BooleanValidationRuleNode,
    type ArrayValidationRuleNode,
    type EmailValidationRuleNode,
    type UrlValidationRuleNode,
    type UuidValidationRuleNode,
    type DateValidationRuleNode,
    type MinValidationRuleNode,
    type MaxValidationRuleNode,
    type BetweenValidationRuleNode,
    type InValidationRuleNode,
    type ExistsValidationRuleNode,
    type UniqueValidationRuleNode,
    type FileValidationRuleNode,
    type ImageValidationRuleNode,
    type CustomValidationRuleNode,
    type ValidationRuleNode,
    type AnyValidationRuleNode,
    type ValidationRuleCategory,
    type ValidationRuleSpecification,
    type ValidationRuleRegistry,
    VALIDATION_RULE_REGISTRY,
    type ValidationRuleVisitor,
    matchValidationRule,
    matchRule,
    ValidationRuleNodeFactory,
    ValidationRuleParser,
    type ZodNode,
    type ExtractRule,
    type ConstraintHandler,
    type ConstraintRegistry,
    ZOD_CONSTRAINT_REGISTRY,
    ZodSchemaReducer,
    type ValidationFieldLocation,
    type ValidationFieldShape,
    type ValidationFieldProperty,
    type RouteValidationRuleEntry,
    type RouteMessageEntry,
    type RouteAttributeEntry,
    type RouteSchemaPayload,
    type ScalarValidationFieldNode,
    type ArrayValidationFieldNode,
    type ObjectValidationFieldNode,
    type ValidationFieldNode,
    ValidationFieldKind,
    type ValidationFieldSpecification,
    type ValidationFieldRegistry,
    VALIDATION_FIELD_REGISTRY,
    type ValidationFieldVisitor,
    matchValidationField,
    type ValidationFieldFolder,
    foldValidationField,
    RouteHandlerKind,
    type RouteHandlerKindSpecification,
    type RouteHandlerKindRegistry,
    ROUTE_HANDLER_KIND_REGISTRY,
    type BaseRouteHandlerDescriptor,
    type ControllerActionHandlerDescriptor,
    type InvokableControllerHandlerDescriptor,
    type ClosureHandlerDescriptor,
    type RouteHandlerDescriptor,
    type RouteHandlerVisitor,
    matchRouteHandler,
    type FormRequestDescriptor,
    ScannedFormRequestDescriptor,
    type HeaderDeclaration,
    RequestHeaders,
    type RouteParameterKind,
    type RouteParameterDescriptor,
    type RouteParameterEntry,
    RouteParameters,
    type RouteQueryEntry,
    RouteQueryParameters,
    type PayloadPropertyEntry,
    RequestPayload,
    RouteSchemaModel,
    ResponseSchemaModel,
    RouteMapperModel,
    type ModelFieldInfo,
    type ModelFieldEntry,
    ModelFieldMap,
    type ModelRelationInfo,
    type ModelRelationEntry,
    ModelRelationMap,
    type ModelAccessorInfo,
    type ModelAccessorEntry,
    ModelAccessorMap,
    type ModelServiceEntry,
    ModelServiceMap,
    type ModelControllerEntry,
    ModelControllerMap,
    type ModelNodeEntry,
    ModelNodeMap,
    type SemanticModelEntry,
    SemanticModelMap,
    type SemanticRelationEntry,
    SemanticRelationMap,
    type BoundSemanticKind,
    type BoundPrimitiveNode,
    type BoundModelColumnNode,
    type BoundRelationNode,
    type BoundStepEdge,
    type BoundPropertyChainNode,
    type ConditionalWrapperKind,
    type BoundConditionalNode,
    type BoundBinaryNode,
    type BoundTernaryNode,
    type BoundMethodCallNode,
    type BoundUnknownNode,
    type BoundSemanticNode,
    type BoundSemanticVisitor,
    matchBoundSemanticNode,
    BoundSemanticFactory,
    PhpAstKind,
    type PhpAstCategory,
    type PhpAstKindSpecification,
    type PhpAstKindRegistry,
    PHP_AST_KIND_REGISTRY,
    type PhpAstKindVisitor,
    matchPhpAstKind,
    type BasePhpAstNode,
    type PropertyLookupAstNode,
    type NullsafePropertyLookupAstNode,
    type OffsetLookupAstNode,
    type StaticPropertyLookupAstNode,
    type FunctionCallAstNode,
    type MethodCallAstNode,
    type NullsafeMethodCallAstNode,
    type StaticMethodCallAstNode,
    type VariableCallAstNode,
    type NewInstanceAstNode,
    type ClosureAstNode,
    type ArrowFuncAstNode,
    type BinaryAstNode,
    type UnaryAstNode,
    type TypeCastAstNode,
    type TernaryAstNode,
    type ArrayEntryAstNode,
    type ArrayAstNode,
    type LiteralAstNode,
    type StaticConstantAstNode,
    type VariableAstNode,
    type PhpAstNode,
    type PhpAstVisitor,
    matchPhpAstNode,
    type PhpAstFolder,
    foldPhpAstNode,
    matchFieldNode,
    type FieldNodeVisitor
} from "./domain";


