/**
 * Resource-Grouped API Client (Enhanced V2)
 * Generated by SDKEmitter - Contract IR Architecture
 * 
 * ENHANCEMENTS:
 * ✅ Production-ready TypeScript identifiers
 * ✅ Enhanced manifest with 1 resources, 1 models
 * ✅ Proper import generation
 * ✅ Sanitized naming conventions
 * 
 * Structure: api.{resource}.{ types, contract, mapper }
 * Benefits: Type-safe, consistent action naming, no duplication
 * Compliance: Engine.Fix.md §27 specification
 */

// Helper function imports (commented for now, implement as needed)
// import { defineApi, endpoint, typeOf } from 'routesync'
// import { API_URL, API_ENDPOINTS, ROUTES, Enums } from 'routesync'

// Type imports from generated files
import type {
  RegisterForm, RegisterApiCreate, RegisterApiResponse,
  LoginForm, LoginApiCreate, LoginApiResponse,
  OauthShow, OauthForm, OauthApiCreate, OauthApiResponse,
  SocialForm, SocialApiCreate, SocialApiResponse,
  ForgotpasswordForm, ForgotpasswordApiCreate, ForgotpasswordApiResponse,
  ResetpasswordForm, ResetpasswordApiCreate, ResetpasswordApiResponse,
  CategoriesIndex, CategoriesApiResponse,
  ProdukIndex, ProdukShow, ProdukForm, ProdukApiCreate, ProdukApiResponse,
  PaymentForm, PaymentApiCreate, PaymentApiResponse,
  ProfileIndex, ProfileForm, ProfileApiUpdate, ProfileApiResponse,
  OrdersIndex, OrdersShow, OrdersApiResponse,
  CartForm, CartApiCreate, CartApiUpdate, CartApiResponse,
  CheckoutForm, CheckoutApiCreate, CheckoutApiResponse,
  BuynowForm, BuynowApiCreate, BuynowApiResponse,
  KeranjangIndex, KeranjangApiResponse,
  WishlistIndex, WishlistForm, WishlistApiCreate, WishlistApiResponse,
  LogoutForm, LogoutApiCreate, LogoutApiResponse,
  AdminForm, AdminApiCreate, AdminApiResponse,
} from '../types/api-read'

// Validation imports from generated files  
import {
  validateRegisterCreatePayload,
  validateRegisterCreateResponse,
  validateLoginCreatePayload,
  validateLoginCreateResponse,
  validateOauthShowResponse,
  validateOauthCreatePayload,
  validateOauthCreateResponse,
  validateSocialCreatePayload,
  validateSocialCreateResponse,
  validateForgotpasswordCreatePayload,
  validateForgotpasswordCreateResponse,
  validateResetpasswordCreatePayload,
  validateResetpasswordCreateResponse,
  validateCategoriesIndexResponse,
  validateProdukIndexResponse,
  validateProdukShowResponse,
  validateProdukCreatePayload,
  validateProdukCreateResponse,
  validatePaymentCreatePayload,
  validatePaymentCreateResponse,
  validateProfileIndexResponse,
  validateProfileUpdatePayload,
  validateProfileUpdateResponse,
  validateOrdersIndexResponse,
  validateOrdersShowResponse,
  validateCartCreatePayload,
  validateCartCreateResponse,
  validateCartUpdatePayload,
  validateCartUpdateResponse,
  validateCartDestroyResponse,
  validateCheckoutCreatePayload,
  validateCheckoutCreateResponse,
  validateBuynowCreatePayload,
  validateBuynowCreateResponse,
  validateKeranjangIndexResponse,
  validateWishlistIndexResponse,
  validateWishlistCreatePayload,
  validateWishlistCreateResponse,
  validateWishlistDestroyResponse,
  validateLogoutCreatePayload,
  validateLogoutCreateResponse,
  validateAdminCreatePayload,
  validateAdminCreateResponse,
} from '../contract/api-contract'

// Mapper imports from generated files
import {
  toApiRegisterCreate,
  toRegisterRead,
  toApiLoginCreate,
  toLoginRead,
  toOauthRead,
  toApiOauthCreate,
  toApiSocialCreate,
  toSocialRead,
  toApiForgotpasswordCreate,
  toForgotpasswordRead,
  toApiResetpasswordCreate,
  toResetpasswordRead,
  toCategoriesReadList,
  toProdukReadList,
  toProdukRead,
  toApiProdukCreate,
  toApiPaymentCreate,
  toPaymentRead,
  toProfileReadList,
  toApiProfileUpdate,
  toProfileRead,
  toOrdersReadList,
  toOrdersRead,
  toApiCartCreate,
  toCartRead,
  toApiCartUpdate,
  toApiCheckoutCreate,
  toCheckoutRead,
  toApiBuynowCreate,
  toBuynowRead,
  toKeranjangReadList,
  toWishlistReadList,
  toApiWishlistCreate,
  toWishlistRead,
  toApiLogoutCreate,
  toLogoutRead,
  toApiAdminCreate,
  toAdminRead,
} from '../mappers/api-mapper'

export const api = {
  register: {
    types: {
      createForm: {} as RegisterForm["Create"],
      createPayload: {} as RegisterApiCreate,
      response: {} as RegisterApiResponse,
    },
    contract: {
      create: {
        body: validateRegisterCreatePayload,
        response: validateRegisterCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiRegisterCreate,
        response: toRegisterRead,
      },
    }
  },
  login: {
    types: {
      createForm: {} as LoginForm["Create"],
      createPayload: {} as LoginApiCreate,
      response: {} as LoginApiResponse,
    },
    contract: {
      create: {
        body: validateLoginCreatePayload,
        response: validateLoginCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiLoginCreate,
        response: toLoginRead,
      },
    }
  },
  oauth: {
    types: {
      show: {} as OauthShow,
      createForm: {} as OauthForm["Create"],
      createPayload: {} as OauthApiCreate,
      response: {} as OauthApiResponse,
    },
    contract: {
      show: {
        response: validateOauthShowResponse,
      },
      create: {
        body: validateOauthCreatePayload,
        response: validateOauthCreateResponse,
      },
    },
    mapper: {
      show: {
        response: toOauthRead,
      },
      create: {
        body: toApiOauthCreate,
        response: toOauthRead,
      },
    }
  },
  social: {
    types: {
      createForm: {} as SocialForm["Create"],
      createPayload: {} as SocialApiCreate,
      response: {} as SocialApiResponse,
    },
    contract: {
      create: {
        body: validateSocialCreatePayload,
        response: validateSocialCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiSocialCreate,
        response: toSocialRead,
      },
    }
  },
  forgotpassword: {
    types: {
      createForm: {} as ForgotpasswordForm["Create"],
      createPayload: {} as ForgotpasswordApiCreate,
      response: {} as ForgotpasswordApiResponse,
    },
    contract: {
      create: {
        body: validateForgotpasswordCreatePayload,
        response: validateForgotpasswordCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiForgotpasswordCreate,
        response: toForgotpasswordRead,
      },
    }
  },
  resetpassword: {
    types: {
      createForm: {} as ResetpasswordForm["Create"],
      createPayload: {} as ResetpasswordApiCreate,
      response: {} as ResetpasswordApiResponse,
    },
    contract: {
      create: {
        body: validateResetpasswordCreatePayload,
        response: validateResetpasswordCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiResetpasswordCreate,
        response: toResetpasswordRead,
      },
    }
  },
  categories: {
    types: {
      index: {} as CategoriesIndex,
      response: {} as CategoriesApiResponse,
    },
    contract: {
      index: {
        response: validateCategoriesIndexResponse,
      },
    },
    mapper: {
      index: {
        response: toCategoriesReadList,
      },
    }
  },
  produk: {
    types: {
      index: {} as ProdukIndex,
      show: {} as ProdukShow,
      createForm: {} as ProdukForm["Create"],
      createPayload: {} as ProdukApiCreate,
      response: {} as ProdukApiResponse,
    },
    contract: {
      index: {
        response: validateProdukIndexResponse,
      },
      show: {
        response: validateProdukShowResponse,
      },
      create: {
        body: validateProdukCreatePayload,
        response: validateProdukCreateResponse,
      },
    },
    mapper: {
      index: {
        response: toProdukReadList,
      },
      show: {
        response: toProdukRead,
      },
      create: {
        body: toApiProdukCreate,
        response: toProdukRead,
      },
    }
  },
  payment: {
    types: {
      createForm: {} as PaymentForm["Create"],
      createPayload: {} as PaymentApiCreate,
      response: {} as PaymentApiResponse,
    },
    contract: {
      create: {
        body: validatePaymentCreatePayload,
        response: validatePaymentCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiPaymentCreate,
        response: toPaymentRead,
      },
    }
  },
  profile: {
    types: {
      index: {} as ProfileIndex,
      updateForm: {} as ProfileForm["Update"],
      updatePayload: {} as ProfileApiUpdate,
      response: {} as ProfileApiResponse,
    },
    contract: {
      index: {
        response: validateProfileIndexResponse,
      },
      update: {
        body: validateProfileUpdatePayload,
        response: validateProfileUpdateResponse,
      },
    },
    mapper: {
      index: {
        response: toProfileReadList,
      },
      update: {
        body: toApiProfileUpdate,
        response: toProfileRead,
      },
    }
  },
  orders: {
    types: {
      index: {} as OrdersIndex,
      show: {} as OrdersShow,
      response: {} as OrdersApiResponse,
    },
    contract: {
      index: {
        response: validateOrdersIndexResponse,
      },
      show: {
        response: validateOrdersShowResponse,
      },
    },
    mapper: {
      index: {
        response: toOrdersReadList,
      },
      show: {
        response: toOrdersRead,
      },
    }
  },
  cart: {
    types: {
      createForm: {} as CartForm["Create"],
      createPayload: {} as CartApiCreate,
      updateForm: {} as CartForm["Update"],
      updatePayload: {} as CartApiUpdate,
      response: {} as CartApiResponse,
    },
    contract: {
      create: {
        body: validateCartCreatePayload,
        response: validateCartCreateResponse,
      },
      update: {
        body: validateCartUpdatePayload,
        response: validateCartUpdateResponse,
      },
      destroy: {
        response: validateCartDestroyResponse,
      },
    },
    mapper: {
      create: {
        body: toApiCartCreate,
        response: toCartRead,
      },
      update: {
        body: toApiCartUpdate,
        response: toCartRead,
      },
      destroy: {
        response: toCartRead,
      },
    }
  },
  checkout: {
    types: {
      createForm: {} as CheckoutForm["Create"],
      createPayload: {} as CheckoutApiCreate,
      response: {} as CheckoutApiResponse,
    },
    contract: {
      create: {
        body: validateCheckoutCreatePayload,
        response: validateCheckoutCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiCheckoutCreate,
        response: toCheckoutRead,
      },
    }
  },
  buynow: {
    types: {
      createForm: {} as BuynowForm["Create"],
      createPayload: {} as BuynowApiCreate,
      response: {} as BuynowApiResponse,
    },
    contract: {
      create: {
        body: validateBuynowCreatePayload,
        response: validateBuynowCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiBuynowCreate,
        response: toBuynowRead,
      },
    }
  },
  keranjang: {
    types: {
      index: {} as KeranjangIndex,
      response: {} as KeranjangApiResponse,
    },
    contract: {
      index: {
        response: validateKeranjangIndexResponse,
      },
    },
    mapper: {
      index: {
        response: toKeranjangReadList,
      },
    }
  },
  wishlist: {
    types: {
      index: {} as WishlistIndex,
      createForm: {} as WishlistForm["Create"],
      createPayload: {} as WishlistApiCreate,
      response: {} as WishlistApiResponse,
    },
    contract: {
      index: {
        response: validateWishlistIndexResponse,
      },
      create: {
        body: validateWishlistCreatePayload,
        response: validateWishlistCreateResponse,
      },
      destroy: {
        response: validateWishlistDestroyResponse,
      },
    },
    mapper: {
      index: {
        response: toWishlistReadList,
      },
      create: {
        body: toApiWishlistCreate,
        response: toWishlistRead,
      },
      destroy: {
        response: toWishlistRead,
      },
    }
  },
  logout: {
    types: {
      createForm: {} as LogoutForm["Create"],
      createPayload: {} as LogoutApiCreate,
      response: {} as LogoutApiResponse,
    },
    contract: {
      create: {
        body: validateLogoutCreatePayload,
        response: validateLogoutCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiLogoutCreate,
        response: toLogoutRead,
      },
    }
  },
  admin: {
    types: {
      createForm: {} as AdminForm["Create"],
      createPayload: {} as AdminApiCreate,
      response: {} as AdminApiResponse,
    },
    contract: {
      create: {
        body: validateAdminCreatePayload,
        response: validateAdminCreateResponse,
      },
    },
    mapper: {
      create: {
        body: toApiAdminCreate,
        response: toAdminRead,
      },
    }
  }
}

export type ApiClient = typeof api
export default api

/**
 * Generated Resources Summary:
 * - Register: 1 actions
 * - Login: 1 actions
 * - Oauth: 2 actions
 * - Social: 1 actions
 * - ForgotPassword: 1 actions
 * - ResetPassword: 1 actions
 * - Categories: 1 actions
 * - Produk: 3 actions
 * - Payment: 1 actions
 * - Profile: 2 actions
 * - Orders: 2 actions
 * - Cart: 3 actions
 * - Checkout: 1 actions
 * - BuyNow: 1 actions
 * - Keranjang: 1 actions
 * - Wishlist: 3 actions
 * - Logout: 1 actions
 * - Admin: 1 actions
 * 
 * Total: 18 resources, 27 total actions
 */
