// Auto-generated by routesync. Do not edit manually.

export interface OrderDetailResourceTransformed {
            readonly id: number
  readonly produkItemId: number
  readonly produk: {
  id: number;
  nama: string;
  gambar: string;
  image_url: string;
}
  readonly qty: number
  readonly harga: number
  readonly subtotal: number
  readonly banana: string
  readonly potato: number
  readonly flyingDog: boolean
  readonly foo: unknown
        }

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
            readonly id: number
  readonly status: string
  readonly totalHarga: number
  readonly invoiceNumber: string
  readonly paymentStatus: string
  readonly financialStatus: string
  readonly fulfillmentStatus: string
  readonly subtotalMinor: number
  readonly discountMinor: number
  readonly shippingMinor: number
  readonly taxMinor: number
  readonly totalHargaMinor: number
  readonly items: unknown
  readonly promotion: {
  code: string;
  discount_minor: number;
}
  readonly shipping: {
  nama: string;
  telepon: string;
  alamat: string;
  kota: string;
  kode_pos: string;
}
  readonly createdAt: string
        }

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
            readonly id: number
  readonly orderId: number
  readonly invoiceNumber: string
  readonly metode: string
  readonly detail: string
  readonly status: string
  readonly paidAt: string
  readonly provider: unknown
  readonly providerTxnId: unknown
  readonly gatewayStatus: unknown
  readonly amountMinor: unknown
  readonly refundAmountMinor: unknown
  readonly items: unknown
  readonly promotion: {
  code: string;
  discount_minor: number;
}
  readonly gateway: {
  name: unknown;
  order_id: unknown;
  token: unknown;
  redirect_url: unknown;
}
  readonly totalHarga: number
        }

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
            readonly id: number
  readonly nama: string
  readonly deskripsi: string
  readonly image: string
  readonly imageUrl: string
  readonly categoryId: number
  readonly categoryName: string
  readonly harga: number
  readonly stok: number
  readonly rating: number
  readonly reviewCount: number
        }

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]

export interface RegisterResponseTransformed {
            readonly success: boolean
  readonly message: string
  readonly data: string | null
        }

export type RegisterResponseShow = RegisterResponseTransformed
export type RegisterResponseIndex = RegisterResponseTransformed[]

export interface OauthRedirectTransformed {
            readonly provider: unknown
  readonly authUrl: unknown
        }

export type OauthRedirectShow = OauthRedirectTransformed
export type OauthRedirectIndex = OauthRedirectTransformed[]

export interface OauthCallbackTransformed {
            readonly message: string
  readonly error: unknown
        }

export type OauthCallbackShow = OauthCallbackTransformed
export type OauthCallbackIndex = OauthCallbackTransformed[]

export interface CategoriesTransformed {
            readonly data: unknown
        }

export type CategoriesShow = CategoriesTransformed
export type CategoriesIndex = CategoriesTransformed[]

export interface ProdukItemTransformed {
            readonly id: number
  readonly nama: string
  readonly deskripsi: string | null
  readonly categoryId: number | null
  readonly harga: number
  readonly stok: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProdukItemShow = ProdukItemTransformed
export type ProdukItemIndex = ProdukItemTransformed[]

export interface ProdukReviewsTransformed {
            readonly summary: {
  avg_rating: number;
  total_review: number;
}
  readonly reviews: unknown
        }

export type ProdukReviewsShow = ProdukReviewsTransformed
export type ProdukReviewsIndex = ProdukReviewsTransformed[]

export interface ProfileTransformed {
            readonly id: string
  readonly name: string
  readonly email: string
        }

export type ProfileShow = ProfileTransformed
export type ProfileIndex = ProfileTransformed[]

export interface OrderTransformed {
            readonly id: number
  readonly userId: number
  readonly totalHarga: number
  readonly status: string
  readonly orderNumber: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderShow = OrderTransformed
export type OrderIndex = OrderTransformed[]

export interface PaymentTransformed {
            readonly id: number
  readonly orderId: number
  readonly metode: string | null
  readonly status: string
  readonly paidAt: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentShow = PaymentTransformed
export type PaymentIndex = PaymentTransformed[]

export interface CategoryTransformed {
            readonly id: number
  readonly nama: string
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type CategoryShow = CategoryTransformed
export type CategoryIndex = CategoryTransformed[]

export interface OrderAmountTransformed {
            readonly id: number
  readonly orderId: number
  readonly subtotalMinor: number
  readonly shippingMinor: number
  readonly discountMinor: number
  readonly taxMinor: number
  readonly totalMinor: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderAmountShow = OrderAmountTransformed
export type OrderAmountIndex = OrderAmountTransformed[]

export interface OrderDetailTransformed {
            readonly id: number
  readonly orderId: number
  readonly produkItemId: number
  readonly qty: number
  readonly harga: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
  readonly banana: string | null
  readonly potato: number | null
  readonly flyingDog: boolean | null
        }

export type OrderDetailShow = OrderDetailTransformed
export type OrderDetailIndex = OrderDetailTransformed[]

export interface OrderFinancialTransformed {
            readonly id: number
  readonly orderId: number
  readonly financialStatus: string
  readonly refundedAt: string | null
  readonly refundReason: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderFinancialShow = OrderFinancialTransformed
export type OrderFinancialIndex = OrderFinancialTransformed[]

export interface OrderFulfillmentTransformed {
            readonly id: number
  readonly orderId: number
  readonly fulfillmentStatus: string
  readonly processingAt: string | null
  readonly shippedAt: string | null
  readonly completedAt: string | null
  readonly canceledAt: string | null
  readonly cancelReason: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderFulfillmentShow = OrderFulfillmentTransformed
export type OrderFulfillmentIndex = OrderFulfillmentTransformed[]

export interface OrderPromotionTransformed {
            readonly id: number
  readonly orderId: number
  readonly promoCodeId: number | null
  readonly promoCode: string
  readonly discountMinor: number
  readonly metadata: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderPromotionShow = OrderPromotionTransformed
export type OrderPromotionIndex = OrderPromotionTransformed[]

export interface OrderShippingTransformed {
            readonly id: number
  readonly orderId: number
  readonly nama: string | null
  readonly telepon: string | null
  readonly alamat: string | null
  readonly kota: string | null
  readonly kodePos: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderShippingShow = OrderShippingTransformed
export type OrderShippingIndex = OrderShippingTransformed[]

export interface PaymentAmountTransformed {
            readonly id: number
  readonly paymentId: number
  readonly currencyCode: string
  readonly amountMinor: number
  readonly feeMinor: number
  readonly netAmountMinor: number
  readonly refundAmountMinor: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentAmountShow = PaymentAmountTransformed
export type PaymentAmountIndex = PaymentAmountTransformed[]

export interface PaymentDetailTransformed {
            readonly id: number
  readonly paymentId: number
  readonly detail: string | null
  readonly payloadHash: string | null
  readonly payloadReceivedAt: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentDetailShow = PaymentDetailTransformed
export type PaymentDetailIndex = PaymentDetailTransformed[]

export interface PaymentGatewayTransformed {
            readonly id: number
  readonly paymentId: number
  readonly provider: string | null
  readonly providerTxnId: string | null
  readonly idempotencyKey: string | null
  readonly gatewayStatus: string | null
  readonly gatewayCode: string | null
  readonly gatewayMessage: string | null
  readonly authorizedAt: string | null
  readonly capturedAt: string | null
  readonly failedAt: string | null
  readonly refundedAt: string | null
  readonly reconciledAt: string | null
  readonly reconciliationBatchId: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentGatewayShow = PaymentGatewayTransformed
export type PaymentGatewayIndex = PaymentGatewayTransformed[]

export interface ProductReviewTransformed {
            readonly id: number
  readonly produkItemId: number
  readonly userId: number
  readonly rating: number
  readonly title: string | null
  readonly comment: string | null
  readonly isVerifiedPurchase: boolean
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProductReviewShow = ProductReviewTransformed
export type ProductReviewIndex = ProductReviewTransformed[]

export interface ProdukItemFrontendTransformed {
            readonly id: number
  readonly produkItemId: number
  readonly gambar: string | null
  readonly rating: number
  readonly jumlahReview: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProdukItemFrontendShow = ProdukItemFrontendTransformed
export type ProdukItemFrontendIndex = ProdukItemFrontendTransformed[]

export interface PromoCodeTransformed {
            readonly id: number
  readonly code: string
  readonly discountType: string
  readonly discountValue: number
  readonly maxDiscountMinor: number | null
  readonly minOrderMinor: number
  readonly usageLimit: number | null
  readonly usedCount: number
  readonly isActive: boolean
  readonly startsAt: string | null
  readonly endsAt: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PromoCodeShow = PromoCodeTransformed
export type PromoCodeIndex = PromoCodeTransformed[]

export interface SocialAccountTransformed {
            readonly id: number
  readonly userId: number
  readonly provider: string
  readonly providerUserId: string
  readonly email: string | null
  readonly avatarUrl: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type SocialAccountShow = SocialAccountTransformed
export type SocialAccountIndex = SocialAccountTransformed[]

export interface UserTransformed {
            readonly id: number
  readonly name: string
  readonly email: string
  readonly role: string
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type UserShow = UserTransformed
export type UserIndex = UserTransformed[]

export interface WishlistTransformed {
            readonly id: number
  readonly userId: number
  readonly produkItemId: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type WishlistShow = WishlistTransformed
export type WishlistIndex = WishlistTransformed[]
