// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-06-02T11:24:41.400Z

import { defineApi, endpoint } from 'routesync'


export const api = defineApi({
})

export default api