// Auto-generated by routesync. Do not edit manually.

export interface OrderDetailResourceTransformed {
            readonly id: number
  readonly produkItemId: number
  readonly produk: {
  id: number;
  nama: string;
  gambar: string;
  image_url: string;
}
  readonly qty: number
  readonly harga: number
  readonly subtotal: number
        }

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
            readonly id: number
  readonly status: string
  readonly totalHarga: number
  readonly invoiceNumber: string
  readonly paymentStatus: string
  readonly financialStatus: string
  readonly fulfillmentStatus: string
  readonly subtotalMinor: number
  readonly discountMinor: number
  readonly shippingMinor: number
  readonly taxMinor: number
  readonly totalHargaMinor: number
  readonly items: OrderDetailResourceTransformed[]
  readonly promotion: {
  code: string;
  discount_minor: number;
}
  readonly shipping: {
  nama: string;
  telepon: string;
  alamat: string;
  kota: string;
  kode_pos: string;
}
  readonly createdAt: string
        }

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
            readonly id: number
  readonly orderId: number
  readonly invoiceNumber: string
  readonly metode: string
  readonly detail: string
  readonly status: string
  readonly paidAt: string
  readonly provider: string
  readonly providerTxnId: string
  readonly gatewayStatus: string
  readonly amountMinor: number
  readonly refundAmountMinor: unknown
  readonly items: OrderDetailResourceTransformed[]
  readonly promotion: {
  code: string;
  discount_minor: number;
}
  readonly gateway: {
  name: unknown;
  order_id: unknown;
  token: unknown;
  redirect_url: unknown;
}
  readonly totalHarga: number
        }

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
            readonly id: number
  readonly nama: string
  readonly deskripsi: string
  readonly image: string
  readonly imageUrl: string
  readonly categoryId: number
  readonly categoryName: string
  readonly harga: number
  readonly stok: number
  readonly rating: number
  readonly reviewCount: number
        }

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]

export interface RegisterResponseTransformed {
            readonly success: boolean
  readonly message: string
  readonly data: string | null
        }

export type RegisterResponseShow = RegisterResponseTransformed
export type RegisterResponseIndex = RegisterResponseTransformed[]

export interface OauthRedirectTransformed {
            readonly provider: string
  readonly authUrl: unknown
        }

export type OauthRedirectShow = OauthRedirectTransformed
export type OauthRedirectIndex = OauthRedirectTransformed[]

export interface OauthCallbackTransformed {
            readonly message: string
  readonly error: unknown
        }

export type OauthCallbackShow = OauthCallbackTransformed
export type OauthCallbackIndex = OauthCallbackTransformed[]

export interface CategoriesTransformed {
            readonly data: CategoryTransformed
        }

export type CategoriesShow = CategoriesTransformed
export type CategoriesIndex = CategoriesTransformed[]

export interface ProdukReviewsTransformed {
            readonly summary: {
  avg_rating: number;
  total_review: number;
}
  readonly reviews: ProductReviewTransformed
        }

export type ProdukReviewsShow = ProdukReviewsTransformed
export type ProdukReviewsIndex = ProdukReviewsTransformed[]

export interface ProfileTransformed {
            readonly id: number
  readonly name: string
  readonly email: string
        }

export type ProfileShow = ProfileTransformed
export type ProfileIndex = ProfileTransformed[]

export interface CategoryTransformed {
            readonly id: number
  readonly nama: string
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type CategoryShow = CategoryTransformed
export type CategoryIndex = CategoryTransformed[]

export interface OrderTransformed {
            readonly id: number
  readonly userId: number
  readonly totalHarga: number
  readonly status: string
  readonly orderNumber: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderShow = OrderTransformed
export type OrderIndex = OrderTransformed[]

export interface PaymentTransformed {
            readonly id: number
  readonly orderId: number
  readonly metode: string | null
  readonly status: string
  readonly paidAt: string | null
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentShow = PaymentTransformed
export type PaymentIndex = PaymentTransformed[]

export interface ProductReviewTransformed {
            readonly id: number
  readonly produkItemId: number
  readonly userId: number
  readonly rating: number
  readonly title: string | null
  readonly comment: string | null
  readonly isVerifiedPurchase: boolean
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProductReviewShow = ProductReviewTransformed
export type ProductReviewIndex = ProductReviewTransformed[]

export interface ProdukItemTransformed {
            readonly id: number
  readonly nama: string
  readonly deskripsi: string | null
  readonly categoryId: number | null
  readonly harga: number
  readonly stok: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProdukItemShow = ProdukItemTransformed
export type ProdukItemIndex = ProdukItemTransformed[]
