// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-09-04T11:09:23.668Z

import { defineApi, endpoint } from 'routesync'
import { API_URL, API_ENDPOINTS, ROUTES, Enums } from './constants'
import { toCategoriesRead, toClearCartRead, toForgotPasswordRead, toGeneralResourceRead, toKeranjangRead, toLoginRead, toLogoutRead, toOauthCallbackRead, toOauthRedirectRead, toOrderResourceRead, toPaymentResourceRead, toProdukItemResourceRead, toProdukRead, toProdukReviewsRead, toProfileRead, toRegisterRead, toRemoveItemRead, toResetPasswordRead, toSocialLoginRead, toWebhookRead, toWishlistRead } from './mappers/api-mapper'

export const api = defineApi({
  register: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_REGISTER,
      mapper: {
        response: toRegisterRead,
      },
    }),
  },
  login: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_LOGIN,
      mapper: {
        response: toLoginRead,
      },
    }),
  },
  oauth: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_OAUTH_PROVIDER_REDIRECT,
      mapper: {
        response: toOauthRedirectRead,
      },
    }),
    get2: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_OAUTH_PROVIDER_CALLBACK,
      mapper: {
        response: toOauthCallbackRead,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_OAUTH_PROVIDER_CALLBACK,
      mapper: {
        response: toOauthCallbackRead,
      },
    }),
  },
  social: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_SOCIAL_LOGIN,
      mapper: {
        response: toSocialLoginRead,
      },
    }),
  },
  forgotPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_FORGOT_PASSWORD,
      mapper: {
        response: toForgotPasswordRead,
      },
    }),
  },
  resetPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_RESET_PASSWORD,
      mapper: {
        response: toResetPasswordRead,
      },
    }),
  },
  categories: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_CATEGORIES,
      mapper: {
        response: toCategoriesRead,
      },
    }),
  },
  produk: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_PRODUK,
      mapper: {
        response: toProdukItemResourceRead,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_PRODUK_DETAIL,
      mapper: {
        response: toProdukItemResourceRead,
      },
    }),
    get2: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_PRODUK_DETAIL_REVIEWS,
      mapper: {
        response: toProdukReviewsRead,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_PRODUK_DETAIL_REVIEWS,
      auth: true,
      mapper: {
        response: toProdukReviewsRead,
      },
    }),
  },
  payment: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_PAYMENT_WEBHOOK,
      mapper: {
        response: toWebhookRead,
      },
    }),
    post2: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_PAYMENT_ORDER_ID,
      auth: true,
      mapper: {
        response: toPaymentResourceRead,
      },
    }),
  },
  profile: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_PROFILE,
      auth: true,
      mapper: {
        response: toProfileRead,
      },
    }),
    put: endpoint({
      method: 'PUT',
      path: API_ENDPOINTS.API_PROFILE,
      auth: true,
      mapper: {
        response: toProfileRead,
      },
    }),
    patch: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.API_PROFILE,
      auth: true,
      mapper: {
        response: toProfileRead,
      },
    }),
  },
  orders: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_ORDERS,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_ORDERS_DETAIL,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
    get2: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_ORDERS_DETAIL_INVOICE,
      auth: true,
      mapper: {
        response: toGeneralResourceRead,
      },
    }),
  },
  cart: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_CART_ITEMS,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
    patch: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.API_CART_ITEM,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.API_CART_ITEM,
      auth: true,
      mapper: {
        response: toRemoveItemRead,
      },
    }),
    delete2: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.API_CART,
      auth: true,
      mapper: {
        response: toClearCartRead,
      },
    }),
    post2: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_CART_PROMO,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
    delete3: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.API_CART_PROMO,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  checkout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_CHECKOUT,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  buyNow: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_BUY_NOW,
      auth: true,
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  keranjang: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_KERANJANG,
      auth: true,
      mapper: {
        response: toKeranjangRead,
      },
    }),
  },
  wishlist: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.API_WISHLIST,
      auth: true,
      mapper: {
        response: toProdukItemResourceRead,
      },
    }),
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_WISHLIST,
      auth: true,
      mapper: {
        response: toWishlistRead,
      },
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.API_WISHLIST_PRODUK_ITEM_ID,
      auth: true,
      mapper: {
        response: toWishlistRead,
      },
    }),
  },
  logout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_LOGOUT,
      auth: true,
      mapper: {
        response: toLogoutRead,
      },
    }),
  },
  admin: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.API_ADMIN_PRODUK,
      auth: true,
      mapper: {
        response: toProdukRead,
      },
    }),
  },
})

export default api
