// Auto-generated by routesync. Do not edit manually.

/* =========================
   APPLICATION CONSTANTS
========================= */

export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/api'

export const API_ENDPOINTS = {
  API_ADMIN_PRODUK: '/api/admin/produk',
  API_BUY_NOW: '/api/buy-now',
  API_CART: '/api/cart',
  API_CART_ITEMS: '/api/cart/items',
  API_CART_ITEM: (produkItemId: number) => `/api/cart/items/${produkItemId}`,
  API_CART_PROMO: '/api/cart/promo',
  API_CATEGORIES: '/api/categories',
  API_CHECKOUT: '/api/checkout',
  API_FORGOT_PASSWORD: '/api/forgot-password',
  API_KERANJANG: '/api/keranjang',
  API_LOGIN: '/api/login',
  API_LOGOUT: '/api/logout',
  API_OAUTH_PROVIDER_CALLBACK: (provider: string) => `/api/oauth/${provider}/callback`,
  API_OAUTH_PROVIDER_REDIRECT: (provider: string) => `/api/oauth/${provider}/redirect`,
  API_ORDERS: '/api/orders',
  API_ORDERS_DETAIL: (id: number) => `/api/orders/${id}`,
  API_ORDERS_DETAIL_INVOICE: (id: number) => `/api/orders/${id}/invoice`,
  API_PAYMENT_ORDER_ID: (orderId: number) => `/api/payment/${orderId}`,
  API_PAYMENT_WEBHOOK: '/api/payment/webhook',
  API_PRODUK: '/api/produk',
  API_PRODUK_DETAIL: (id: number) => `/api/produk/${id}`,
  API_PRODUK_DETAIL_REVIEWS: (id: number) => `/api/produk/${id}/reviews`,
  API_PROFILE: '/api/profile',
  API_REGISTER: '/api/register',
  API_RESET_PASSWORD: '/api/reset-password',
  API_SOCIAL_LOGIN: '/api/social/login',
  API_WISHLIST: '/api/wishlist',
  API_WISHLIST_PRODUK_ITEM_ID: (produkItemId: number) => `/api/wishlist/${produkItemId}`,
} as const

export const ROUTES = {
  HOME: '/',
  API_OAUTH_DETAIL_REDIRECT: (provider: string) => `/api/oauth/${provider}/redirect`,
  API_OAUTH_DETAIL_CALLBACK: (provider: string) => `/api/oauth/${provider}/callback`,
  API_CATEGORIES: '/api/categories',
  API_PRODUK: '/api/produk',
  API_PRODUK_DETAIL: (id: number) => `/api/produk/${id}`,
  API_PRODUK_DETAIL_REVIEWS: (id: number) => `/api/produk/${id}/reviews`,
  API_PROFILE: '/api/profile',
  API_ORDERS: '/api/orders',
  API_ORDERS_DETAIL: (id: number) => `/api/orders/${id}`,
  API_KERANJANG: '/api/keranjang',
  API_WISHLIST: '/api/wishlist',
  API_ORDERS_DETAIL_INVOICE: (id: number) => `/api/orders/${id}/invoice`,
} as const

export const Enums = {
  Social: {
    Provider: {
      GOOGLE: 'google',
      FACEBOOK: 'facebook',
      APPLE: 'apple',
    } as const,
  },
} as const

export type SocialProvider = (typeof Enums.Social.Provider)[keyof typeof Enums.Social.Provider]
