// Auto-generated by routesync. Do not edit manually.

import { defineHooks, useAggregateCollectionIntent } from 'routesync/react'
import { api } from './api'
import { QueryKey } from './query-key'
import { runtimeManifest } from './routesync.runtime'
import type {
  AdminForm,
  CategoriesTransformed,
  ForgotPasswordForm,
  KeranjangTransformed,
  OauthForm,
  OauthRedirectTransformed,
  OrderResourceTransformed,
  ProdukForm,
  ProdukItemResourceTransformed,
  ProfileTransformed,
  ResetPasswordForm,
  SocialForm,
  WishlistForm,
} from './types/index'
import type {
  CartPost2Payload,
} from './contract/api-schema'

export const typeOf = <T>() => ({} as T)

const baseHooks = defineHooks({
  register: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.register,
    actionKeys: {
      create: QueryKey.register.create,
    },
    endpoint: api.register,

    cache: {
      create: {
        invalidate: [
          QueryKey.register.all,
        ],
      },
    },
  },
  login: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.login,
    actionKeys: {
      create: QueryKey.login.create,
    },
    endpoint: api.login,

    cache: {
      create: {
        invalidate: [
          QueryKey.login.all,
        ],
      },
    },
  },
  oauth: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<OauthRedirectTransformed>(),
      create: typeOf<OauthForm['Get']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.oauth,
    actionKeys: {
      get: QueryKey.oauth.get,
      get2: QueryKey.oauth.get2,
      post: QueryKey.oauth.post,
    },
    endpoint: api.oauth,

    cache: {
      post: {
        invalidate: [
          QueryKey.oauth.get,
          QueryKey.oauth.get2,
          QueryKey.oauth.all,
        ],
      },
    },
  },
  social: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<SocialForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.social,
    actionKeys: {
      post: QueryKey.social.post,
    },
    endpoint: api.social,

    cache: {
      post: {
        invalidate: [
          QueryKey.social.all,
        ],
      },
    },
  },
  forgotPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ForgotPasswordForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.forgotPassword,
    actionKeys: {
      create: QueryKey.forgotPassword.create,
    },
    endpoint: api.forgotPassword,

    cache: {
      create: {
        invalidate: [
          QueryKey.forgotPassword.all,
        ],
      },
    },
  },
  resetPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ResetPasswordForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.resetPassword,
    actionKeys: {
      create: QueryKey.resetPassword.create,
    },
    endpoint: api.resetPassword,

    cache: {
      create: {
        invalidate: [
          QueryKey.resetPassword.all,
        ],
      },
    },
  },
  categories: {
    types: {
      list: typeOf<CategoriesTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.categories,
    actionKeys: {
      list: QueryKey.categories.list,
    },
    endpoint: api.categories,

    cache: {
      list: QueryKey.categories.list,
    },
  },
  produk: {
    types: {
      list: typeOf<ProdukItemResourceTransformed>(),
      detail: typeOf<ProdukItemResourceTransformed>(),
      create: typeOf<ProdukForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.produk,
    actionKeys: {
      list: QueryKey.produk.list,
      get: QueryKey.produk.get,
      get2: QueryKey.produk.get2,
      post: QueryKey.produk.post,
    },
    endpoint: api.produk,

    cache: {
      list: QueryKey.produk.lists,
      detail: QueryKey.produk.detail,
      post: {
        invalidate: [
          QueryKey.produk.lists,
          QueryKey.produk.get2,
          QueryKey.produk.all,
        ],
      },
    },
  },
  payment: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.payment,
    actionKeys: {
      post: QueryKey.payment.post,
      post2: QueryKey.payment.post2,
    },
    endpoint: api.payment,

    cache: {
      post: {
        invalidate: [
          QueryKey.payment.all,
        ],
      },
      post2: {
        invalidate: [
          QueryKey.payment.all,
        ],
      },
    },
  },
  profile: {
    types: {
      list: typeOf<ProfileTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.profile,
    actionKeys: {
      list: QueryKey.profile.list,
      put: QueryKey.profile.put,
      patch: QueryKey.profile.patch,
    },
    endpoint: api.profile,

    cache: {
      list: QueryKey.profile.list,
      put: {
        invalidate: [
          QueryKey.profile.list,
          QueryKey.profile.all,
        ],
      },
      patch: {
        invalidate: [
          QueryKey.profile.list,
          QueryKey.profile.all,
        ],
      },
    },
  },
  orders: {
    types: {
      list: typeOf<OrderResourceTransformed>(),
      detail: typeOf<OrderResourceTransformed>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.orders,
    actionKeys: {
      list: QueryKey.orders.list,
      get: QueryKey.orders.get,
      get2: QueryKey.orders.get2,
    },
    endpoint: api.orders,

    cache: {
      list: QueryKey.orders.lists,
      detail: QueryKey.orders.detail,
    },
  },
  cart: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<CartPost2Payload>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.cart,
    actionKeys: {
      post: QueryKey.cart.post,
      patch: QueryKey.cart.patch,
      delete: QueryKey.cart.delete,
      delete2: QueryKey.cart.delete2,
      post2: QueryKey.cart.post2,
      delete3: QueryKey.cart.delete3,
    },
    endpoint: api.cart,

    cache: {
      post: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      patch: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete2: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      post2: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
      delete3: {
        invalidate: [
          QueryKey.cart.all,
        ],
      },
    },
  },
  checkout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.checkout,
    actionKeys: {
      create: QueryKey.checkout.create,
    },
    endpoint: api.checkout,

    cache: {
      create: {
        invalidate: [
          QueryKey.checkout.all,
        ],
      },
    },
  },
  buyNow: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.buyNow,
    actionKeys: {
      create: QueryKey.buyNow.create,
    },
    endpoint: api.buyNow,

    cache: {
      create: {
        invalidate: [
          QueryKey.buyNow.all,
        ],
      },
    },
  },
  keranjang: {
    types: {
      list: typeOf<KeranjangTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.keranjang,
    actionKeys: {
      list: QueryKey.keranjang.list,
    },
    endpoint: api.keranjang,

    cache: {
      list: QueryKey.keranjang.list,
    },
  },
  wishlist: {
    types: {
      list: typeOf<ProdukItemResourceTransformed>(),
      detail: typeOf<never>(),
      create: typeOf<WishlistForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.wishlist,
    actionKeys: {
      list: QueryKey.wishlist.list,
      create: QueryKey.wishlist.create,
      remove: QueryKey.wishlist.remove,
    },
    endpoint: api.wishlist,

    cache: {
      list: QueryKey.wishlist.list,
      create: {
        invalidate: [
          QueryKey.wishlist.list,
          QueryKey.wishlist.all,
        ],
      },
      remove: {
        invalidate: [
          QueryKey.wishlist.list,
          QueryKey.wishlist.all,
        ],
      },
    },
  },
  logout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<void>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.logout,
    actionKeys: {
      create: QueryKey.logout.create,
    },
    endpoint: api.logout,

    cache: {
      create: {
        invalidate: [
          QueryKey.logout.all,
          QueryKey.profile.all,
          QueryKey.orders.all,
          QueryKey.cart.all,
          QueryKey.checkout.all,
          QueryKey.buyNow.all,
          QueryKey.keranjang.all,
          QueryKey.wishlist.all,
          QueryKey.produk.all,
          QueryKey.payment.all,
          QueryKey.admin.all,
        ],
      },
    },
  },
  admin: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<AdminForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.admin,
    actionKeys: {
      post: QueryKey.admin.post,
    },
    endpoint: api.admin,

    cache: {
      post: {
        invalidate: [
          QueryKey.admin.all,
        ],
      },
    },
  },
}, runtimeManifest)

export const hooks = baseHooks

export const useRegister = hooks.register
export const useLogin = hooks.login
export const useOauth = hooks.oauth
export const useSocial = hooks.social
export const useForgotPassword = hooks.forgotPassword
export const useResetPassword = hooks.resetPassword
export const useCategories = hooks.categories
export const useProduk = hooks.produk
export const usePayment = hooks.payment
export const useProfile = hooks.profile
export const useOrders = hooks.orders
export const useCart = hooks.cart
export const useCheckout = hooks.checkout
export const useBuyNow = hooks.buyNow
export const useKeranjang = hooks.keranjang
export const useWishlist = hooks.wishlist
export const useLogout = hooks.logout
export const useAdmin = hooks.admin

export * from './query-key'
