// Auto-generated by routesync. Do not edit manually.

/* =========================
   ENTITY CONSTANTS
========================= */
export const Entity = {
  REGISTER: "register",
  LOGIN: "login",
  OAUTH: "oauth",
  SOCIAL: "social",
  FORGOTPASSWORD: "forgotPassword",
  RESETPASSWORD: "resetPassword",
  CATEGORIES: "categories",
  PRODUK: "produk",
  PAYMENT: "payment",
  PROFILE: "profile",
  ORDERS: "orders",
  CART: "cart",
  CHECKOUT: "checkout",
  BUYNOW: "buyNow",
  KERANJANG: "keranjang",
  WISHLIST: "wishlist",
  LOGOUT: "logout",
  ADMIN: "admin",
} as const

type EntityValue = (typeof Entity)[keyof typeof Entity]

/* =========================
   BASE FACTORY (GENERIC)
========================= */
const createBaseQueryKey = <T extends EntityValue, TId = string | number, TFilter = Record<string, unknown>>(entity: T) => ({
  all:     ()                         => [entity] as const,
  lists:   ()                         => [entity, "list"] as const,
  list:    (filters?: TFilter)        =>
             [entity, "list", filters ?? {}] as const,
  details: ()                         => [entity, "detail"] as const,
  detail:  (id: TId)                  => [entity, "detail", id] as const,
})

/* =========================
   QUERY KEY REGISTRY
========================= */
export const QueryKey = {
  /* ===== REGISTER ===== */
  register: {
    all: () => [Entity.REGISTER] as const,
    create: () => [Entity.REGISTER, "create"] as const,
  },

  /* ===== LOGIN ===== */
  login: {
    all: () => [Entity.LOGIN] as const,
    create: () => [Entity.LOGIN, "create"] as const,
  },

  /* ===== OAUTH ===== */
  oauth: {
    all: () => [Entity.OAUTH] as const,
    get: (params?: string | number | Record<string, unknown>) => [Entity.OAUTH, "get", params ?? {}] as const,
    get2: (params?: string | number | Record<string, unknown>) => [Entity.OAUTH, "get2", params ?? {}] as const,
    post: (params?: string | number | Record<string, unknown>) => [Entity.OAUTH, "post", params ?? {}] as const,
  },

  /* ===== SOCIAL ===== */
  social: {
    all: () => [Entity.SOCIAL] as const,
    post: () => [Entity.SOCIAL, "post"] as const,
  },

  /* ===== FORGOTPASSWORD ===== */
  forgotPassword: {
    all: () => [Entity.FORGOTPASSWORD] as const,
    create: () => [Entity.FORGOTPASSWORD, "create"] as const,
  },

  /* ===== RESETPASSWORD ===== */
  resetPassword: {
    all: () => [Entity.RESETPASSWORD] as const,
    create: () => [Entity.RESETPASSWORD, "create"] as const,
  },

  /* ===== CATEGORIES ===== */
  categories: {
    all: () => [Entity.CATEGORIES] as const,
    list: () => [Entity.CATEGORIES, "list"] as const,
  },

  /* ===== PRODUK ===== */
  produk: {
    ...createBaseQueryKey<typeof Entity.PRODUK, string | number>(Entity.PRODUK),
    list: () => [Entity.PRODUK, "list"] as const,
    get: (params?: string | number | Record<string, unknown>) => [Entity.PRODUK, "get", params ?? {}] as const,
    get2: (params?: string | number | Record<string, unknown>) => [Entity.PRODUK, "get2", params ?? {}] as const,
    post: (params?: string | number | Record<string, unknown>) => [Entity.PRODUK, "post", params ?? {}] as const,
  },

  /* ===== PAYMENT ===== */
  payment: {
    all: () => [Entity.PAYMENT] as const,
    post: () => [Entity.PAYMENT, "post"] as const,
    post2: (params?: string | number | Record<string, unknown>) => [Entity.PAYMENT, "post2", params ?? {}] as const,
  },

  /* ===== PROFILE ===== */
  profile: {
    all: () => [Entity.PROFILE] as const,
    list: () => [Entity.PROFILE, "list"] as const,
    put: () => [Entity.PROFILE, "put"] as const,
    patch: () => [Entity.PROFILE, "patch"] as const,
  },

  /* ===== ORDERS ===== */
  orders: {
    ...createBaseQueryKey<typeof Entity.ORDERS, number>(Entity.ORDERS),
    list: () => [Entity.ORDERS, "list"] as const,
    get: (params?: string | number | Record<string, unknown>) => [Entity.ORDERS, "get", params ?? {}] as const,
    get2: (params?: string | number | Record<string, unknown>) => [Entity.ORDERS, "get2", params ?? {}] as const,
  },

  /* ===== CART ===== */
  cart: {
    all: () => [Entity.CART] as const,
    post: () => [Entity.CART, "post"] as const,
    patch: (params?: string | number | Record<string, unknown>) => [Entity.CART, "patch", params ?? {}] as const,
    delete: (params?: string | number | Record<string, unknown>) => [Entity.CART, "delete", params ?? {}] as const,
    delete2: () => [Entity.CART, "delete2"] as const,
    post2: () => [Entity.CART, "post2"] as const,
    delete3: () => [Entity.CART, "delete3"] as const,
  },

  /* ===== CHECKOUT ===== */
  checkout: {
    all: () => [Entity.CHECKOUT] as const,
    create: () => [Entity.CHECKOUT, "create"] as const,
  },

  /* ===== BUYNOW ===== */
  buyNow: {
    all: () => [Entity.BUYNOW] as const,
    create: () => [Entity.BUYNOW, "create"] as const,
  },

  /* ===== KERANJANG ===== */
  keranjang: {
    all: () => [Entity.KERANJANG] as const,
    list: () => [Entity.KERANJANG, "list"] as const,
  },

  /* ===== WISHLIST ===== */
  wishlist: {
    all: () => [Entity.WISHLIST] as const,
    list: () => [Entity.WISHLIST, "list"] as const,
    create: () => [Entity.WISHLIST, "create"] as const,
    remove: (params?: string | number | Record<string, unknown>) => [Entity.WISHLIST, "remove", params ?? {}] as const,
  },

  /* ===== LOGOUT ===== */
  logout: {
    all: () => [Entity.LOGOUT] as const,
    create: () => [Entity.LOGOUT, "create"] as const,
  },

  /* ===== ADMIN ===== */
  admin: {
    all: () => [Entity.ADMIN] as const,
    post: () => [Entity.ADMIN, "post"] as const,
  },

} as const

/* =========================
   BACKWARD COMPATIBLE EXPORTS
========================= */
export const registerKeys = QueryKey.register
export const loginKeys = QueryKey.login
export const oauthKeys = QueryKey.oauth
export const socialKeys = QueryKey.social
export const forgotPasswordKeys = QueryKey.forgotPassword
export const resetPasswordKeys = QueryKey.resetPassword
export const categoriesKeys = QueryKey.categories
export const produkKeys = QueryKey.produk
export const paymentKeys = QueryKey.payment
export const profileKeys = QueryKey.profile
export const ordersKeys = QueryKey.orders
export const cartKeys = QueryKey.cart
export const checkoutKeys = QueryKey.checkout
export const buyNowKeys = QueryKey.buyNow
export const keranjangKeys = QueryKey.keranjang
export const wishlistKeys = QueryKey.wishlist
export const logoutKeys = QueryKey.logout
export const adminKeys = QueryKey.admin
