// Auto-generated by routesync. Do not edit manually.

import { z } from 'zod'

export const CategorySchema = z.object({
  id: z.number(),
  nama: z.string().nullable(),
})

export const OrderSchema = z.object({
  id: z.number(),
  userId: z.string().nullable(),
  totalHarga: z.string().nullable(),
  status: z.string().nullable(),
  orderNumber: z.string().nullable(),
})

export const OrderAmountSchema = z.object({
  id: z.number(),
  orderId: z.number().nullable(),
  subtotalMinor: z.number().nullable(),
  shippingMinor: z.number().nullable(),
  discountMinor: z.number().nullable(),
  taxMinor: z.number().nullable(),
  totalMinor: z.number().nullable(),
  subtotal: z.unknown().optional(), // accessor attribute
  shipping: z.unknown().optional(), // accessor attribute
  discount: z.unknown().optional(), // accessor attribute
  tax: z.unknown().optional(), // accessor attribute
  total: z.unknown().optional(), // accessor attribute
})

export const OrderDetailSchema = z.object({
  id: z.number(),
  orderId: z.string().nullable(),
  produkItemId: z.string().nullable(),
  qty: z.number().nullable(),
  harga: z.number().nullable(),
  foo: z.unknown().optional(), // accessor attribute
})

export const OrderFinancialSchema = z.object({
  id: z.number(),
  orderId: z.number().nullable(),
  financialStatus: z.string().nullable(),
  refundedAt: z.string().nullable(),
  refundReason: z.string().nullable(),
})

export const OrderFulfillmentSchema = z.object({
  id: z.number(),
  orderId: z.number().nullable(),
  fulfillmentStatus: z.string().nullable(),
  processingAt: z.string().nullable(),
  shippedAt: z.string().nullable(),
  completedAt: z.string().nullable(),
  canceledAt: z.string().nullable(),
  cancelReason: z.string().nullable(),
})

export const OrderPromotionSchema = z.object({
  id: z.number(),
  orderId: z.string().nullable(),
  promoCodeId: z.string().nullable(),
  promoCode: z.string().nullable(),
  discountMinor: z.number().nullable(),
  metadata: z.record(z.string(), z.unknown()).nullable(),
})

export const OrderShippingSchema = z.object({
  id: z.number(),
  orderId: z.string().nullable(),
  nama: z.string().nullable(),
  telepon: z.string().nullable(),
  alamat: z.string().nullable(),
  kota: z.string().nullable(),
  kodePos: z.string().nullable(),
  courierCode: z.string().nullable(),
  serviceLevel: z.string().nullable(),
  trackingNumber: z.string().nullable(),
  estimatedArrivalAt: z.string().nullable(),
  shippedAt: z.string().nullable(),
  deliveredAt: z.string().nullable(),
})

export const PaymentSchema = z.object({
  id: z.number(),
  orderId: z.string().nullable(),
  metode: z.string().nullable(),
  status: z.string().nullable(),
  paidAt: z.string().nullable(),
  gatewayStatus: z.unknown().optional(), // accessor attribute
  amountMinor: z.unknown().optional(), // accessor attribute
  providerTxnId: z.unknown().optional(), // accessor attribute
  provider: z.unknown().optional(), // accessor attribute
  refundAmountMinor: z.unknown().optional(), // accessor attribute
  foo: z.unknown().optional(), // accessor attribute
  bar: z.unknown().optional(), // accessor attribute
})

export const PaymentAmountSchema = z.object({
  id: z.number(),
  paymentId: z.string().nullable(),
  currencyCode: z.string().nullable(),
  amountMinor: z.number().nullable(),
  feeMinor: z.number().nullable(),
  netAmountMinor: z.number().nullable(),
  refundAmountMinor: z.number().nullable(),
})

export const PaymentDetailSchema = z.object({
  id: z.number(),
  paymentId: z.string().nullable(),
  detail: z.record(z.string(), z.unknown()).nullable(),
  payloadHash: z.string().nullable(),
  payloadReceivedAt: z.string().nullable(),
})

export const PaymentGatewaySchema = z.object({
  id: z.number(),
  paymentId: z.string().nullable(),
  provider: z.string().nullable(),
  providerTxnId: z.string().nullable(),
  idempotencyKey: z.string().nullable(),
  gatewayStatus: z.string().nullable(),
  gatewayCode: z.string().nullable(),
  gatewayMessage: z.string().nullable(),
  authorizedAt: z.string().nullable(),
  capturedAt: z.string().nullable(),
  failedAt: z.string().nullable(),
  refundedAt: z.string().nullable(),
  reconciledAt: z.string().nullable(),
  reconciliationBatchId: z.string().nullable(),
})

export const ProductReviewSchema = z.object({
  id: z.number(),
  produkItemId: z.string().nullable(),
  userId: z.string().nullable(),
  rating: z.number().nullable(),
  title: z.string().nullable(),
  comment: z.string().nullable(),
  isVerifiedPurchase: z.boolean().nullable(),
})

export const ProdukItemSchema = z.object({
  id: z.number(),
  nama: z.string().nullable(),
  deskripsi: z.string().nullable(),
  categoryId: z.number().nullable(),
  currencyCode: z.string().nullable(),
  harga: z.number().nullable(),
  hargaMinor: z.number().nullable(),
  stok: z.number().nullable(),
  image: z.unknown().optional(), // appended attribute
  imageUrl: z.unknown().optional(), // appended attribute
  categoryName: z.unknown().optional(), // appended attribute
  rating: z.unknown().optional(), // appended attribute
  reviewCount: z.unknown().optional(), // appended attribute
})

export const ProdukItemFrontendSchema = z.object({
  id: z.number(),
  produkItemId: z.string().nullable(),
  gambar: z.string().nullable(),
  rating: z.number().nullable(),
  jumlahReview: z.number().nullable(),
})

export const PromoCodeSchema = z.object({
  id: z.number(),
  code: z.string().nullable(),
  discountType: z.string().nullable(),
  discountValue: z.number().nullable(),
  maxDiscountMinor: z.number().nullable(),
  minOrderMinor: z.number().nullable(),
  usageLimit: z.number().nullable(),
  usedCount: z.number().nullable(),
  isActive: z.boolean().nullable(),
  startsAt: z.string().nullable(),
  endsAt: z.string().nullable(),
})

export const SocialAccountSchema = z.object({
  id: z.number(),
  userId: z.string().nullable(),
  provider: z.string().nullable(),
  providerUserId: z.string().nullable(),
  email: z.string().nullable(),
  avatarUrl: z.string().nullable(),
})

export const UserSchema = z.object({
  id: z.number(),
  name: z.string().nullable(),
  email: z.string().nullable(),
  password: z.string().nullable().optional(),
  role: z.string().nullable(),
  useFactory: z.unknown().optional(), // accessor attribute
})

export const WishlistSchema = z.object({
  id: z.number(),
  userId: z.string().nullable(),
  produkItemId: z.string().nullable(),
})

export const RegisterResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.unknown().nullable(),
})

export const RegisterCreateSchema = z.object({
  name: z.string(),
  email: z.string(),
  password: z.string(),
})

export const LoginCreateSchema = z.object({
  email: z.string(),
  password: z.string(),
})

export const OauthRedirectGetSchema = z.object({
  redirectTo: z.string().optional().nullable(),
})

export const SocialLoginCreateSchema = z.object({
  provider: z.string(),
  providerUserId: z.string(),
  email: z.string(),
  name: z.string().optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
})

export const ForgotPasswordCreateSchema = z.object({
  email: z.string(),
})

export const ResetPasswordCreateSchema = z.object({
  email: z.string(),
  token: z.string(),
  password: z.string(),
})

export const ProdukReviewsPostSchema = z.object({
  rating: z.number(),
  title: z.string().optional().nullable(),
  comment: z.string().optional().nullable(),
})

export const ProfilePutSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const ProfilePatchSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const CartItemsCreateSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
})

export const CartItemsUpdateSchema = z.object({
  qty: z.number(),
})

export const CartPromoCreateSchema = z.object({
  code: z.string(),
})

export const CheckoutCreateSchema = z.object({
  items: z.array(z.unknown()).optional(),
  "items.*.produkItemId": z.string(),
  "items.*.qty": z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const BuyNowCreateSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const WishlistCreateSchema = z.object({
  produkItemId: z.string(),
})

export const PaymentPostSchema = z.object({
  metode: z.string(),
  detail: z.array(z.unknown()).optional().nullable(),
  provider: z.string().optional().nullable(),
  providerTxnId: z.string().optional().nullable(),
  idempotencyKey: z.string().optional().nullable(),
  gatewayCode: z.string().optional().nullable(),
  gatewayMessage: z.string().optional().nullable(),
})

export const AdminProdukCreateSchema = z.object({
  nama: z.string(),
  deskripsi: z.string().optional().nullable(),
  gambar: z.string().optional().nullable(),
  categoryId: z.string(),
  harga: z.number(),
  stok: z.number(),
  rating: z.number().optional().nullable(),
  jumlahReview: z.number().optional().nullable(),
})
