// Auto-generated by routesync. Do not edit manually.

// ⭐ Contract types (Response types from Zod schemas)
import type {
  OrderDetailResourceResponse,
  OrderResourceResponse,
  PaymentResourceResponse,
  ProdukItemResourceResponse,
  RegisterResponseResponse,
  OauthRedirectResponse,
  OauthCallbackResponse,
  CategoriesResponse,
  ProdukReviewsResponse,
  ProfileResponse,
  CategoryResponse,
  OrderResponse,
  PaymentResponse,
  ProductReviewResponse,
  ProdukItemResponse,
  LoginResponse,
  SocialLoginResponse,
  ProdukListResponse,
  ProdukReviewsGetResponse,
  ProdukReviewsCreateResponse,
  OrdersListResponse,
  WishlistListResponse,
} from '../contract/api-contract'

// ⭐ Schema payload types (Request types for API calls)
// No schema types needed

// ⭐ Frontend types (Transformed display types)
import type {
  OrderDetailTransformed,
  OrderTransformed,
  PaymentTransformed,
  ProdukItemTransformed,
  RegisterResponseTransformed,
  OauthRedirectTransformed,
  OauthCallbackTransformed,
  CategoriesTransformed,
  ProdukReviewsTransformed,
  ProfileTransformed,
  CategoryTransformed,
  OrderTransformed,
  PaymentTransformed,
  ProductReviewTransformed,
  ProdukItemTransformed,
} from '../types/api-read'

// ⭐ Field constants for API payload transformation
import { ApiApiField } from '../contract/api-field'

// ⭐ Form types for body mappers
// No form types needed

// ==== READ MAPPERS (API Response → Frontend Model) ====
// Transforms snake_case API responses to camelCase frontend models

export const toOrderDetailRead = (api: OrderDetailResourceResponse): OrderDetailResourceTransformed => ({
    id: api.id,
    produkItemId: api.produk_item_id,
    produk: api.produk,
    qty: api.qty,
    harga: api.harga,
    subtotal: api.subtotal,
  })

export const toOrderDetailReadList = (api: OrderDetailResourceResponse[]): OrderDetailResourceTransformed[] =>
  api.map(toOrderDetailRead)

export const toOrderRead = (api: OrderResourceResponse): OrderResourceTransformed => ({
    id: api.id,
    status: api.status,
    totalHarga: api.total_harga,
    invoiceNumber: api.invoice_number,
    paymentStatus: api.payment_status,
    financialStatus: api.financial_status,
    fulfillmentStatus: api.fulfillment_status,
    subtotalMinor: api.subtotal_minor,
    discountMinor: api.discount_minor,
    shippingMinor: api.shipping_minor,
    taxMinor: api.tax_minor,
    totalHargaMinor: api.total_harga_minor,
    items: api.items,
    promotion: api.promotion,
    shipping: api.shipping,
    createdAt: api.created_at,
  })

export const toOrderReadList = (api: OrderResourceResponse[]): OrderResourceTransformed[] =>
  api.map(toOrderRead)

export const toPaymentRead = (api: PaymentResourceResponse): PaymentResourceTransformed => ({
    id: api.id,
    orderId: api.order_id,
    invoiceNumber: api.invoice_number,
    metode: api.metode,
    detail: api.detail,
    status: api.status,
    paidAt: api.paid_at,
    provider: api.provider,
    providerTxnId: api.provider_txn_id,
    gatewayStatus: api.gateway_status,
    amountMinor: api.amount_minor,
    refundAmountMinor: api.refund_amount_minor,
    items: api.items,
    promotion: api.promotion,
    gateway: api.gateway,
    totalHarga: api.total_harga,
  })

export const toPaymentReadList = (api: PaymentResourceResponse[]): PaymentResourceTransformed[] =>
  api.map(toPaymentRead)

export const toProdukItemRead = (api: ProdukItemResourceResponse): ProdukItemResourceTransformed => ({
    id: api.id,
    nama: api.nama,
    deskripsi: api.deskripsi,
    image: api.image,
    imageUrl: api.image_url,
    categoryId: api.category_id,
    categoryName: api.category_name,
    harga: api.harga,
    stok: api.stok,
    rating: api.rating,
    reviewCount: api.review_count,
  })

export const toProdukItemReadList = (api: ProdukItemResourceResponse[]): ProdukItemResourceTransformed[] =>
  api.map(toProdukItemRead)

export const toRegisterResponseRead = (api: RegisterResponseResponse): RegisterResponseTransformed => ({
    success: api.success,
    message: api.message,
    data: api.data,
  })

export const toRegisterResponseReadList = (api: RegisterResponseResponse[]): RegisterResponseTransformed[] =>
  api.map(toRegisterResponseRead)

export const toOauthRedirectRead = (api: OauthRedirectResponse): OauthRedirectTransformed => ({
    provider: api.provider,
    authUrl: api.auth_url,
  })

export const toOauthRedirectReadList = (api: OauthRedirectResponse[]): OauthRedirectTransformed[] =>
  api.map(toOauthRedirectRead)

export const toOauthCallbackRead = (api: OauthCallbackResponse): OauthCallbackTransformed => ({
    message: api.message,
    error: api.error,
  })

export const toOauthCallbackReadList = (api: OauthCallbackResponse[]): OauthCallbackTransformed[] =>
  api.map(toOauthCallbackRead)

export const toCategoriesRead = (api: CategoriesResponse): CategoriesTransformed => ({
    data: api.data,
  })

export const toCategoriesReadList = (api: CategoriesResponse[]): CategoriesTransformed[] =>
  api.map(toCategoriesRead)

export const toProdukReviewsRead = (api: ProdukReviewsResponse): ProdukReviewsTransformed => ({
    summary: api.summary,
    reviews: api.reviews,
  })

export const toProdukReviewsReadList = (api: ProdukReviewsResponse[]): ProdukReviewsTransformed[] =>
  api.map(toProdukReviewsRead)

export const toProfileRead = (api: ProfileResponse): ProfileTransformed => ({
    id: api.id,
    name: api.name,
    email: api.email,
  })

export const toProfileReadList = (api: ProfileResponse[]): ProfileTransformed[] =>
  api.map(toProfileRead)

export const toCategoryRead = (api: CategoryResponse): CategoryTransformed => ({
    id: api.id,
    nama: api.nama,
    createdAt: api.created_at,
    updatedAt: api.updated_at,
  })

export const toCategoryReadList = (api: CategoryResponse[]): CategoryTransformed[] =>
  api.map(toCategoryRead)

export const toOrderRead = (api: OrderResponse): OrderTransformed => ({
    id: api.id,
    userId: api.user_id,
    totalHarga: api.total_harga,
    status: api.status,
    orderNumber: api.order_number,
    createdAt: api.created_at,
    updatedAt: api.updated_at,
  })

export const toOrderReadList = (api: OrderResponse[]): OrderTransformed[] =>
  api.map(toOrderRead)

export const toPaymentRead = (api: PaymentResponse): PaymentTransformed => ({
    id: api.id,
    orderId: api.order_id,
    metode: api.metode,
    status: api.status,
    paidAt: api.paid_at,
    createdAt: api.created_at,
    updatedAt: api.updated_at,
  })

export const toPaymentReadList = (api: PaymentResponse[]): PaymentTransformed[] =>
  api.map(toPaymentRead)

export const toProductReviewRead = (api: ProductReviewResponse): ProductReviewTransformed => ({
    id: api.id,
    produkItemId: api.produk_item_id,
    userId: api.user_id,
    rating: api.rating,
    title: api.title,
    comment: api.comment,
    isVerifiedPurchase: api.is_verified_purchase,
    createdAt: api.created_at,
    updatedAt: api.updated_at,
  })

export const toProductReviewReadList = (api: ProductReviewResponse[]): ProductReviewTransformed[] =>
  api.map(toProductReviewRead)

export const toProdukItemRead = (api: ProdukItemResponse): ProdukItemTransformed => ({
    id: api.id,
    nama: api.nama,
    deskripsi: api.deskripsi,
    categoryId: api.category_id,
    harga: api.harga,
    stok: api.stok,
    createdAt: api.created_at,
    updatedAt: api.updated_at,
  })

export const toProdukItemReadList = (api: ProdukItemResponse[]): ProdukItemTransformed[] =>
  api.map(toProdukItemRead)

// ==== FORM MAPPERS (Frontend Form → API Payload) ====
// Transforms camelCase form data to snake_case API payloads using ApiApiField
