// Auto-generated by routesync. Do not edit manually.

// ⭐ Contract types (Response types from Zod schemas)
import type {
  LoginResponse,
  OauthRedirectResponse,
  SocialLoginResponse,
  CategoriesResponse,
  ProdukListResponse,
  ProdukReviewsGetResponse,
  ProdukReviewsCreateResponse,
  OrdersListResponse,
  WishlistListResponse,
} from '../contract/api-contract'

// ⭐ Schema payload types (Request types for API calls)
// No schema types needed

// ⭐ Frontend types (Transformed display types)
import type {
  CategoriesTransformed,
  OauthRedirectTransformed,
  ProdukReviewsTransformed,
  RegisterResponseTransformed,
} from '../types/api-read'

// ⭐ Field constants for API payload transformation
import { ApiApiField } from '../contract/api-field'

// ⭐ Form types for body mappers
// No form types needed

// ==== READ MAPPERS (API Response → Frontend Model) ====
// Transforms snake_case API responses to camelCase frontend models

// ==== FORM MAPPERS (Frontend Form → API Payload) ====
// Transforms camelCase form data to snake_case API payloads using ApiApiField
