// Auto-generated by routesync. Do not edit manually.

// ⭐ Contract types (Response types from Zod schemas)
import type {
  RegisterResponseResponse,
  ProdukItemResponse,
  OrderResponse,
  PaymentResponse,
  LoginResponse,
  OauthRedirectResponse,
  SocialLoginResponse,
  CategoriesResponse,
  ProdukListResponse,
  ProdukReviewsGetResponse,
  ProdukReviewsCreateResponse,
  OrdersListResponse,
  WishlistListResponse,
} from '../contract/api-contract'

// ⭐ Schema payload types (Request types for API calls)
// No schema types needed

// ⭐ Frontend types (Transformed display types)
import type {
  RegisterResponseTransformed,
  ProdukItemTransformed,
  OrderTransformed,
  PaymentTransformed,
  CategoriesTransformed,
  OauthRedirectTransformed,
  ProdukReviewsTransformed,
} from '../types/api-read'

// ⭐ Field constants for API payload transformation
import { ApiApiField } from '../contract/api-field'

// ⭐ Form types for body mappers
// No form types needed

// ==== READ MAPPERS (API Response → Frontend Model) ====
// Transforms snake_case API responses to camelCase frontend models

export const toRegisterResponseRead = (api: RegisterResponseResponse): RegisterResponseTransformed => ({
    rules: api.rules,
  })

export const toRegisterResponseReadList = (api: RegisterResponseResponse[]): RegisterResponseTransformed[] =>
  api.map(toRegisterResponseRead)

export const toProdukItemRead = (api: ProdukItemResponse): ProdukItemTransformed => ({
    rules: api.rules,
  })

export const toProdukItemReadList = (api: ProdukItemResponse[]): ProdukItemTransformed[] =>
  api.map(toProdukItemRead)

export const toOrderRead = (api: OrderResponse): OrderTransformed => ({
    rules: api.rules,
  })

export const toOrderReadList = (api: OrderResponse[]): OrderTransformed[] =>
  api.map(toOrderRead)

export const toPaymentRead = (api: PaymentResponse): PaymentTransformed => ({
    rules: api.rules,
  })

export const toPaymentReadList = (api: PaymentResponse[]): PaymentTransformed[] =>
  api.map(toPaymentRead)

// ==== FORM MAPPERS (Frontend Form → API Payload) ====
// Transforms camelCase form data to snake_case API payloads using ApiApiField
