/**
 * ApiFieldProjector.ts
 *
 * Semantic projector from the canonical RequestField meaning algebra into the
 * final text emission boundary. Source/domain descriptors do not participate
 * in this projection.
 */

import type { CodeSink } from '../sink/CodeSink';
import type { RequestField } from '../../types/domain/request';
import type { RequestFieldMeaning, ObjectRequestField } from '../../types/domain/requestFieldMeaning';
import type { PropertyName } from '../../types/upstream/names';
import type { RequestTypesArtifact } from '../artifacts/RequestTypesArtifact';
import { relationExpand } from '../../semantic/kernel/relationalSequence';

const propertyNameText = (name: PropertyName): string => name.value.value;

export function deriveApiFieldKey(originalName: string): string {
    return originalName.toUpperCase().replace(/[^A-Z0-9]/g, '');
}

const objectFieldNames = (fields: readonly ObjectRequestField[]): readonly string[] =>
    relationExpand<ObjectRequestField, string>(
        fields,
        field => [propertyNameText(field.name), ...collectMeaningFieldNames(field.meaning)],
    );

const collectMeaningFieldNames = (meaning: RequestFieldMeaning): readonly string[] =>
    meaning.accept({
        scalar: (): readonly string[] => [],
        object: value => objectFieldNames(value.fields),
        resource: value => [value.resourceName.value.value, ...objectFieldNames(value.fields)],
        collection: value => collectMeaningFieldNames(value.element),
        resourceCollection: value => [value.resourceName.value.value, ...objectFieldNames(value.fields)],
        jsonValue: (): readonly string[] => [],
        never: (): readonly string[] => [],
        error: (): readonly string[] => [],
        union: value => relationExpand<RequestFieldMeaning, string>(value.members, member => collectMeaningFieldNames(member)),
        intersection: value => relationExpand<RequestFieldMeaning, string>(value.members, member => collectMeaningFieldNames(member)),
        generic: value => [
            ...collectMeaningFieldNames(value.base),
            ...relationExpand(value.parameters, parameter => collectMeaningFieldNames(parameter.meaning)),
        ],
    });

export function* extractFieldNamesFromField(field: RequestField): Generator<string> {
    yield propertyNameText(field.sourceName);
    yield* collectMeaningFieldNames(field.meaning);
}

export function* streamAllRequestFieldNames(artifact: RequestTypesArtifact): Generator<string> {
    const names = relationExpand(
        artifact.requestTypes,
        requestType => relationExpand(
            requestType.actions,
            action => relationExpand(action.fields, field => [
                propertyNameText(field.sourceName),
                ...collectMeaningFieldNames(field.meaning),
            ]),
        ),
    );
    yield* names;
}

export function projectApiFieldConstants(
    uniqueNames: readonly string[],
    sink: CodeSink,
    constName = 'ApiApiField',
): void {
    sink.writeLine('// Auto-generated by routesync. Do not edit manually.');
    sink.writeLine('');
    sink.writeLine(`export const ${constName} = {`);
    sink.indent();
    uniqueNames.forEach(name => sink.writeLine(`${deriveApiFieldKey(name)}: "${name}",`));
    sink.dedent();
    sink.writeLine('} as const');
}
