/**
 * ApiFieldProjector.ts
 *
 * Stream Projector for ApiApiField constant dictionary.
 * Consumes field streams in a single pass without triple-nested loops.
 *
 * @module compiler/projectors
 */

import type { CodeSink } from '../sink/CodeSink';
import type { RequestTypesArtifact, RequestField } from '../artifacts/RequestTypesArtifact';

export function deriveApiFieldKey(originalName: string): string {
    return originalName.toUpperCase().replace(/[^A-Z0-9]/g, '');
}

/**
 * Pure generator stream: extracts field names from RequestField without duck-typing.
 */
export function* extractFieldNamesFromField(field: RequestField): Generator<string> {
    yield field.originalName;
    const typeObj = field.type as unknown as {
        readonly kind?: string;
        readonly elementType?: {
            readonly properties?: readonly { readonly name?: string }[] | Map<string, unknown>;
        };
        readonly properties?: readonly { readonly name?: string }[] | Map<string, unknown>;
    };

    const target = (typeObj.kind === 'readonly_collection' || typeObj.kind === 'mutable_collection')
        ? typeObj.elementType
        : typeObj;

    if (target?.properties) {
        if (Array.isArray(target.properties)) {
            for (const prop of target.properties) {
                if (prop?.name && !prop.name.startsWith('__')) {
                    yield prop.name;
                }
            }
        } else if (typeof (target.properties as Map<string, unknown>).keys === 'function') {
            for (const key of (target.properties as Map<string, unknown>).keys()) {
                if (typeof key === 'string' && !key.startsWith('__')) {
                    yield key;
                }
            }
        }
    }
}

/**
 * Single-pass generator stream over all fields in RequestTypesArtifact.
 */
export function* streamAllRequestFieldNames(artifact: RequestTypesArtifact): Generator<string> {
    for (const rt of artifact.requestTypes) {
        for (const action of rt.actions) {
            for (const field of action.fields) {
                yield* extractFieldNamesFromField(field);
            }
        }
    }
}

/**
 * Projects ApiApiField constant block to CodeSink.
 */
export function projectApiFieldConstants(
    uniqueNames: readonly string[],
    sink: CodeSink,
    constName = 'ApiApiField'
): void {
    sink.writeLine('// Auto-generated by routesync. Do not edit manually.');
    sink.writeLine('');
    sink.writeLine(`export const ${constName} = {`);
    sink.indent();
    for (const name of uniqueNames) {
        sink.writeLine(`${deriveApiFieldKey(name)}: "${name}",`);
    }
    sink.dedent();
    sink.writeLine('} as const');
}
