// Utils
export { camelCase, camelCaseKeys, snakeCase, snakeCaseKeys } from './utils'
export { ResourceNamingConvention, toPascalCase, toCamelCase, toSnakeCase, capitalize } from './utils/resource-naming'

// Client
export { HttpClient } from './client/HttpClient'
export { Request } from './client/Request'
export { Response } from './client/Response'
export { Interceptor } from './client/Interceptor'

// Auth
export { TokenManager } from './auth/TokenManager'
export { AuthMiddleware } from './auth/AuthMiddleware'

// Routing
export { PathResolver } from './routing/PathResolver'
export { QueryBuilder } from './routing/QueryBuilder'

// Errors
export { ApiError } from './errors/ApiError'
export { ErrorHandler } from './errors/ErrorHandler'

// Types
export type { ServiceConfig, RetryConfig, AuthConfig } from './types/config'
export type { ApiResponse, PaginationMeta } from './types/response'
export type {
  RequestOptions,
  RouteDefinition,
  RouteDefinitionContract,
  RouteDefinitionDescriptorParams,
  MinimalRouteDefinitionParams,
  RouteContractConfig,
  ApiDefinition,
  ApiActionEntry,
  ApiGroupContract,
  ApiManifestContract,
  RouteMapper,
  RouteSchema,
  RouteSchemaMap,
  RouteSchemaValue,
  RouteParserSchema,
  RouteTransform,
  RouteTransformFn,
  RouteTransformMap,
  ResponseSchema,
  RouteParameterEntry,
  RouteQueryEntry,
  PayloadPropertyEntry
} from './types/request'
export {
  RouteDefinitionDescriptor,
  RequestHeaders,
  RouteParameters,
  RouteQueryParameters,
  RequestPayload,
  RouteSchemaModel,
  ResponseSchemaModel,
  RouteMapperModel,
  RouteTransformMapFactory,
  RouteSchemaMapFactory,
  RouteContractConfigFactory,
  RequestOptionsDescriptor,
  type RequestOptionsContract,
  type PhantomCarrier
} from './types/request'
// Domain & Route Contracts
export {
  AbstractCrudResourceGroupDescriptor,
  AbstractResourceGroupDescriptor,
  BROADCAST_CHANNEL_REGISTRY,
  BoundSemanticFactory,
  BroadcastChannelKind,
  CRUD_DISPATCH_REGISTRY,
  CRUD_ROLE_REGISTRY,
  CrudRole,
  DATABASE_COLUMN_KIND_REGISTRY,
  DATA_PROVENANCE_REGISTRY,
  DataProvenanceKind,
  DatabaseColumnKind,
  DatabaseColumnTypeMapper,
  ELOQUENT_CAST_REGISTRY,
  ELOQUENT_RELATION_REGISTRY,
  EloquentCastKind,
  EloquentCastMapper,
  EloquentRelationClassifier,
  EloquentRelationType,
  HOOK_KIND_REGISTRY,
  HTTP_ERROR_KIND_REGISTRY,
  HTTP_METHOD_REGISTRY,
  HTTP_STATUS_CODE_REGISTRY,
  HttpErrorKind,
  HttpMethod,
  HttpStatusCode,
  INVALIDATION_TARGET_REGISTRY,
  InlineResponseDescriptor,
  InvalidationTargetKind,
  MODEL_KEY_TYPE_REGISTRY,
  ModelAccessorMap,
  ModelControllerMap,
  ModelFieldMap,
  ModelKeyType,
  ModelKeyTypeMapper,
  ModelNodeMap,
  ModelRelationMap,
  ModelResponseDescriptor,
  ModelServiceMap,
  MutationCapability,
  PAGE_ENDPOINT_REGISTRY,
  PAGINATION_KIND_REGISTRY,
  PARAMETER_LOCATION_REGISTRY,
  POLYMORPHIC_RELATION_REGISTRY,
  PageEndpointKind,
  PaginationKind,
  PolymorphicMorphType,
  REQUEST_CONTENT_TYPE_REGISTRY,
  RESOURCE_EXPRESSION_REGISTRY,
  RESOURCE_GROUP_REGISTRY,
  RESPONSE_DESCRIPTOR_REGISTRY,
  RESPONSE_SHAPE_REGISTRY,
  ROUTE_ACTION_KIND_REGISTRY,
  ROUTE_DESCRIPTOR_REGISTRY,
  ROUTE_HANDLER_KIND_REGISTRY,
  ROUTE_PARAMETER_TYPE_REGISTRY,
  ROUTE_PAYLOAD_MODE_REGISTRY,
  ROUTE_POLICY_REGISTRY,
  RequestContentType,
  ResourceExpressionKind,
  ResourceFieldDescriptor,
  ResourceFieldExpressionFactory,
  PHP_AST_KIND_REGISTRY,
  PhpAstKind,
  ResourceGroupKind,
  ResourceResponseDescriptor,
  ResponseDescriptorBase,
  ResponseKind,
  ResponseShape,
  RouteActionKind,
  RouteDescriptorKind,
  RouteHandlerKind,
  RouteHookKind,
  RouteParameterLocation,
  RouteParameterType,
  RoutePayloadMode,
  RoutePolicyKind,
  RouteSecurityClassifier,
  SDK_RESPONSE_KIND_REGISTRY,
  SECURITY_SCHEME_REGISTRY,
  ScannedCrudResourceGroupDescriptor,
  ScannedCrudRoleDescriptor,
  ScannedCustomResourceGroupDescriptor,
  ScannedEndpointContract,
  ScannedEndpointProvenanceDescriptor,
  ScannedFlexibleCrudResourceGroupDescriptor,
  ScannedFormRequestDescriptor,
  ScannedFullCrudResourceGroupDescriptor,
  ScannedInvalidationTarget,
  ScannedPaginatedEnvelopeDescriptor,
  ScannedPolymorphicRelationDescriptor,
  ScannedReadOnlyCrudResourceGroupDescriptor,
  ScannedRequestContentTypeDescriptor,
  ScannedResourceGroupGraph,
  ScannedResourceGroupTypeSignature,
  ScannedRouteCacheInvalidationDescriptor,
  ScannedRouteExecutionSignature,
  ScannedRouteHookDescriptor,
  ScannedRouteInvalidationPayload,
  ScannedRouteRegistry,
  ScannedRouteSecurityDescriptor,
  ScannedSdkResponseResolution,
  ScannedSingletonResourceGroupDescriptor,
  SdkResponseKind,
  SecuritySchemeKind,
  SemanticModelMap,
  SemanticRelationMap,
  VALIDATION_FIELD_REGISTRY,
  VALIDATION_RULE_REGISTRY,
  ValidationFieldKind,
  ValidationRuleKind,
  ValidationRuleNodeFactory,
  ValidationRuleParser,
  VoidResponseDescriptor,
  ZOD_CONSTRAINT_REGISTRY,
  ZodSchemaReducer,
  classifyRoute,
  createEndpointContract,
  createResourceGroupGraph,
  foldValidationField,
  getManifestContractMap,
  getRouteContract,
  matchBoundSemanticNode,
  matchBroadcastChannel,
  matchCrudRole,
  matchDataProvenance,
  matchDatabaseColumnKind,
  matchEloquentCastKind,
  matchEndpointResponse,
  matchFineGrainedResourceGroup,
  matchHookKind,
  matchHttpError,
  matchHttpMethod,
  matchHttpStatusCode,
  matchInvalidationTarget,
  matchModelKeyType,
  matchPageEndpoint,
  foldPhpAstNode,
  matchFieldNode,
  matchPaginatedEnvelope,
  matchPaginationKind,
  matchPhpAstKind,
  matchPhpAstNode,
  matchPolymorphicMorphType,
  matchPolymorphicRelation,
  matchRelation,
  matchRelationCardinality,
  matchRelationType,
  matchRequestContentType,
  matchResourceExpression,
  matchResourceFieldExpression,
  matchResourceGroup,
  matchResponse,
  matchResponseShape,
  matchRoute,
  matchRouteActionKind,
  matchRouteExecutionSignature,
  matchRouteHandler,
  matchRouteHookKind,
  matchRouteParameter,
  matchRouteParameterType,
  matchRoutePayloadMode,
  matchRoutePolicy,
  matchRouteSecurity,
  matchRule,
  matchSdkResponse,
  matchSdkResponseResolution,
  matchUnifiedResourceGroup,
  matchValidationField,
  matchValidationRule
} from './types/route'

export type {
  AbsentMutation,
  ActionDefinition,
  AnyCrudRoleDescriptor,
  AnyInvalidationTarget,
  AnyPaginatedEnvelopeDescriptor,
  AnyPolymorphicRelationDescriptor,
  AnyResourceFieldExpression,
  AnyRouteExecutionSignature,
  AnyRouteHookDescriptor,
  AnyRouteParameter,
  AnySdkResponseResolution,
  AnyValidationRuleNode,
  ArrayValidationFieldNode,
  ArrayValidationRuleNode,
  AuthResourceInvalidationTarget,
  AvailableMutation,
  BaseCrudParams,
  BaseCrudResourceGroupDescriptor,
  BaseCrudRoleDescriptor,
  BasePaginatedEnvelopeDescriptor,
  BasePolymorphicRelationDescriptor,
  BaseRequestContentTypeDescriptor,
  BaseResourceGroupDescriptor,
  BaseResourceGroupParams,
  BaseResourceGroupTypeSignature,
  BaseRouteExecutionSignature,
  BaseRouteHandlerDescriptor,
  BaseRouteHookDescriptor,
  BaseValidationRuleNode,
  BetweenValidationRuleNode,
  BooleanValidationRuleNode,
  BoundBinaryNode,
  BoundConditionalNode,
  BoundMethodCallNode,
  BoundModelColumnNode,
  BoundPrimitiveNode,
  BoundPropertyChainNode,
  BoundRelationNode,
  BoundSemanticKind,
  BoundSemanticNode,
  BoundSemanticVisitor,
  BoundStepEdge,
  BoundTernaryNode,
  BoundUnknownNode,
  BroadcastChannelDescriptor,
  BroadcastChannelRegistry,
  BroadcastChannelSpecification,
  BroadcastChannelVisitor,
  ClassifiedDomainGraph,
  ClosureHandlerDescriptor,
  CollectionRelationDescriptor,
  ConditionalWrapperKind,
  ConstraintHandler,
  ConstraintRegistry,
  ControllerActionHandlerDescriptor,
  CreateCrudRoleDescriptor,
  CrudEndpointsTrait,
  CrudResourceGroupDescriptor,
  CrudResourceGroupDescriptorParams,
  CrudRoleRegistry,
  CrudRoleSpecification,
  CrudRoleVisitor,
  CursorPaginatedEnvelopeDescriptor,
  CustomCrudRoleDescriptor,
  CustomResourceGroupDescriptor,
  CustomResourceGroupDescriptorParams,
  CustomTypeSignature,
  CustomValidationRuleNode,
  DataProvenanceKindRegistry,
  DataProvenanceKindSpecification,
  DataProvenanceVisitor,
  DatabaseColumnKindRegistry,
  DatabaseColumnKindSpecification,
  DatabaseColumnKindVisitor,
  DateValidationRuleNode,
  DeleteCrudRoleDescriptor,
  DeletionRouteDescriptor,
  DomainConfigEntry,
  DomainDefinitionEntry,
  DomainIntentConfig,
  DomainOperationEntry,
  EloquentCastKindRegistry,
  EloquentCastKindSpecification,
  EloquentCastKindVisitor,
  EloquentRelationCardinality,
  EloquentRelationDescriptor,
  EloquentRelationRegistry,
  EloquentRelationTypeVisitor,
  EmailValidationRuleNode,
  EndpointContract,
  EndpointErrorResponseContract,
  EndpointProvenanceDescriptor,
  EndpointRequestBodyContract,
  EndpointRequestContract,
  EndpointResponseContract,
  EndpointResponseVisitor,
  EndpointSuccessResponseContract,
  ExhaustiveFineGrainedResourceGroupVisitor,
  ExistsValidationRuleNode,
  ExtractRule,
  FileValidationRuleNode,
  FlexibleCrudParams,
  FlexibleCrudResourceGroupDescriptor,
  FlexibleCrudTypeSignature,
  FlexibleMutationEndpointsTrait,
  FormRequestDescriptor,
  FrontendConfig,
  FullCrudParams,
  FullCrudResourceGroupDescriptor,
  FullCrudTypeSignature,
  GetCollectionRouteDescriptor,
  GetItemRouteDescriptor,
  GroupAliasEntry,
  HeaderDeclaration,
  HeaderParameterDescriptor,
  HookKindRegistry,
  HookKindSpecification,
  HttpErrorKindRegistry,
  HttpErrorKindSpecification,
  HttpErrorResponseDescriptor,
  HttpErrorVisitor,
  HttpMethodRegistry,
  HttpMethodSpecification,
  HttpMethodVisitor,
  HttpStatusCodeCategory,
  HttpStatusCodeRegistry,
  HttpStatusCodeSpecification,
  HttpStatusCodeVisitor,
  ImageValidationRuleNode,
  InValidationRuleNode,
  IndexCrudRoleDescriptor,
  InfiniteQueryHookDescriptor,
  InlineResponseDescriptorParams,
  InvalidationTarget,
  InvalidationTargetRegistry,
  InvalidationTargetSpecification,
  InvalidationTargetVisitor,
  InvokableControllerHandlerDescriptor,
  ItemEndpointContract,
  ItemEndpointRequestContract,
  JsonRequestContentTypeDescriptor,
  KnownHttpStatusCode,
  LaravelForbiddenError,
  LaravelNotFoundError,
  LaravelServerError,
  LaravelUnauthorizedError,
  LaravelValidationError,
  LengthAwarePaginatedEnvelopeDescriptor,
  MappedSdkResponseResolution,
  MaxValidationRuleNode,
  MinValidationRuleNode,
  ModelAccessorEntry,
  ModelAccessorInfo,
  ModelControllerEntry,
  ModelFieldEntry,
  ModelFieldInfo,
  ModelKeyTypeRegistry,
  ModelKeyTypeSpecification,
  ModelKeyTypeVisitor,
  ModelNodeEntry,
  ModelRelationEntry,
  ModelRelationInfo,
  ModelResponseParams,
  ModelServiceEntry,
  MorphManyRelationDescriptor,
  MorphOneRelationDescriptor,
  MorphToManyRelationDescriptor,
  MorphToRelationDescriptor,
  MorphedByManyRelationDescriptor,
  MultipartRequestContentTypeDescriptor,
  MutationHookDescriptor,
  MutationRouteDescriptor,
  NoPayloadExecutionSignature,
  NoneRequestContentTypeDescriptor,
  NullableValidationRuleNode,
  NumberValidationRuleNode,
  ObjectValidationFieldNode,
  OptionalPayloadExecutionSignature,
  OptionalValidationRuleNode,
  PageConfig,
  PageEndpointDescriptor,
  PageEndpointKindRegistry,
  PageEndpointKindSpecification,
  PageEndpointVisitor,
  PageMetaEntry,
  PagePropEntry,
  PaginatedEnvelopeDescriptor,
  PaginatedEnvelopeVisitor,
  PaginationKindRegistry,
  PaginationKindSpecification,
  ParentDetailInvalidationTarget,
  ParentListInvalidationTarget,
  ParsedAccessor,
  ParsedCast,
  ParsedChannel,
  ParsedColumn,
  ParsedModel,
  ParsedRelation,
  ParsedResource,
  ParsedRoute,
  PathParameterDescriptor,
  PhpAstCategory,
  PhpAstFolder,
  PhpAstKindRegistry,
  PhpAstKindSpecification,
  PhpAstNode,
  PhpAstVisitor,
  FieldNodeVisitor,
  PolymorphicRelationDescriptor,
  PolymorphicRelationRegistry,
  PolymorphicRelationSpecification,
  PolymorphicRelationVisitor,
  PresenceBroadcastChannelDescriptor,
  PrivateBroadcastChannelDescriptor,
  ProvenanceSourceRef,
  PublicBroadcastChannelDescriptor,
  QueryHookDescriptor,
  QueryParameterDescriptor,
  RateLimitDescriptor,
  RawSdkResponseResolution,
  ReadOnlyCrudParams,
  ReadOnlyCrudResourceGroupDescriptor,
  ReadOnlyCrudTypeSignature,
  RelationCardinalityDescriptor,
  RelationCardinalityVisitor,
  RequestContentTypeDescriptor,
  RequestContentTypeRegistry,
  RequestContentTypeSpecification,
  RequestContentTypeVisitor,
  RequiredPayloadExecutionSignature,
  RequiredValidationRuleNode,
  ResourceAssignment,
  ResourceExpressionCategory,
  ResourceExpressionRegistry,
  ResourceExpressionSpecification,
  ResourceFieldExpression,
  ResourceFieldExpressionVisitor,
  ResourceFieldKind,
  ResourceGroupDescriptor,
  ResourceGroupGraph,
  ResourceGroupIdentityTrait,
  ResourceGroupLoweringTrait,
  ResourceGroupQueryKeysTrait,
  ResourceGroupRegistry,
  ResourceGroupSpecification,
  ResourceGroupTypeSignature,
  ResourceGroupTypeSignatureParams,
  ResourceGroupVisitor,
  ResourceGroupVisitorCapability,
  ResourceResponseParams,
  ResourceRouteGroup,
  ResponseDescriptorRegistry,
  ResponseKindSpecification,
  ResponseMetadata,
  ResponseShapeRegistry,
  ResponseShapeSpecification,
  ResponseShapeVisitor,
  ResponseVisitor,
  RouteActionKindRegistry,
  RouteActionKindSpecification,
  RouteActionKindVisitor,
  RouteAttributeEntry,
  RouteBindingContract,
  RouteCacheInvalidationDescriptor,
  RouteCapabilityContract,
  RouteClassifier,
  RouteCollectionRegistry,
  RouteDescriptor,
  RouteDescriptorRegistry,
  RouteExecutionSignature,
  RouteExecutionSignatureVisitor,
  RouteHandlerDescriptor,
  RouteHandlerKindRegistry,
  RouteHandlerKindSpecification,
  RouteHandlerVisitor,
  RouteHookDescriptor,
  RouteHookKindVisitor,
  RouteIdentityContract,
  RouteKindSpecification,
  RouteManifest,
  RouteMessageEntry,
  RouteParameter,
  RouteParameterDescriptor,
  RouteParameterKind,
  RouteParameterLocationRegistry,
  RouteParameterLocationSpecification,
  RouteParameterSpecification,
  RouteParameterTypeRegistry,
  RouteParameterTypeSpecification,
  RouteParameterTypeVisitor,
  RouteParameterVisitor,
  RoutePayloadModeRegistry,
  RoutePayloadModeSpecification,
  RoutePolicyDescriptor,
  RoutePolicyKindRegistry,
  RoutePolicyKindSpecification,
  RoutePolicyVisitor,
  RouteProvenanceContract,
  RouteQueryParameter,
  RouteResponseAnalysis,
  RouteSchemaPayload,
  RouteSecurityDescriptor,
  RouteSecurityVisitor,
  RouteValidationRuleEntry,
  RouteVisitor,
  ScalarValidationFieldNode,
  ScannedPaginatedEnvelopeParams,
  ScannedPolymorphicRelationParams,
  ScannedRouteSecurityParams,
  SdkResponseKindRegistry,
  SdkResponseKindSpecification,
  SdkResponseResolution,
  SdkResponseResolutionVisitor,
  SecuritySchemeRegistry,
  SecuritySchemeSpecification,
  SelfListInvalidationTarget,
  SemanticModelEntry,
  SemanticRelationEntry,
  ShowCrudRoleDescriptor,
  SingleRelationDescriptor,
  SingletonResourceGroupDescriptor,
  SingletonResourceGroupDescriptorParams,
  SingletonTypeSignature,
  SqlTypeFamily,
  StrictMutationEndpointsTrait,
  StringValidationRuleNode,
  UnifiedCrudResourceGroupVisitor,
  UniqueValidationRuleNode,
  UpdateCrudRoleDescriptor,
  UrlEncodedRequestContentTypeDescriptor,
  UrlValidationRuleNode,
  UuidValidationRuleNode,
  ValidatedAndMappedSdkResponseResolution,
  ValidatedSdkResponseResolution,
  ValidationFieldFolder,
  ValidationFieldNode,
  ValidationFieldRegistry,
  ValidationFieldSpecification,
  ValidationFieldVisitor,
  ValidationRuleCategory,
  ValidationRuleNode,
  ValidationRuleRegistry,
  ValidationRuleSpecification,
  ValidationRuleVisitor,
  VoidSdkResponseResolution,
  ZodNode
} from './types/route'

// Semantic Kernel Types & IR
export { SemanticResolutionKernel as SemanticKernelV2Impl } from './semantic/SemanticResolutionKernel'
export { SemanticResolutionKernel } from './semantic/SemanticResolutionKernel'
export type { ModelNode as SemanticModelNode, ResolverMeta, ResolutionContext, ResolverPlugin } from './semantic/types'

export {
  IRHintsFactory,
  IRRawNodeDescriptor,
  ModelCastCollection,
  SemanticFieldSet,
  SourceRefFactory,
  ZodObjectShape,
  createSourceColumnNumber,
  createConfidenceScore,
  createModelNodeName,
  createServiceNodeName,
  createControllerNodeName
} from './types/semantic'

export type {
  AccessKind,
  ControllerAction,
  ControllerNode,
  ExecutionLayer,
  GeneratedSDKModule,
  IRContext,
  IRFrameworkContext,
  IRHintPattern,
  IRHints,
  IRKind,
  IRMeta,
  IRRawNode,
  JsonMemberResolution,
  JsonObjectResolution,
  ModelCastEntry,
  ModelNode,
  ReactQueryHooks,
  RequestContract,
  ResolutionStatus,
  ResponseContract,
  RouteParamTypeMap,
  RouteQueryTypeMap,
  SemanticFieldEntry,
  SemanticIRNode,
  SemanticKernelV2,
  SemanticNode,
  SemanticRelation,
  SemanticResolution,
  SemanticType,
  ServiceDependency,
  ServiceGraph,
  ServiceNode,
  SourceContext,
  SourceRef,
  SemanticTraceNode,
  ZodAST,
  ZodArrayNode,
  ZodBooleanNode,
  ZodContract,
  ZodLiteralNode,
  ZodNumberNode,
  ZodObjectNode,
  ZodOptionalNode,
  ZodPropertyEntry,
  ZodStringNode,
  ZodUnionNode,
  ZodUnknownNode
} from './types/semantic'
export type {
  TSEmitModule,
  TSFileUnit,
  TSExport,
  ImportStatement,
  TSInterfaceField,
  TSInterface,
  TSFunction,
  TSConst
} from './types/emit'
export { ServiceGraphBuilder } from './graph/ServiceGraphBuilder'

// IR v3 (CompilerRoadmap.md Stage 2)
export { buildSemanticIRNode, computeStableHash, IRNodeRegistry } from './ir/buildIRNode'
export type { BuildIRNodeInput } from './ir/buildIRNode'

// Unified FieldNode model (compiler/CompilerBacklog.md H1/H3 follow-up) — phase 1 of 3
export type {
  BaseField,
  ParsedField,
  UnknownField,
  LiteralField,
  VariableField,
  PropertyAccessField,
  ArrayAccessField,
  FunctionCallField,
  MethodCallField,
  NullsafeMethodCallField,
  VariableCallField,
  StaticMethodCallField,
  StaticPropertyAccessField,
  StaticConstantField,
  UnaryExpressionField,
  BinaryExpressionField,
  TypeCastField,
  TernaryField,
  NullsafePropertyAccessField,
  NewInstanceField,
  ClosureField,
  ArrowFunctionField,
  FieldArgument,
  FieldReturnExpression,
  FieldStatement,
  FieldNode,
  FieldEntryNode,
  FieldArrayKey,
  ArrayField,
  type FieldBinding,
  type ResolvedFieldBinding,
  type UnresolvedFieldBinding,
  RouteDef,
  RouteDefContract,
  ResourceDef,
  ResourceDefContract,
  RoutePath,
  HttpVerb,
  ColumnDefinitionContract,
  ModelRelationDefinitionContract,
  ModelSemanticDefinitionContract,
  ModelSemanticDefinition
} from './types/field';
export { createFieldBinding } from './types/domain/fieldBinding';

export {
  RouteDefDescriptor,
  ResourceDefDescriptor,
  createRoutePath,
  createHttpVerb
} from './types/field';

export type {
  ResponseDescriptorContract,
  JsonTransportContract,
  BinaryTransportContract,
  StreamTransportContract,
  RedirectTransportContract,
  EmptyTransportContract
} from './compiler/ir/response/responseDescriptorContract';

export type {
  ResponseFieldContract,
  PrimitiveResponseFieldContract,
  ObjectResponseFieldContract,
  ArrayResponseFieldContract,
  VariableResponseFieldContract,
  PropertyAccessResponseFieldContract
} from './compiler/generators/contract-generation/response-field/types';

export type {
  SemanticRelationContract,
  BelongsToManyRelationContract,
  DirectRelationContract,
  MorphRelationContract
} from './types/semantic';

// SymbolTable — O(1) model/member lookup (roadmap: next after ResolverMeta unification)
export { SymbolTable, ModelSymbol } from './semantic/SymbolTable'

// RouteSync Compiler Core v6.0
export * as v6 from './compiler'

// ResponseArtifact and related types (SSOT for response analysis)
export {
  ResponseArtifact,
  ResponseArtifactBuilder,
  InferenceMethod,
  TransportKind
} from './compiler/ir/ResponseArtifact'
export { RouteManifestArtifact } from './compiler/artifacts/RouteManifestArtifact'
export { ResponseAnalysisArtifact } from './compiler/artifacts/ResponseAnalysisArtifact'
export type {
  ResponseDescriptor,
  ResponseBody,
  ResourceBody,
  ModelBody,
  ObjectBody,
  PrimitiveBody,
  ConfidenceScore,
  ObjectSchema,
  ObjectSchemaProperty,
  PropertyType,
  PropertyDescriptor,
  ModelAttribute
} from './compiler/ir/ResponseArtifact'

export {
  type TokenType,
  type TokenDescriptor,
  type SourceOffset,
  type SourceLineNumber,
  type AstIdentifier,
  createSourceOffset,
  createSourceLineNumber,
  createAstIdentifier,
  type PhpLiteralValue,
  type PhpAstValue,
  type PhpAstValueVisitor,
  type PhpMicroAstVisitor,
  matchPhpAstValue,
  type PhpArrayEntry,
  type ParsedPhpArrayResult,
  PhpAstFactory,
  SourceStream,
  tokenizePhpSource,
  parsePhpArray,
  classifyAstTokens,
  classifyAstValue,
  LaravelSourceLexer
} from './compiler/scanner/LaravelSourceLexer'

export {
  StaticLaravelScanner,
  collectPhpFiles,
  ChannelScanner,
  ControllerScanner,
  ResourceScanner,
  FormRequestScanner,
  ModelScanner,
  RouteScanner,
  InvalidationResolver,
  resolvePrimitiveKind,
  resolveRouteDomain,
  ValidationRuleFieldLowerer,
  RequestTypeDeriver,
  deriveRequestTypes,
  TypeDeriver
} from './compiler/scanner/StaticLaravelScanner'
export { IdentifierCase, extractClassBasename, inferLaravelTableName } from './utils/resource-naming'
export {
  ScannedObjectProperty,
  PrimitiveKind,
  PrimitiveType,
  JsonValueType,
  ObjectType,
  ReferenceType,
  UnionType,
  IntersectionType,
  ReadonlyCollectionType,
  MutableCollectionType,
  OptionalType,
  NullableType,
  CollectionKind
} from './compiler/types/SemanticType'

export {
  ResolvedPhpType,
  PrimitivePhpType,
  EloquentModelPhpType,
  ResourceWrapperPhpType,
  VoidPhpType,
  UnknownPhpType,
  matchResolvedPhpType
} from './compiler/types/ResolvedPhpType'
export type { ResolvedPhpTypeVisitor } from './compiler/types/ResolvedPhpType'

export {
  SemanticTypeDeriver,
  SemanticDerivationContext
} from './compiler/scanner/subscanners/SemanticTypeDeriver'


export { ContractActionGenerator } from './compiler/generators/contract-generation/ContractActionGenerator'
export { FormActionGenerator } from './compiler/generators/form-generation/FormActionGenerator'
export { defaultTypeResolver } from './compiler/domain/common/ResponseFieldLowering'
export {
  ResolvedObjectType,
  ResolvedOptionalType,
  ResolvedCollectionType,
  ResolvedPrimitiveType,
  ResolvedReferenceType,
  ResolvedNullableType,
  ResolvedUnionType,
  ResolvedIntersectionType,
  ResolvedUnknownType,
  ResolvedSemanticTypeKind,
  RESOLVED_SEMANTIC_TYPE_REGISTRY,
  matchResolvedSemanticType
} from './compiler/domain/common/ResolvedSemanticType'
export type {
  ResolvedSemanticType,
  ResolvedPrimitiveKind,
  ObjectKind,
  ResolvedProperty,
  ResolvedObjectIdentity,
  ResolvedSemanticTypeSpecification,
  ResolvedSemanticTypeRegistry,
  ResolvedSemanticTypeVisitor
} from './compiler/domain/common/ResolvedSemanticType'

// Compiler Diagnostics (Stage 2: Validation Gatekeeper)
export {
  DiagnosticBag,
  CompilerValidationError,
  DiagnosticCategory,
  DIAGNOSTIC_CATEGORY_REGISTRY,
  matchDiagnosticCategory
} from './compiler/diagnostics'
export type {
  Diagnostic,
  DiagnosticSeverity,
  DiagnosticFix,
  TextEdit,
  DiagnosticCategorySpecification,
  DiagnosticCategoryRegistry,
  DiagnosticCategoryVisitor
} from './compiler/diagnostics'
// Compiler Passes (Pure Transforms & Output Lowerers)
export { lowerTypeScriptArtifact } from './compiler/passes/TypeScriptGeneratorPass'
export { lowerFormArtifact } from './compiler/passes/FormGeneratorPass'
export { lowerContractArtifact } from './compiler/passes/ContractGeneratorPass'
export { lowerApiFieldArtifact } from './compiler/passes/ApiFieldGeneratorPass'
export { lowerMapperArtifact } from './compiler/passes/MapperGeneratorPass'
export {
  lowerReadTypesOutput,
  lowerFormTypesOutput,
  lowerContractsOutput,
  lowerApiFieldsOutput,
  lowerMappersOutput,
  type CompilerOutput,
  type FormOutput,
  type ContractOutput,
  type ApiFieldOutput,
  type MapperOutput
} from './compiler/passes/outputLowerers'

// Compiler Scanner Descriptors & Resolvers
export {
  LaravelValidationType,
  type LaravelValidationConstraint,
  type ResourceExpressionDescriptor,
  type StaticLaravelScannerOptions,
  ScannedRouteValidationRuleEntry,
  type ScannedRouteValidationRuleParams,
  ScannedRouteSchemaPayload,
  type ScannedRouteSchemaParams,
  ScannedScalarFieldNode,
  type ScannedScalarFieldParams,
  ScannedObjectFieldNode,
  type ScannedObjectFieldParams,
  ScannedArrayFieldNode,
  type ScannedArrayFieldParams,
  ValidationTreeBuilder,
  buildValidationTree,
  ScannedRouteDescriptor,
  ScannedRouteParameterDescriptor,
  ScannedRouteQueryParameterDescriptor,
  ScannedRoutePolicyDescriptor,
  ScannedRateLimitDescriptor,
  ScannedHttpErrorResponseDescriptor,
  type ScannedRouteCompleteContracts,
  type ScannedRouteConstructorInput,
  type ScannedRouteParams,
  type ScannedRouteParameterParams,
  type ScannedRouteQueryParameterParams,
  type ScannedRoutePolicyParams,
  type ScannedRateLimitParams,
  type ScannedHttpErrorResponseParams,
  ScannedResourceFieldDescriptor,
  type ScannedResourceFieldParams,
  ScannedResourceDescriptor,
  type ScannedResourceParams,
  ScannedModelColumnDescriptor,
  ScannedModelCastDescriptor,
  ScannedModelRelationDescriptor,
  ScannedModelAccessorDescriptor,
  ScannedModelDescriptor,
  type ScannedModelColumnParams,
  type ScannedModelCastParams,
  type ScannedModelRelationParams,
  type ScannedModelAccessorParams,
  type ScannedModelParams,
  ScannedBroadcastChannelDescriptor,
  type ScannedBroadcastChannelParams,
  compileBroadcastRuntimePattern,
  ScannedFormFieldDescriptor,
  type ScannedFormFieldParams,
  ScannedFormActionDescriptor,
  type ScannedFormActionParams,
  ScannedControllerActionDescriptor,
  type ScannedControllerActionParams,
  ScannedRequestTypeDescriptor,
  type ScannedRequestTypeParams,
  type ControllerActionInfo,
  buildRequestTypeWithActions,
  ScannedResourceRouteGroupDescriptor,
  type ScannedResourceRouteGroupParams,
  ScannedRouteManifestDescriptor,
  type ScannedRouteManifestParams
} from './compiler/scanner/descriptors'

export {
  type RouteDomainResolutionContext,
  RouteDomainResolver,
  RouteCrudClassifier,
  type RouteSecurityResolution,
  RouteSecurityResolver,
  type RouteBoundaryContract,
  type RouteBoundaryOptions,
  RouteBoundaryContractFactory,
  RouteBoundaryAdapter
} from './compiler/scanner/resolvers'
export { ModelSymbolTable, OriginModelSymbol } from './compiler/scanner/symbols/ModelSymbolTable'
export { SemanticResourceBinder } from './compiler/scanner/binders/SemanticResourceBinder'
export { ResourceModelResolver } from './compiler/scanner/resolvers/resource'
export {
  type ResourceModelBinding,
  type ResourceModelBindingSource,
  type MonoModelBinding,
  type PolyModelBinding,
  type UnbackedDtoBinding,
  ResourceModelBindingFactory,
  matchResourceModelBinding
} from './compiler/scanner/symbols/resource'

// Contract IR & Semantic Types
export {
  ResolvedSemanticTypeFactory,
  matchResolvedSemanticTypeIR,
  TypeIRUtils,
  createEndpointId,
  createResourceId,
  createRequestId,
  createHttpHeaderName
} from './types/ir'
export type {
  ContractIR,
  ResourceIR,
  ResourceVariantIR,
  RequestIR,
  EndpointIR,
  TypeIR,
  PrimitiveSemanticTypeIR,
  ResourceSemanticTypeIR,
  ModelSemanticTypeIR,
  ObjectSemanticTypeIR,
  ArraySemanticTypeIR,
  UnionSemanticTypeIR,
  LiteralSemanticTypeIR,
  ResolvedSemanticType as ResolvedSemanticTypeIR,
  ResolvedSemanticTypeVisitor as ResolvedSemanticTypeIRVisitor,
  EndpointId,
  ResourceId,
  RequestId,
  HttpHeaderName
} from './types/ir'
export { OptimizedContractIRBuilder } from './ir/ContractIRBuilder'

// Utilities & Type Guards
export {
  isObject,
  hasProperty,
  isString,
  isNumber,
  isBoolean,
  isArray
} from './utils/guards'

// Code Sinks & Catamorphic Domain Projectors
export {
  type CodeSink,
  type SinkMetadata,
  MemoryCodeSink
} from './compiler/sink'

export {
  type DomainProjector,
  type ProjectorOutput,
  deriveApiFieldKey,
  extractFieldNamesFromField,
  streamAllRequestFieldNames,
  projectApiFieldConstants,
  type FormProjectorDependencies,
  FormModelProjector,
  ContractProjector,
  ReadModelProjector,
  MapperProjector
} from './compiler/projectors'

// Schema Morphisms & Functor Composition (Level 7 Architecture)
export {
  TypeWrapperKind,
  type IdentityWrapper,
  type NullableWrapper,
  type CollectionWrapper,
  type PaginatedWrapper,
  type TypeWrapper,
  TypeWrapperFactory,
  DomainCarrierKind,
  type ScalarCarrier,
  type ModelCarrier,
  type ResourceCarrier,
  type StructuralCarrier,
  type DomainCarrier,
  type SchemaFieldMorphism,
  DomainCarrierFactory,
  type WrapperAlgebra,
  type CarrierVisitor,
  matchDomainCarrier,
  foldTypeWrapper,
} from './types/domain'


export { SemanticTypeResolver } from './compiler/domain/common/SemanticTypeResolver'
export { toTypeScriptTypeExpression } from './compiler/domain/common/ts-lowerer/typeScriptNodeLowerer'
export { toZodSchemaExpression } from './compiler/domain/common/ZodSchemaLowerer'
