/**
 * hookSourceLowerer.ts
 *
 * Emits full hooks.ts and routesync.runtime.ts source streams.
 *
 * @module cli/generators/hooks
 */

import type { RouteManifest } from '@routesync/core';
import type { ClassifiedDomainGraph, ClassifiedRoute } from '../route-classifier';
import { lowerGroupHookConfig, addRouteInvalidations } from './hookConfigLowerer';

export function* lowerRuntimeManifestSource(manifest: RouteManifest): Iterable<string> {
  yield `// Auto-generated by routesync. Do not edit manually.`;
  yield ``;
  yield `export const runtimeManifest = {`;
  yield `  resources: {},`;
  yield `  domains: ${JSON.stringify(manifest.frontend?.domains || {}, null, 2)},`;
  yield `  intents: {}`;
  yield `} as const`;
  yield ``;
}

export function* lowerHookSource(
  graph: ClassifiedDomainGraph<ClassifiedRoute>,
  _manifest: RouteManifest
): Iterable<string> {
  const importedTypes = new Set<string>();
  const contractImportedTypes = new Set<string>();

  for (const group of graph.resourceGroupGraph.all) {
    for (const t of group.types.importedTypes) importedTypes.add(t);
    for (const t of group.types.contractImportedTypes) contractImportedTypes.add(t);
  }

  yield `// Auto-generated by routesync. Do not edit manually.`;
  yield ``;
  yield `import { defineHooks, useAggregateCollectionIntent } from 'routesync/react'`;
  yield `import { api } from './api'`;
  yield `import { QueryKey } from './query-key'`;
  yield `import { runtimeManifest } from './routesync.runtime'`;

  if (importedTypes.size > 0) {
    yield `import type {`;
    for (const t of Array.from(importedTypes).sort()) {
      yield `  ${t},`;
    }
    yield `} from './types/index'`;
  }

  if (contractImportedTypes.size > 0) {
    yield `import type {`;
    for (const t of Array.from(contractImportedTypes).sort()) {
      yield `  ${t},`;
    }
    yield `} from './contract/api-schema'`;
  }

  yield ``;
  yield `export const typeOf = <T>() => ({} as T)`;
  yield ``;
  yield `const baseHooks = defineHooks({`;

  for (const group of graph.resourceGroupGraph.all) {
    yield* lowerGroupHookConfig(group, addRouteInvalidations);
  }

  yield `}, runtimeManifest)`;
  yield ``;
  yield `export const hooks = baseHooks`;
  yield ``;

  for (const group of graph.resourceGroups) {
    const { groupName, titleName } = group;
    const primaryRoute = group.primaryRoute;
    yield `/**`;
    yield ` * @provenance ${primaryRoute.contract.provenance.summary}`;
    if (primaryRoute.contract.provenance.route?.file) {
      yield ` * @see ${primaryRoute.contract.provenance.route.file}#L${primaryRoute.contract.provenance.route.line}`;
    }
    yield ` */`;
    yield `export const use${titleName} = hooks.${groupName}`;
  }

  yield ``;
  yield `export * from './query-key'`;
  yield ``;
}
