// Generated by TypeScriptGenerator
// File: types/api-read.ts

export interface CategoryTransformed {
    id: number;
    nama: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderTransformed {
    id: number;
    userId: number;
    totalHarga: number;
    status: string;
    orderNumber: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderAmountTransformed {
    id: number;
    orderId: number;
    subtotalMinor: number;
    shippingMinor: number;
    discountMinor: number;
    taxMinor: number;
    totalMinor: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderDetailTransformed {
    id: number;
    orderId: number;
    produkItemId: number;
    qty: number;
    harga: number;
    createdAt: datetime;
    updatedAt: datetime;
    banana: string;
    potato: number;
    flyingDog: number;
}

export interface OrderFinancialTransformed {
    id: number;
    orderId: number;
    financialStatus: string;
    refundedAt: datetime;
    refundReason: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderFulfillmentTransformed {
    id: number;
    orderId: number;
    fulfillmentStatus: string;
    processingAt: datetime;
    shippedAt: datetime;
    completedAt: datetime;
    canceledAt: datetime;
    cancelReason: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderPromotionTransformed {
    id: number;
    orderId: number;
    promoCodeId: number;
    promoCode: string;
    discountMinor: number;
    metadata: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface OrderShippingTransformed {
    id: number;
    orderId: number;
    nama: string;
    telepon: string;
    alamat: string;
    kota: string;
    kodePos: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface PaymentTransformed {
    id: number;
    orderId: number;
    metode: string;
    status: string;
    paidAt: datetime;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface PaymentAmountTransformed {
    id: number;
    paymentId: number;
    currencyCode: string;
    amountMinor: number;
    feeMinor: number;
    netAmountMinor: number;
    refundAmountMinor: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface PaymentDetailTransformed {
    id: number;
    paymentId: number;
    detail: string;
    payloadHash: string;
    payloadReceivedAt: datetime;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface PaymentGatewayTransformed {
    id: number;
    paymentId: number;
    provider: string;
    providerTxnId: string;
    idempotencyKey: string;
    gatewayStatus: string;
    gatewayCode: string;
    gatewayMessage: string;
    authorizedAt: datetime;
    capturedAt: datetime;
    failedAt: datetime;
    refundedAt: datetime;
    reconciledAt: datetime;
    reconciliationBatchId: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface ProductReviewTransformed {
    id: number;
    produkItemId: number;
    userId: number;
    rating: number;
    title: string;
    comment: string;
    isVerifiedPurchase: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface ProdukItemTransformed {
    id: number;
    nama: string;
    deskripsi: string;
    categoryId: number;
    harga: number;
    stok: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface ProdukItemFrontendTransformed {
    id: number;
    produkItemId: number;
    gambar: string;
    rating: number;
    jumlahReview: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface PromoCodeTransformed {
    id: number;
    code: string;
    discountType: string;
    discountValue: number;
    maxDiscountMinor: number;
    minOrderMinor: number;
    usageLimit: number;
    usedCount: number;
    isActive: number;
    startsAt: datetime;
    endsAt: datetime;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface SocialAccountTransformed {
    id: number;
    userId: number;
    provider: string;
    providerUserId: string;
    email: string;
    avatarUrl: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface UserTransformed {
    id: number;
    name: string;
    email: string;
    password: string;
    role: string;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface WishlistTransformed {
    id: number;
    userId: number;
    produkItemId: number;
    createdAt: datetime;
    updatedAt: datetime;
}

export interface RegisterResponseTransformed {
    success: boolean;
    message: string;
    data: string;
}

export interface OrderDetailResourceTransformed {
    id: number;
    produkItemId: number;
    produkId: number;
    produkNama: string;
    produkGambar: string;
    produkImageUrl: string;
    qty: number;
    harga: number;
    subtotal: unknown;
}

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
    id: number;
    status: string;
    totalHarga: number;
    invoiceNumber: string;
    paymentStatus: unknown;
    financialStatus: unknown;
    fulfillmentStatus: unknown;
    subtotalMinor: number;
    discountMinor: number;
    shippingMinor: number;
    taxMinor: number;
    totalHargaMinor: number;
    items: unknown;
    promotionCode: unknown;
    promotionDiscountMinor: unknown;
    shippingNama: unknown;
    shippingTelepon: unknown;
    shippingAlamat: unknown;
    shippingKota: unknown;
    shippingKodePos: unknown;
    createdAt: unknown;
}

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
    id: number;
    orderId: number;
    invoiceNumber: string;
    metode: string;
    detail: string;
    status: string;
    paidAt: string;
    provider: string;
    providerTxnId: string;
    gatewayStatus: string;
    amountMinor: number;
    refundAmountMinor: string;
    items: unknown;
    promotionCode: unknown;
    promotionDiscountMinor: unknown;
    gatewayName: unknown;
    gatewayOrderId: unknown;
    gatewayToken: unknown;
    gatewayRedirectUrl: unknown;
    totalHarga: unknown;
}

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
    id: number;
    nama: string;
    deskripsi: string;
    image: string;
    imageUrl: string;
    categoryId: number;
    categoryName: unknown;
    harga: number;
    stok: number;
    rating: number;
    reviewCount: number;
}

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]
