// Auto-generated by routesync. Do not edit manually.

export interface OrderDetailResourceTransformed {
            readonly id: unknown
  readonly produkItemId: unknown
  readonly produk: {
  id: unknown;
  nama: unknown;
  gambar: unknown;
  image_url: string;
}
  readonly qty: unknown
  readonly harga: unknown
  readonly subtotal: number
        }

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
            readonly id: unknown
  readonly status: unknown
  readonly totalHarga: unknown
  readonly invoiceNumber: unknown
  readonly paymentStatus: string
  readonly financialStatus: string
  readonly fulfillmentStatus: string
  readonly subtotalMinor: number
  readonly discountMinor: number
  readonly shippingMinor: number
  readonly taxMinor: number
  readonly totalHargaMinor: number
  readonly items: unknown
  readonly promotion: {
  code: unknown;
  discount_minor: number;
}
  readonly shipping: {
  nama: unknown;
  telepon: unknown;
  alamat: unknown;
  kota: unknown;
  kode_pos: unknown;
}
  readonly createdAt: string
        }

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
            readonly id: unknown
  readonly orderId: unknown
  readonly invoiceNumber: unknown
  readonly metode: unknown
  readonly detail: unknown
  readonly status: unknown
  readonly paidAt: unknown
  readonly provider: unknown
  readonly providerTxnId: unknown
  readonly gatewayStatus: unknown
  readonly amountMinor: unknown
  readonly refundAmountMinor: unknown
  readonly items: unknown
  readonly promotion: {
  code: unknown;
  discount_minor: number;
}
  readonly gateway: {
  name: unknown;
  order_id: unknown;
  token: unknown;
  redirect_url: unknown;
}
  readonly totalHarga: unknown
        }

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
            readonly id: unknown
  readonly nama: unknown
  readonly deskripsi: unknown
  readonly image: unknown
  readonly imageUrl: string
  readonly categoryId: unknown
  readonly categoryName: unknown
  readonly harga: unknown
  readonly stok: unknown
  readonly rating: number
  readonly reviewCount: number
        }

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]

export interface RegisterResponseTransformed {
            readonly success: boolean
  readonly message: string
  readonly data: string | null
        }

export type RegisterResponseShow = RegisterResponseTransformed
export type RegisterResponseIndex = RegisterResponseTransformed[]

export interface OauthRedirectTransformed {
            readonly provider: string
  readonly authUrl: unknown
        }

export type OauthRedirectShow = OauthRedirectTransformed
export type OauthRedirectIndex = OauthRedirectTransformed[]

export interface OauthCallbackTransformed {
            readonly message: string
  readonly error: unknown
        }

export type OauthCallbackShow = OauthCallbackTransformed
export type OauthCallbackIndex = OauthCallbackTransformed[]

export interface CategoriesTransformed {
            readonly data: unknown
        }

export type CategoriesShow = CategoriesTransformed
export type CategoriesIndex = CategoriesTransformed[]

export interface ProdukReviewsTransformed {
            readonly summary: {
  avg_rating: number;
  total_review: number;
}
  readonly reviews: unknown
        }

export type ProdukReviewsShow = ProdukReviewsTransformed
export type ProdukReviewsIndex = ProdukReviewsTransformed[]

export interface ProfileTransformed {
            readonly id: unknown
  readonly name: unknown
  readonly email: unknown
        }

export type ProfileShow = ProfileTransformed
export type ProfileIndex = ProfileTransformed[]

export interface ProdukItemTransformed {
            readonly id: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type ProdukItemShow = ProdukItemTransformed
export type ProdukItemIndex = ProdukItemTransformed[]

export interface OrderTransformed {
            readonly id: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type OrderShow = OrderTransformed
export type OrderIndex = OrderTransformed[]

export interface PaymentTransformed {
            readonly id: number
  readonly createdAt: string | null
  readonly updatedAt: string | null
        }

export type PaymentShow = PaymentTransformed
export type PaymentIndex = PaymentTransformed[]
