/**
 * layers/FieldEmitter.ts
 *
 * Emits: contract/api-field.ts
 * 
 * RESPONSIBILITY: Generate global field lookup table untuk frontend form transformations
 * 
 * NEW CONTRACT IR ARCHITECTURE:
 * - Consumes ContractIR.resources untuk generate ApiApiField
 * - All field transformations sudah resolved di ResourceIR.fields
 * - Output format: Global flat object SNAKE_UPPER → snake_case
 * 
 * Outputs:
 * - ApiApiField constant (camelCase → snake_case lookup table)
 * - Used by frontend untuk transformasi form field names
 */

import { ContractIR, ResourceIR, ResourceFieldIR, GeneratedFile, IREmitter } from '../../../../core/src/types/ir'

export class FieldEmitter implements IREmitter {
    /**
     * Contract IR Architecture - Thin Emitter
     * 
     * Generate global ApiApiField object persis seperti format lama
     * Input: ContractIR dengan all field transformations sudah resolved
     * Output: Flat object SNAKE_UPPER keys → snake_case values
     * 
     * Format output:
     * export const ApiApiField = {
     *   CUSTOMERNAME: "customer_name",
     *   CREATEDAT: "created_at",
     *   ...
     * } as const
     */
    emit(ir: ContractIR): GeneratedFile[] {
        const files: GeneratedFile[] = []
        const lines: string[] = []

        // Header comment
        lines.push('// Auto-generated by routesync. Do not edit manually.')
        lines.push('')

        // Generate global ApiApiField object
        lines.push('export const ApiApiField = {')

        // Collect all fields from all resources into flat structure
        const allFieldMappings: string[] = []

        for (const resource of ir.resources) {
            for (const field of resource.fields) {
                // Convert camelCase to SNAKE_UPPER
                const upperKey = this.camelCaseToSnakeUpper(field.transformedName)
                allFieldMappings.push(`  ${upperKey}: "${field.name}",`)
            }
        }

        // Add all field mappings
        lines.push(...allFieldMappings)
        lines.push('} as const')

        files.push({
            path: 'contract/api-field.ts',
            content: lines.join('\n'),
            metadata: {
                emitter: 'FieldEmitter',
                generatedAt: new Date().toISOString(),
                dependencies: []
            }
        })

        return files
    }

    /**
     * Convert camelCase to SNAKE_UPPER
     * customerName → CUSTOMERNAME
     * createdAt → CREATEDAT
     * userId → USERID
     * redirectTo → REDIRECTTO
     * providerUserId → PROVIDERUSERID
     */
    private camelCaseToSnakeUpper(camelCase: string): string {
        // Insert underscore before uppercase letters, then convert to uppercase
        return camelCase
            .replace(/([a-z])([A-Z])/g, '$1_$2')
            .toUpperCase()
    }
}