/**
 * SDKEmitter - Resource-Grouped API Generation
 * 
 * Implements the new api.ts structure from Engine.Fix.md §27:
 * - Resource-centric grouping (not per HTTP method)
 * - Explicit types block with typeOf<T>()
 * - Nested contract/mapper per action
 * - Consistent action naming (create/update, not post/patch)
 * 
 * Benefits:
 * ✅ Solves profile.put vs profile.patch duplication (§24.3)
 * ✅ Explicit type declarations (§27.1)
 * ✅ Single action vocabulary across types/contract/mapper (§27.6)
 * ✅ Natural body/response optionality per action (§27.6)
 */

import { ContractIR, EndpointIR, GeneratedFile, IREmitter, HttpMethod } from '../../../../core/src/types/ir'

interface ResourceEndpoint {
    resourceName: string
    actions: Map<string, ActionEndpoint>
}

interface ActionEndpoint {
    method: HttpMethod
    path: string
    endpoint: EndpointIR
    hasBody: boolean
    hasResponse: boolean
}

export class SDKEmitter implements IREmitter {
    emit(ir: ContractIR): GeneratedFile[] {
        const content = this.generateResourceGroupedAPI(ir)

        return [{
            path: 'sdk/api.ts',
            content,
            metadata: {
                emitter: 'SDKEmitter',
                generatedAt: new Date().toISOString(),
                dependencies: ['types/api-read.ts', 'contract/api-contract.ts', 'mappers/api-mapper.ts']
            }
        }]
    }

    private generateResourceGroupedAPI(ir: ContractIR): string {
        const resourceEndpoints = this.groupEndpointsByResource(ir)

        return `/**
 * Resource-Grouped API Client
 * Generated by SDKEmitter - Contract IR Architecture
 * 
 * Structure: api.{resource}.endpoint({ types, contract, mapper })
 * Benefits: Type-safe, consistent action naming, no duplication
 * Sesuai Engine.Fix.md §27 specification
 */

import { defineApi, endpoint, typeOf } from 'routesync'
import { API_URL, API_ENDPOINTS, ROUTES, Enums } from 'routesync'

// Type imports from generated files
${this.generateTypeImports(ir)}

// Validation imports from generated files  
${this.generateValidationImports(ir)}

// Mapper imports from generated files
${this.generateMapperImports(ir)}

export const api = defineApi({
${resourceEndpoints.map(resource => this.generateResourceBlock(resource)).join(',\n')}
})

export type ApiClient = typeof api
export default api
`
    }

    private groupEndpointsByResource(ir: ContractIR): ResourceEndpoint[] {
        const resourceMap = new Map<string, ResourceEndpoint>()

        for (const endpoint of ir.endpoints) {
            const resourceName = this.extractResourceName(endpoint.id)
            const actionName = this.mapMethodAndPathToAction(endpoint.method, endpoint.path)

            if (!resourceMap.has(resourceName)) {
                resourceMap.set(resourceName, {
                    resourceName,
                    actions: new Map()
                })
            }

            const resource = resourceMap.get(resourceName)!
            resource.actions.set(actionName, {
                method: endpoint.method,
                path: endpoint.path,
                endpoint,
                hasBody: this.actionNeedsBody(endpoint.method),
                hasResponse: true // All endpoints have response
            })
        }

        return Array.from(resourceMap.values())
    }

    private extractResourceName(endpointId: string): string {
        // Extract resource name from endpoint ID like "get_orders" -> "orders"
        const parts = endpointId.split('_')
        if (parts.length > 1) {
            return parts.slice(1).join('_') // Remove HTTP method prefix
        }
        return endpointId
    }

    private mapMethodAndPathToAction(method: HttpMethod, path: string): string {
        // Consistent action mapping from Engine.Fix.md §27
        const ACTION_MAP: Record<HttpMethod, string> = {
            'GET': this.isShowPath(path) ? 'show' : 'index',
            'POST': 'create',
            'PUT': 'update',
            'PATCH': 'update', // Unifies PUT/PATCH → update (solves §24.3)
            'DELETE': 'destroy',
            'HEAD': 'head',
            'OPTIONS': 'options'
        }

        return ACTION_MAP[method] || method.toLowerCase()
    }

    private isShowPath(path: string): boolean {
        // Detect show vs index pattern: /users/{id} vs /users
        return path.includes('{') || path.includes(':')
    }

    private actionNeedsBody(method: HttpMethod): boolean {
        return ['POST', 'PUT', 'PATCH'].includes(method)
    }

    private generateResourceBlock(resource: ResourceEndpoint): string {
        return `  ${resource.resourceName}: {
    endpoint({
      types: {
${this.generateTypesBlock(resource)}
      },
      contract: {
${this.generateContractBlock(resource)}
      },
      mapper: {
${this.generateMapperBlock(resource)}
      }
    })
  }`
    }

    private generateTypesBlock(resource: ResourceEndpoint): string {
        const types: string[] = []

        // Generate explicit type declarations with typeOf<T>() (§27.1)
        for (const [actionName] of resource.actions) {
            switch (actionName) {
                case 'index':
                    types.push(`        index: typeOf<${this.capitalize(resource.resourceName)}Index>(),`)
                    break
                case 'show':
                    types.push(`        show: typeOf<${this.capitalize(resource.resourceName)}Show>(),`)
                    break
                case 'create':
                    types.push(`        createForm: typeOf<${this.capitalize(resource.resourceName)}Form["Create"]>(),`)
                    types.push(`        createPayload: typeOf<${this.capitalize(resource.resourceName)}ApiCreate>(),`)
                    break
                case 'update':
                    types.push(`        updateForm: typeOf<${this.capitalize(resource.resourceName)}Form["Update"]>(),`)
                    types.push(`        updatePayload: typeOf<${this.capitalize(resource.resourceName)}ApiUpdate>(),`)
                    break
            }
        }

        // Always include response type (dari contract, bukan read)
        types.push(`        response: typeOf<${this.capitalize(resource.resourceName)}ResourceResponse>(),`)

        return types.join('\n')
    }

    private generateContractBlock(resource: ResourceEndpoint): string {
        const contracts: string[] = []

        // Generate nested contract per action (§27.5)
        for (const [actionName, action] of resource.actions) {
            const actionBlock: string[] = []

            // Body contract for actions that need it
            if (action.hasBody) {
                const bodyValidator = this.getBodyValidatorName(resource.resourceName, actionName)
                actionBlock.push(`          body: ${bodyValidator},`)
            }

            // Response contract for all actions
            const responseValidator = this.getResponseValidatorName(resource.resourceName, actionName)
            actionBlock.push(`          response: ${responseValidator},`)

            contracts.push(`        ${actionName}: {
${actionBlock.join('\n')}
        },`)
        }

        return contracts.join('\n')
    }

    private generateMapperBlock(resource: ResourceEndpoint): string {
        const mappers: string[] = []

        // Generate nested mapper per action (§27.5)
        for (const [actionName, action] of resource.actions) {
            const actionBlock: string[] = []

            // Body mapper for actions that need it
            if (action.hasBody) {
                const bodyMapper = this.getBodyMapperName(resource.resourceName, actionName)
                actionBlock.push(`          body: ${bodyMapper},`)
            }

            // Response mapper for all actions
            const responseMapper = this.getResponseMapperName(resource.resourceName, actionName)
            actionBlock.push(`          response: ${responseMapper},`)

            mappers.push(`        ${actionName}: {
${actionBlock.join('\n')}
        },`)
        }

        return mappers.join('\n')
    }

    private generateTypeImports(ir: ContractIR): string {
        const imports: string[] = []

        for (const resource of ir.resources) {
            const resourceName = this.capitalize(resource.name)
            // Frontend types dari ReadEmitter
            imports.push(`import type {
  ${resourceName}Index,
  ${resourceName}Show,
  ${resourceName}Form,
  ${resourceName}ApiCreate,
  ${resourceName}ApiUpdate,
} from '../types/api-read'`)

            // Response types dari ContractEmitter (z.infer results)
            imports.push(`import type {
  ${resourceName}ResourceResponse,
} from '../contract/api-contract'`)
        }

        return imports.join('\n')
    }

    private generateValidationImports(ir: ContractIR): string {
        const imports: string[] = []

        for (const resource of ir.resources) {
            const resourceName = this.capitalize(resource.name)
            imports.push(`import {
  validate${resourceName}CreatePayload,
  validate${resourceName}UpdatePayload,
  validate${resourceName}ResourceResponse,          // ⭐ SHARED
  validate${resourceName}ResourceCollectionResponse, // ⭐ Collection
} from '../contract/api-contract'`)
        }

        return imports.join('\n')
    }

    private generateMapperImports(ir: ContractIR): string {
        const imports: string[] = []

        for (const resource of ir.resources) {
            const resourceName = this.capitalize(resource.name)
            imports.push(`import {
  toApi${resourceName}Create,
  toApi${resourceName}Update,
  to${resourceName}Read,
  to${resourceName}ReadList,
} from '../mappers/api-mapper'`)
        }

        return imports.join('\n')
    }

    private getBodyValidatorName(resourceName: string, actionName: string): string {
        return `validate${this.capitalize(resourceName)}${this.capitalize(actionName)}Payload`
    }

    private getResponseValidatorName(resourceName: string, actionName: string): string {
        // ⭐ KEY FIX: Shared response validator untuk semua CUD operations
        // Hanya index yang menggunakan collection validator
        if (actionName === 'index') {
            return `validate${this.capitalize(resourceName)}CollectionResponse`
        }

        // Semua operations lain (show/create/update) menggunakan SHARED single validator
        // karena backend selalu return single resource untuk CUD operations
        return `validate${this.capitalize(resourceName)}Response`
    }

    private getBodyMapperName(resourceName: string, actionName: string): string {
        return `toApi${this.capitalize(resourceName)}${this.capitalize(actionName)}`
    }

    private getResponseMapperName(resourceName: string, actionName: string): string {
        if (actionName === 'index') {
            return `to${this.capitalize(resourceName)}ReadList`
        }
        return `to${this.capitalize(resourceName)}Read`
    }

    private capitalize(str: string): string {
        return str.charAt(0).toUpperCase() + str.slice(1)
    }
}