/**
 * Resource-Grouped API Client
 * Generated by SDKEmitter - Contract IR Architecture
 * 
 * Structure: api.{resource}.endpoint({ types, contract, mapper })
 * Benefits: Type-safe, consistent action naming, no duplication
 * Sesuai Engine.Fix.md §27 specification
 */

import { defineApi, endpoint, typeOf } from 'routesync'
import { API_URL, API_ENDPOINTS, ROUTES, Enums } from 'routesync'

// Type imports from generated files
// Frontend types dari ReadEmitter  
import type {

} from '../types/api-read'

// Response types dari ContractEmitter (z.infer results)
import type {
  LoginResponse,
  OauthRedirectResponse,
  SocialLoginResponse,
  CategoriesResponse,
  ProdukListResponse,
  ProdukReviewsGetResponse,
  ProdukReviewsCreateResponse,
  OrdersListResponse,
  WishlistListResponse,
} from '../contract/api-contract'

// Validation imports from generated files  
// Validation imports dari ContractEmitter
import {
  validateLoginResponse,
  validateOauthRedirectResponse,
  validateSocialLoginResponse,
  validateCategoriesResponse,
  validateProdukListResponse,
  validateProdukReviewsGetResponse,
  validateProdukReviewsCreateResponse,
  validateOrdersListResponse,
  validateWishlistListResponse,
  validateLogoutResponse,
  validateResetPasswordResponse,
} from '../contract/api-contract'

// Mapper imports from generated files
// Mapper imports dari MapperEmitter
import {
  toLoginResponseRead,
  toOauthRedirectResponseRead,
  toSocialLoginResponseRead,
  toCategoriesResponseRead,
  toProdukListResponseRead,
  toProdukReviewsGetResponseRead,
  toProdukReviewsCreateResponseRead,
  toOrdersListResponseRead,
  toWishlistListResponseRead,
  toRegisterResponseRead,
} from '../mappers/api-mapper'

export const api = defineApi({
  register.post: {
    endpoint({
      types: {
        createForm: typeOf<Register.postForm["Create"]>(),
        createPayload: typeOf<Register.postApiCreate>(),
        response: typeOf<Register.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateRegister.postCreatePayload,
          response: validateRegister.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiRegister.postCreate,
          response: toRegister.postRead,
        },
      }
    })
  },
  login.post: {
    endpoint({
      types: {
        createForm: typeOf<Login.postForm["Create"]>(),
        createPayload: typeOf<Login.postApiCreate>(),
        response: typeOf<Login.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateLogin.postCreatePayload,
          response: validateLogin.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiLogin.postCreate,
          response: toLogin.postRead,
        },
      }
    })
  },
  provider_redirect.get: {
    endpoint({
      types: {
        show: typeOf<Provider_redirect.getShow>(),
        response: typeOf<Provider_redirect.getResourceResponse>(),
      },
      contract: {
        show: {
          response: validateProvider_redirect.getResponse,
        },
      },
      mapper: {
        show: {
          response: toProvider_redirect.getRead,
        },
      }
    })
  },
  provider_callback.get: {
    endpoint({
      types: {
        show: typeOf<Provider_callback.getShow>(),
        response: typeOf<Provider_callback.getResourceResponse>(),
      },
      contract: {
        show: {
          response: validateProvider_callback.getResponse,
        },
      },
      mapper: {
        show: {
          response: toProvider_callback.getRead,
        },
      }
    })
  },
  provider_callback.post: {
    endpoint({
      types: {
        createForm: typeOf<Provider_callback.postForm["Create"]>(),
        createPayload: typeOf<Provider_callback.postApiCreate>(),
        response: typeOf<Provider_callback.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateProvider_callback.postCreatePayload,
          response: validateProvider_callback.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiProvider_callback.postCreate,
          response: toProvider_callback.postRead,
        },
      }
    })
  },
  forgot-password.post: {
    endpoint({
      types: {
        createForm: typeOf<Forgot-password.postForm["Create"]>(),
        createPayload: typeOf<Forgot-password.postApiCreate>(),
        response: typeOf<Forgot-password.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateForgot-password.postCreatePayload,
          response: validateForgot-password.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiForgot-password.postCreate,
          response: toForgot-password.postRead,
        },
      }
    })
  },
  reset-password.post: {
    endpoint({
      types: {
        createForm: typeOf<Reset-password.postForm["Create"]>(),
        createPayload: typeOf<Reset-password.postApiCreate>(),
        response: typeOf<Reset-password.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateReset-password.postCreatePayload,
          response: validateReset-password.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiReset-password.postCreate,
          response: toReset-password.postRead,
        },
      }
    })
  },
  categories.get: {
    endpoint({
      types: {
        index: typeOf<Categories.getIndex>(),
        response: typeOf<Categories.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateCategories.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toCategories.getReadList,
        },
      }
    })
  },
  produk.get: {
    endpoint({
      types: {
        index: typeOf<Produk.getIndex>(),
        response: typeOf<Produk.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateProduk.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toProduk.getReadList,
        },
      }
    })
  },
  id.get: {
    endpoint({
      types: {
        show: typeOf<Id.getShow>(),
        response: typeOf<Id.getResourceResponse>(),
      },
      contract: {
        show: {
          response: validateId.getResponse,
        },
      },
      mapper: {
        show: {
          response: toId.getRead,
        },
      }
    })
  },
  id_reviews.get: {
    endpoint({
      types: {
        show: typeOf<Id_reviews.getShow>(),
        response: typeOf<Id_reviews.getResourceResponse>(),
      },
      contract: {
        show: {
          response: validateId_reviews.getResponse,
        },
      },
      mapper: {
        show: {
          response: toId_reviews.getRead,
        },
      }
    })
  },
  webhook.post: {
    endpoint({
      types: {
        createForm: typeOf<Webhook.postForm["Create"]>(),
        createPayload: typeOf<Webhook.postApiCreate>(),
        response: typeOf<Webhook.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateWebhook.postCreatePayload,
          response: validateWebhook.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiWebhook.postCreate,
          response: toWebhook.postRead,
        },
      }
    })
  },
  profile.get: {
    endpoint({
      types: {
        index: typeOf<Profile.getIndex>(),
        response: typeOf<Profile.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateProfile.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toProfile.getReadList,
        },
      }
    })
  },
  profile.put: {
    endpoint({
      types: {
        updateForm: typeOf<Profile.putForm["Update"]>(),
        updatePayload: typeOf<Profile.putApiUpdate>(),
        response: typeOf<Profile.putResourceResponse>(),
      },
      contract: {
        update: {
          body: validateProfile.putUpdatePayload,
          response: validateProfile.putResponse,
        },
      },
      mapper: {
        update: {
          body: toApiProfile.putUpdate,
          response: toProfile.putRead,
        },
      }
    })
  },
  profile.patch: {
    endpoint({
      types: {
        updateForm: typeOf<Profile.patchForm["Update"]>(),
        updatePayload: typeOf<Profile.patchApiUpdate>(),
        response: typeOf<Profile.patchResourceResponse>(),
      },
      contract: {
        update: {
          body: validateProfile.patchUpdatePayload,
          response: validateProfile.patchResponse,
        },
      },
      mapper: {
        update: {
          body: toApiProfile.patchUpdate,
          response: toProfile.patchRead,
        },
      }
    })
  },
  orders.get: {
    endpoint({
      types: {
        index: typeOf<Orders.getIndex>(),
        response: typeOf<Orders.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateOrders.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toOrders.getReadList,
        },
      }
    })
  },
  items.post: {
    endpoint({
      types: {
        createForm: typeOf<Items.postForm["Create"]>(),
        createPayload: typeOf<Items.postApiCreate>(),
        response: typeOf<Items.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateItems.postCreatePayload,
          response: validateItems.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiItems.postCreate,
          response: toItems.postRead,
        },
      }
    })
  },
  items_produkItemId.patch: {
    endpoint({
      types: {
        updateForm: typeOf<Items_produkItemId.patchForm["Update"]>(),
        updatePayload: typeOf<Items_produkItemId.patchApiUpdate>(),
        response: typeOf<Items_produkItemId.patchResourceResponse>(),
      },
      contract: {
        update: {
          body: validateItems_produkItemId.patchUpdatePayload,
          response: validateItems_produkItemId.patchResponse,
        },
      },
      mapper: {
        update: {
          body: toApiItems_produkItemId.patchUpdate,
          response: toItems_produkItemId.patchRead,
        },
      }
    })
  },
  items_produkItemId.delete: {
    endpoint({
      types: {
        response: typeOf<Items_produkItemId.deleteResourceResponse>(),
      },
      contract: {
        destroy: {
          response: validateItems_produkItemId.deleteResponse,
        },
      },
      mapper: {
        destroy: {
          response: toItems_produkItemId.deleteRead,
        },
      }
    })
  },
  cart.delete: {
    endpoint({
      types: {
        response: typeOf<Cart.deleteResourceResponse>(),
      },
      contract: {
        destroy: {
          response: validateCart.deleteResponse,
        },
      },
      mapper: {
        destroy: {
          response: toCart.deleteRead,
        },
      }
    })
  },
  promo.post: {
    endpoint({
      types: {
        createForm: typeOf<Promo.postForm["Create"]>(),
        createPayload: typeOf<Promo.postApiCreate>(),
        response: typeOf<Promo.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validatePromo.postCreatePayload,
          response: validatePromo.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiPromo.postCreate,
          response: toPromo.postRead,
        },
      }
    })
  },
  promo.delete: {
    endpoint({
      types: {
        response: typeOf<Promo.deleteResourceResponse>(),
      },
      contract: {
        destroy: {
          response: validatePromo.deleteResponse,
        },
      },
      mapper: {
        destroy: {
          response: toPromo.deleteRead,
        },
      }
    })
  },
  checkout.post: {
    endpoint({
      types: {
        createForm: typeOf<Checkout.postForm["Create"]>(),
        createPayload: typeOf<Checkout.postApiCreate>(),
        response: typeOf<Checkout.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateCheckout.postCreatePayload,
          response: validateCheckout.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiCheckout.postCreate,
          response: toCheckout.postRead,
        },
      }
    })
  },
  buy-now.post: {
    endpoint({
      types: {
        createForm: typeOf<Buy-now.postForm["Create"]>(),
        createPayload: typeOf<Buy-now.postApiCreate>(),
        response: typeOf<Buy-now.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateBuy-now.postCreatePayload,
          response: validateBuy-now.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiBuy-now.postCreate,
          response: toBuy-now.postRead,
        },
      }
    })
  },
  keranjang.get: {
    endpoint({
      types: {
        index: typeOf<Keranjang.getIndex>(),
        response: typeOf<Keranjang.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateKeranjang.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toKeranjang.getReadList,
        },
      }
    })
  },
  wishlist.get: {
    endpoint({
      types: {
        index: typeOf<Wishlist.getIndex>(),
        response: typeOf<Wishlist.getResourceResponse>(),
      },
      contract: {
        index: {
          response: validateWishlist.getCollectionResponse,
        },
      },
      mapper: {
        index: {
          response: toWishlist.getReadList,
        },
      }
    })
  },
  wishlist.post: {
    endpoint({
      types: {
        createForm: typeOf<Wishlist.postForm["Create"]>(),
        createPayload: typeOf<Wishlist.postApiCreate>(),
        response: typeOf<Wishlist.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateWishlist.postCreatePayload,
          response: validateWishlist.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiWishlist.postCreate,
          response: toWishlist.postRead,
        },
      }
    })
  },
  produkItemId.delete: {
    endpoint({
      types: {
        response: typeOf<ProdukItemId.deleteResourceResponse>(),
      },
      contract: {
        destroy: {
          response: validateProdukItemId.deleteResponse,
        },
      },
      mapper: {
        destroy: {
          response: toProdukItemId.deleteRead,
        },
      }
    })
  },
  id_reviews.post: {
    endpoint({
      types: {
        createForm: typeOf<Id_reviews.postForm["Create"]>(),
        createPayload: typeOf<Id_reviews.postApiCreate>(),
        response: typeOf<Id_reviews.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateId_reviews.postCreatePayload,
          response: validateId_reviews.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiId_reviews.postCreate,
          response: toId_reviews.postRead,
        },
      }
    })
  },
  orderId.post: {
    endpoint({
      types: {
        createForm: typeOf<OrderId.postForm["Create"]>(),
        createPayload: typeOf<OrderId.postApiCreate>(),
        response: typeOf<OrderId.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateOrderId.postCreatePayload,
          response: validateOrderId.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiOrderId.postCreate,
          response: toOrderId.postRead,
        },
      }
    })
  },
  id_invoice.get: {
    endpoint({
      types: {
        show: typeOf<Id_invoice.getShow>(),
        response: typeOf<Id_invoice.getResourceResponse>(),
      },
      contract: {
        show: {
          response: validateId_invoice.getResponse,
        },
      },
      mapper: {
        show: {
          response: toId_invoice.getRead,
        },
      }
    })
  },
  logout.post: {
    endpoint({
      types: {
        createForm: typeOf<Logout.postForm["Create"]>(),
        createPayload: typeOf<Logout.postApiCreate>(),
        response: typeOf<Logout.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateLogout.postCreatePayload,
          response: validateLogout.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiLogout.postCreate,
          response: toLogout.postRead,
        },
      }
    })
  },
  produk.post: {
    endpoint({
      types: {
        createForm: typeOf<Produk.postForm["Create"]>(),
        createPayload: typeOf<Produk.postApiCreate>(),
        response: typeOf<Produk.postResourceResponse>(),
      },
      contract: {
        create: {
          body: validateProduk.postCreatePayload,
          response: validateProduk.postResponse,
        },
      },
      mapper: {
        create: {
          body: toApiProduk.postCreate,
          response: toProduk.postRead,
        },
      }
    })
  }
})

export type ApiClient = typeof api
export default api
