// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-07-16T03:50:07.207Z

import { defineApi, endpoint } from 'routesync'
import { API_URL, API_ENDPOINTS, ROUTES, Enums } from './constants'
import { toLoginResponseRead, toOauthRedirectResponseRead, toProdukReviewsCreateResponseRead, toProdukReviewsGetResponseRead, toSocialLoginResponseRead } from './mappers/api-mapper'

export const api = defineApi({
  register: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.REGISTER,
    }),
  },
  login: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGIN,
      mapper: {
        response: toLoginResponseRead,
      },
    }),
  },
  oauthRedirect: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_REDIRECT,
      mapper: {
        response: toOauthRedirectResponseRead,
      },
    }),
  },
  oauthCallback: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
    }),
  },
  socialLogin: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.SOCIAL_LOGIN,
      mapper: {
        response: toSocialLoginResponseRead,
      },
    }),
  },
  forgotPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.FORGOT_PASSWORD,
    }),
  },
  resetPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.RESET_PASSWORD,
    }),
  },
  categories: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.CATEGORIES,
    }),
  },
  produk: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK,
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL,
    }),
  },
  produkReviews: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      mapper: {
        response: toProdukReviewsGetResponseRead,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      auth: true,
      mapper: {
        response: toProdukReviewsCreateResponseRead,
      },
    }),
  },
  paymentWebhook: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_WEBHOOK,
    }),
  },
  profile: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
    }),
    put: endpoint({
      method: 'PUT',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
    }),
    patch: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
    }),
  },
  orders: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS,
      auth: true,
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL,
      auth: true,
    }),
  },
  cartItems: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_ITEMS,
      auth: true,
    }),
    update: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
    }),
  },
  cart: {
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART,
      auth: true,
    }),
  },
  cartPromo: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
    }),
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
    }),
  },
  checkout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CHECKOUT,
      auth: true,
    }),
  },
  buyNow: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.BUY_NOW,
      auth: true,
    }),
  },
  keranjang: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.KERANJANG,
      auth: true,
    }),
  },
  wishlist: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
    }),
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.WISHLIST_PRODUK_ITEM_ID,
      auth: true,
    }),
  },
  payment: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_ORDER_ID,
      auth: true,
    }),
  },
  ordersInvoice: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL_INVOICE,
      auth: true,
    }),
  },
  logout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGOUT,
      auth: true,
    }),
  },
  adminProduk: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.ADMIN_PRODUK,
      auth: true,
    }),
  },
})

export default api
