/**
 * Runtime contract validation schemas
 * Generated by ContractGeneratorPass
 */
import { z } from 'zod';

// ========== REQUEST SCHEMAS ==========
/**
 * Runtime contract validation schemas for login
 * @provenance ContractSchema: login
 */
export const loginContractSchema = {
  Update: z.object({ email: z.string(), password: z.string() })
};
export const LoginContractSchema = loginContractSchema;

/**
 * Runtime contract validation schemas for register
 * @provenance ContractSchema: register
 */
export const registerContractSchema = {
  Update: z.object({ name: z.string(), email: z.string(), password: z.string() })
};
export const RegisterContractSchema = registerContractSchema;

/**
 * Runtime contract validation schemas for buyNow
 * @provenance ContractSchema: buyNow
 */
export const buyNowContractSchema = {
  Create: z.object({ produk_item_id: z.number(), qty: z.number(), shipping_nama: z.string(), shipping_telepon: z.string(), shipping_alamat: z.string(), shipping_kota: z.string(), shipping_kode_pos: z.string() })
};
export const BuyNowContractSchema = buyNowContractSchema;

/**
 * Runtime contract validation schemas for cartItem
 * @provenance ContractSchema: cartItem
 */
export const cartItemContractSchema = {
  Create: z.object({ produk_item_id: z.number(), qty: z.number() }),
  Update: z.object({ qty: z.number() })
};
export const CartItemContractSchema = cartItemContractSchema;

/**
 * Runtime contract validation schemas for order
 * @provenance ContractSchema: order
 */
export const orderContractSchema = {
  Create: z.object({ items: z.array(z.object({ produk_item_id: z.number(), qty: z.number() })).optional(), shipping_nama: z.string(), shipping_telepon: z.string(), shipping_alamat: z.string(), shipping_kota: z.string(), shipping_kode_pos: z.string() })
};
export const OrderContractSchema = orderContractSchema;

/**
 * Runtime contract validation schemas for payment
 * @provenance ContractSchema: payment
 */
export const paymentContractSchema = {
  Create: z.object({ metode: z.string(), detail: z.array(z.unknown()), provider: z.string(), provider_txn_id: z.string(), idempotency_key: z.string(), gateway_code: z.string(), gateway_message: z.string() })
};
export const PaymentContractSchema = paymentContractSchema;

/**
 * Runtime contract validation schemas for profile
 * @provenance ContractSchema: profile
 */
export const profileContractSchema = {
  Update: z.object({ name: z.string(), email: z.string() })
};
export const ProfileContractSchema = profileContractSchema;

// ========== INFERRED TYPES ==========
export type LoginContract = {
  Update: z.infer<typeof loginContractSchema.Update>
};

export type RegisterContract = {
  Update: z.infer<typeof registerContractSchema.Update>
};

export type BuyNowContract = {
  Create: z.infer<typeof buyNowContractSchema.Create>
};

export type CartItemContract = {
  Create: z.infer<typeof cartItemContractSchema.Create>,
  Update: z.infer<typeof cartItemContractSchema.Update>
};

export type OrderContract = {
  Create: z.infer<typeof orderContractSchema.Create>
};

export type PaymentContract = {
  Create: z.infer<typeof paymentContractSchema.Create>
};

export type ProfileContract = {
  Update: z.infer<typeof profileContractSchema.Update>
};

// ========== VALIDATORS ==========
export const validateLoginUpdate = (data: unknown) => {
  return loginContractSchema.Update.parse(data);
};

export const validateRegisterUpdate = (data: unknown) => {
  return registerContractSchema.Update.parse(data);
};

export const validateBuyNowCreate = (data: unknown) => {
  return buyNowContractSchema.Create.parse(data);
};

export const validateCartItemCreate = (data: unknown) => {
  return cartItemContractSchema.Create.parse(data);
};

export const validateCartItemUpdate = (data: unknown) => {
  return cartItemContractSchema.Update.parse(data);
};

export const validateOrderCreate = (data: unknown) => {
  return orderContractSchema.Create.parse(data);
};

export const validatePaymentCreate = (data: unknown) => {
  return paymentContractSchema.Create.parse(data);
};

export const validateProfileUpdate = (data: unknown) => {
  return profileContractSchema.Update.parse(data);
};

// ========== ERROR SCHEMAS & VALIDATORS ==========
export const laravelValidationErrorSchema = z.object({
  message: z.string(),
  errors: z.record(z.string(), z.array(z.string()))
});
export type LaravelValidationError = z.infer<typeof laravelValidationErrorSchema>;
export const validateLaravelValidationError = (data: unknown): LaravelValidationError => laravelValidationErrorSchema.parse(data);

export const laravelUnauthorizedErrorSchema = z.object({
  message: z.string()
});
export type LaravelUnauthorizedError = z.infer<typeof laravelUnauthorizedErrorSchema>;
export const validateLaravelUnauthorizedError = (data: unknown): LaravelUnauthorizedError => laravelUnauthorizedErrorSchema.parse(data);

// ========== EXPORTS ==========
export const ContractSchemas = {
  login: loginContractSchema,
  register: registerContractSchema,
  buyNow: buyNowContractSchema,
  cartItem: cartItemContractSchema,
  order: orderContractSchema,
  payment: paymentContractSchema,
  profile: profileContractSchema
};