// Auto-generated by routesync. Do not edit manually.

export const ApiApiField = {
  EMAIL: "email",
  PASSWORD: "password",
  NAME: "name",
  PRODUKITEMID: "produk_item_id",
  QTY: "qty",
  SHIPPINGNAMA: "shipping_nama",
  SHIPPINGTELEPON: "shipping_telepon",
  SHIPPINGALAMAT: "shipping_alamat",
  SHIPPINGKOTA: "shipping_kota",
  SHIPPINGKODEPOS: "shipping_kode_pos",
  ITEMS: "items",
  METODE: "metode",
  DETAIL: "detail",
  PROVIDER: "provider",
  PROVIDERTXNID: "provider_txn_id",
  IDEMPOTENCYKEY: "idempotency_key",
  GATEWAYCODE: "gateway_code",
  GATEWAYMESSAGE: "gateway_message",
} as const
