import type { ModelAst } from '../../../../types/upstream/ast';
import type { ModelDefinition, ModelKeyKind } from '../../../../types/upstream/model';
import type { CastType } from '../../../../types/upstream/expression';
import type { ModelSemanticDefinition } from '../../../../types/upstream/model';
import type { Sequence, PropertyNames, Indexes, ForeignKeys } from '../../../../types/upstream/collections';
import type { SourceSpan } from '../../../../types/upstream/provenance';
import type { PrimitiveVocabulary } from '../../../../types/upstream/primitiveVocabulary';
import type { TypeExpression } from '../../../../types/upstream/typeVocabulary';
import type { ModelFacts } from '../../../../types/upstream/modelSourceFacts';
import type { ModelDeclarationAst } from '../../lexer';
import type { ModelCast } from '../../../../types/upstream/model';
import type { ModelAccessorFact, ModelColumnFact, ModelRelationFact } from '../../../../types/upstream/modelSourceFacts';
import type { NumberValue, StringValue, TruthValue } from '../../../../types/upstream/valueObjects';
import { parseModelSourceFacts } from './modelSourceFactsParser';
import { accessorExpression } from './modelAccessorCanonical';

const str = (value: string): StringValue => ({ kind: 'string_value', value });
const num = (value: number): NumberValue => ({ kind: 'number_value', value });
const truth = (value: boolean): TruthValue => ({ kind: 'truth_value', value });
const sequence = <T>(items: readonly T[]): Sequence<T> => items.reduceRight<Sequence<T>>((tail, head) => ({ kind: 'cons', head, tail }), { kind: 'empty' });
const sourceSpan = (file: string, length: number): SourceSpan => ({ kind: 'source_span', file: { kind: 'source_file', value: str(file) }, start: num(0), end: num(length) });
const name = (value: string) => ({ kind: 'model_name', value: str(value) } as const);
const property = (value: string) => ({ kind: 'property_name', value: str(value) } as const);
const column = (value: string) => ({ kind: 'column_name', value: str(value) } as const);
const table = (value: string) => ({ kind: 'table_name', value: str(value) } as const);
const primitive = (value: PrimitiveVocabulary): TypeExpression => ({ kind: 'primitive', value });
import { semanticType } from './semanticTypeCanonical';

const exposure = (values: readonly string[]): PropertyNames => ({ kind: 'property_names', items: sequence(values.map(value => property(value))) });


export function modelAstFromSemantic(
    model: ModelSemanticDefinition,
    schema: { readonly indexes: Indexes; readonly foreignKeys: ForeignKeys },
    casts: readonly ModelCast[],
    accessors: readonly ModelAccessorFact[],
    relations: readonly ModelRelationFact[],
    file: string,
    length: number,
    declaration: ModelDeclarationAst
): ModelAst {
    const span = sourceSpan(file, length);
    const semanticRelations = relations;
    const semanticAccessors = accessors;
    const modelProperties = model.columnFacts.map((item: ModelColumnFact) => ({ kind: 'property' as const, name: item.property, type: item.type.value, presence: item.presence, origin: { kind: 'column' as const, column: item.column }, source: item.source }));
    const factsSource = parseModelSourceFacts(declaration, span);
    const modelColumnFacts = model.columnFacts;
    const keySemanticType = (kind: 'number' | 'string'): TypeExpression => {
        switch (kind) {
            case 'number': return primitive({ kind: 'number' });
            case 'string': return primitive({ kind: 'string' });
        }
    };
    const modelKeySemanticType = keySemanticType(model.key.semanticType.kind);
    const surfaceMembers = [
        ...modelColumnFacts,
        ...semanticAccessors,
        ...semanticRelations,
        ...factsSource.methods,
        ...factsSource.constants
    ];
    const modelSchema = { kind: 'model_schema' as const, columns: { kind: 'model_column_facts' as const, items: sequence(modelColumnFacts) }, foreignKeys: schema.foreignKeys, indexes: schema.indexes };
    const definition: ModelDefinition = {
        kind: 'model',
        identity: { kind: 'model_identity', name: name(model.identity.name.value.value), shortName: name(model.identity.shortName.value.value), table: table(model.identity.table.value.value), inheritance: factsSource.inheritance },
        source: span,
        file: { kind: 'source_file', value: str(file) },
        key: { kind: 'primary_key', column: column(model.identity.primaryKey.value.value), type: model.key.type, semanticType: modelKeySemanticType, autoGenerated: truth(model.behavior.incrementing) },
        behavior: { kind: 'model_behavior', incrementing: truth(model.behavior.incrementing), softDeletes: truth(model.behavior.softDeletes), timestamps: truth(model.behavior.timestamps) },
        exposure: { kind: 'model_exposure', fillable: exposure(model.exposure.fillable.map(value => value.value.value)), guarded: exposure(model.exposure.guarded.map(value => value.value.value)), hidden: exposure(model.exposure.hidden.map(value => value.value.value)), appends: exposure(model.exposure.appends.map(value => value.value.value)) },
        capabilities: { kind: 'model_source_capabilities', traits: factsSource.traits },
        surface: { kind: 'property_surface', properties: { kind: 'properties', items: sequence(modelProperties) } },
        semanticProperties: model.surface.properties,
        schema: modelSchema,
        properties: { kind: 'properties', items: sequence(modelProperties) },
        relations: { kind: 'model_relations', items: sequence(semanticRelations.map((relation: ModelRelationFact) => ({ kind: 'model_relation' as const, name: relation.name, target: relation.target, relation: relation.relation, cardinality: relation.cardinality, multiplicity: relation.multiplicity, targetShape: relation.targetShape, traversalTarget: relation.traversalTarget, semanticType: relation.semanticType, key: relation.key, source: relation.source }))) },
        casts: { kind: 'model_casts', items: sequence(casts) },
        computed: { kind: 'model_accessors', items: sequence(semanticAccessors.map((accessor: ModelAccessorFact) => ({ kind: 'model_accessor' as const, name: accessor.property, expression: accessorExpression(accessor.computation, accessor.source), source: accessor.source }))) },
        constants: { kind: 'model_constants', items: sequence(factsSource.constants.map(item => ({ kind: 'model_constant' as const, name: item.name, value: item.value, source: item.source }))) },
        methods: { kind: 'model_methods', items: sequence(factsSource.methods.map(item => ({ kind: 'model_method' as const, name: item.name, result: item.result, body: item.body, source: item.source }))) },
        semantic: model
    };
    const facts: ModelFacts = { kind: 'model_facts', identity: { kind: 'model_identity_facts', name: name(model.identity.name.value.value), shortName: name(model.identity.shortName.value.value), table: table(model.identity.table.value.value), inheritance: factsSource.inheritance, source: span }, key: { kind: 'model_key_facts', column: column(model.identity.primaryKey.value.value), type: model.key.type, semanticType: modelKeySemanticType, autoGenerated: truth(model.behavior.incrementing) }, behavior: { kind: 'model_behavior_facts', incrementing: truth(model.behavior.incrementing), softDeletes: truth(model.behavior.softDeletes), timestamps: truth(model.behavior.timestamps) }, exposure: { kind: 'model_exposure_facts', fillable: sequence(model.exposure.fillable.map(value => property(value.value.value))), guarded: sequence(model.exposure.guarded.map(value => property(value.value.value))), hidden: sequence(model.exposure.hidden.map(value => property(value.value.value))), appends: sequence(model.exposure.appends.map(value => property(value.value.value))) }, capabilities: factsSource.traits, surface: { kind: 'model_surface_facts', members: sequence(surfaceMembers) }, schema: modelSchema, source: span };
    return { kind: 'model_ast', definition, facts, source: span };
}
