/**
 * FormCodeBuilder.ts
 * 
 * Small focused class: Assemble final TypeScript code.
 * Pure assembly logic - combines pieces into complete file.
 * 
 * Responsibility: Build final code string from action blocks
 * 
 * @module compiler/generators/form-generation
 */

import type { GeneratedAction } from './FormActionGenerator';
import type { RequestType } from '../../artifacts/RequestTypesArtifact';

/**
 * Built code result
 */
export interface BuiltCode {
    /** Complete code string */
    readonly code: string;

    /** Line count */
    readonly lineCount: number;

    /** Form type count */
    readonly formTypeCount: number;
}

/**
 * FormCodeBuilder - Pure assembly logic
 * 
 * Tiny puzzle piece (~80 lines) yang fokus pada code assembly.
 * Takes action blocks, returns complete file content.
 * 
 * @example
 * ```typescript
 * const builder = new FormCodeBuilder();
 * const result = builder.buildFormTypes(requestTypes, actionsByResource);
 * // Returns complete forms/api-form.ts content
 * ```
 */
export class FormCodeBuilder {
    /**
     * Build complete form types file
     * 
     * Pure function - combines headers + form types.
     * 
     * @param requestTypes - Array of request types
     * @param actionsByResource - Map of resource → actions
     * @returns Built code with metadata
     */
    buildFormTypes(
        requestTypes: readonly RequestType[],
        actionsByResource: Map<string, readonly GeneratedAction[]>
    ): BuiltCode {
        const lines: string[] = [];

        // File header
        lines.push('/**');
        lines.push(' * Form type definitions untuk input validation');
        lines.push(' * Generated by FormGeneratorPass - Compiler Architecture');
        lines.push(' * ');
        lines.push(' * Output path: forms/api-form.ts');
        lines.push(' * Source: manifest.routes[].validation');
        lines.push(' */');
        lines.push('');

        let formTypeCount = 0;

        // Generate each form type
        for (const requestType of requestTypes) {
            const actions = actionsByResource.get(requestType.resourceName) || [];

            if (actions.length === 0) {
                // No actions - generate empty type
                lines.push(`export type ${requestType.formTypeName} = {}`);
                lines.push('');
                formTypeCount++;
                continue;
            }

            // Form type header
            lines.push(`export type ${requestType.formTypeName} = {`);

            // Add action blocks
            for (let i = 0; i < actions.length; i++) {
                const action = actions[i];

                // Add action lines
                for (const line of action.lines) {
                    lines.push(line);
                }

                // Add separator between actions (not after last)
                if (i < actions.length - 1) {
                    lines.push('');
                }
            }

            // Form type footer
            lines.push('}');
            lines.push('');

            formTypeCount++;
        }

        const code = lines.join('\n');

        return {
            code,
            lineCount: lines.length,
            formTypeCount
        };
    }

    /**
     * Build empty file (fallback ketika no validation rules)
     */
    buildEmptyFile(): BuiltCode {
        const lines = [
            '/**',
            ' * Form type definitions',
            ' * Generated by FormGeneratorPass',
            ' * ',
            ' * Note: No validation rules found in manifest',
            ' */',
            '',
            '// No form types generated'
        ];

        return {
            code: lines.join('\n'),
            lineCount: lines.length,
            formTypeCount: 0
        };
    }
}
