import { describe, expect, it } from 'vitest';
import { reconcileModelPrimaryKey } from '../modelPrimaryKey';
import { createColumnName, createTableName } from '../names';
import type { SchemaInterface } from '../schema';

const span = { kind: 'source_span' as const, file: { kind: 'source_file' as const, value: 'fixture' }, start: 0, end: 1 };
const stringValue = (value: string) => ({ kind: 'string_value' as const, value });
const column = (name: string, primary = false) => ({
  kind: 'column' as const,
  name: createColumnName(name),
  databaseType: { kind: 'string' as const, length: { kind: 'number_value' as const, value: 36 } },
  semanticType: { kind: 'string' as const },
  presence: { kind: 'required' as const },
  nullability: { kind: 'non_nullable' as const },
  default: { kind: 'none' as const },
  primary: { kind: 'truth_value' as const, value: primary },
  autoGenerated: { kind: 'truth_value' as const, value: false },
  source: span,
});
const empty = <T,>() => ({ kind: 'empty' as const });
const schema = (primaryKeys: readonly string[]): SchemaInterface => ({
  kind: 'schema_interface',
  definition: {
    kind: 'schema_definition',
    tables: {
      kind: 'schema_tables',
      items: {
        kind: 'cons',
        head: {
          kind: 'schema_table',
          table: createTableName('accounts'),
          columns: { kind: 'columns', items: primaryKeys.reduceRight((tail, name) => ({ kind: 'cons' as const, head: column(name, true), tail }), empty<ReturnType<typeof column>>()) },
          indexes: { kind: 'indexes', items: empty() },
          foreignKeys: { kind: 'foreign_keys', items: empty() },
          migrationProvenance: empty(),
          source: span,
        },
        tail: empty(),
      },
    },
    source: span,
  },
  source: span,
  closed: true,
});

describe('phase1003 model primary-key reconciliation', () => {
  it('matches a conventional model key to schema id', () => {
    const result = reconcileModelPrimaryKey(schema(['id']), createTableName('accounts'), createColumnName('id'), { kind: 'conventional' });
    expect(result.status).toBe('matched');
  });

  it('detects explicit uuid model key against schema id', () => {
    const result = reconcileModelPrimaryKey(schema(['id']), createTableName('accounts'), createColumnName('uuid'), { kind: 'explicit' });
    expect(result.status).toBe('conflict');
  });

  it('detects schema uuid against Laravel conventional model id', () => {
    const result = reconcileModelPrimaryKey(schema(['uuid']), createTableName('accounts'), createColumnName('id'), { kind: 'conventional' });
    expect(result.status).toBe('conflict');
  });

  it('does not invent a primary key when schema evidence is absent', () => {
    const result = reconcileModelPrimaryKey(schema([]), createTableName('accounts'), createColumnName('id'), { kind: 'conventional' });
    expect(result.status).toBe('unresolved');
  });

  it('keeps composite schema primary keys explicit as ambiguous for single-key Eloquent models', () => {
    const result = reconcileModelPrimaryKey(schema(['tenant_id', 'id']), createTableName('accounts'), createColumnName('id'), { kind: 'conventional' });
    expect(result.status).toBe('ambiguous');
  });
});
