// Auto-generated by routesync. Do not edit manually.

/* =========================
   APPLICATION CONSTANTS
========================= */

export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/api'

export const API_ENDPOINTS = {
  ADMIN_PRODUK: '/admin/produk',
  BUY_NOW: '/buy-now',
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (produkItemId: string | number) => `/cart/items/${produkItemId}`,
  CART_PROMO: '/cart/promo',
  CATEGORIES: '/categories',
  CHECKOUT: '/checkout',
  FORGOT_PASSWORD: '/forgot-password',
  KERANJANG: '/keranjang',
  LOGIN: '/login',
  LOGOUT: '/logout',
  OAUTH_PROVIDER_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  OAUTH_PROVIDER_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
  PAYMENT_ORDER_ID: (orderId: string | number) => `/payment/${orderId}`,
  PAYMENT_WEBHOOK: '/payment/webhook',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  SOCIAL_LOGIN: '/social/login',
  WISHLIST: '/wishlist',
  WISHLIST_PRODUK_ITEM_ID: (produkItemId: string | number) => `/wishlist/${produkItemId}`,
} as const

export const ROUTES = {
  HOME: '/',
  OAUTH_DETAIL_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  OAUTH_DETAIL_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  CATEGORIES: '/categories',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  KERANJANG: '/keranjang',
  WISHLIST: '/wishlist',
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
} as const

export const Enums = {
  Social: {
    Provider: {
      GOOGLE: 'google',
      FACEBOOK: 'facebook',
      APPLE: 'apple',
    } as const,
  },
  Payment: {
    Provider: {
      MOCK: 'mock',
      MIDTRANS: 'midtrans',
    } as const,
  },
} as const

export type SocialProvider = (typeof Enums.Social.Provider)[keyof typeof Enums.Social.Provider]
export type PaymentProvider = (typeof Enums.Payment.Provider)[keyof typeof Enums.Payment.Provider]
