// Auto-generated by routesync. Do not edit manually.

import { z } from 'zod'

export const RegisterCreateSchema = z.object({
  name: z.string(),
  email: z.string(),
  password: z.string(),
})

export const LoginCreateSchema = z.object({
  email: z.string(),
  password: z.string(),
})

export const OauthRedirectGetSchema = z.object({
  redirectTo: z.string().optional().nullable(),
})

export const SocialLoginCreateSchema = z.object({
  provider: z.string(),
  providerUserId: z.string(),
  email: z.string(),
  name: z.string().optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
})

export const ForgotPasswordCreateSchema = z.object({
  email: z.string(),
})

export const ResetPasswordCreateSchema = z.object({
  email: z.string(),
  token: z.string(),
  password: z.string(),
})

export const ProdukReviewsPostSchema = z.object({
  rating: z.number(),
  title: z.string().optional().nullable(),
  comment: z.string().optional().nullable(),
})

export const ProfilePutSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const ProfilePatchSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const CartItemsCreateSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
})

export const CartItemsUpdateSchema = z.object({
  qty: z.number(),
})

export const CartPromoCreateSchema = z.object({
  code: z.string(),
})

export const CheckoutCreateSchema = z.object({
  items: z.array(z.unknown()).optional(),
  "items.*.produkItemId": z.string(),
  "items.*.qty": z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const BuyNowCreateSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const WishlistCreateSchema = z.object({
  produkItemId: z.string(),
})

export const PaymentPostSchema = z.object({
  metode: z.string(),
  detail: z.array(z.unknown()).optional().nullable(),
  provider: z.string().optional().nullable(),
  providerTxnId: z.string().optional().nullable(),
  idempotencyKey: z.string().optional().nullable(),
  gatewayCode: z.string().optional().nullable(),
  gatewayMessage: z.string().optional().nullable(),
})

export const AdminProdukCreateSchema = z.object({
  nama: z.string(),
  deskripsi: z.string().optional().nullable(),
  gambar: z.string().optional().nullable(),
  categoryId: z.string(),
  harga: z.number(),
  stok: z.number(),
  rating: z.number().optional().nullable(),
  jumlahReview: z.number().optional().nullable(),
})
