/**
 * api-field-domain.ts
 *
 * Pure Stage Operations for API Field Generation.
 * 0 spread operators, 0 procedural branching.
 *
 * @module compiler/passes
 */

import type { RequestTypesArtifact } from '../artifacts/RequestTypesArtifact';
import type { GeneratedApiFieldArtifact } from '../artifacts/GeneratedApiFieldArtifact';
import type { ArtifactMetadata } from '../artifacts/Artifact';

export interface ExtractedApiField {
    readonly originalName: string;
}

export interface DerivedApiField extends ExtractedApiField {
    readonly derivedKey: string;
}

export interface FieldCollection<TField> {
    readonly fields: readonly TField[];
}

export type ExtractedFieldNames = FieldCollection<string>;
export type UniqueFieldCollection = FieldCollection<string>;
export type GeneratedApiFieldCode = string;

export function extractFieldNames(artifact: RequestTypesArtifact): readonly string[] {
    const names: string[] = [];
    for (const rt of artifact.requestTypes) {
        for (const action of rt.actions) {
            for (const field of action.fields) {
                names.push(field.originalName);
                const isCollection =
                    (field.type as any)?.kind === 'readonly_collection' ||
                    (field.type as any)?.kind === 'mutable_collection';
                const elem = isCollection ? (field.type as any).elementType : field.type;
                if ((elem as any)?.kind === 'object' && (elem as any)?.properties) {
                    const props = (elem as any).properties;
                    if (Array.isArray(props)) {
                        for (const p of props) {
                            if (p.name && !p.name.startsWith('__')) {
                                names.push(p.name);
                            }
                        }
                    } else if (typeof props.entries === 'function') {
                        for (const [k] of props.entries()) {
                            if (typeof k === 'string' && !k.startsWith('__')) {
                                names.push(k);
                            }
                        }
                    }
                }
            }
        }
    }
    return names;
}

export function deduplicateFieldNames(rawNames: readonly string[]): UniqueFieldCollection {
    return {
        fields: Array.from(new Set(rawNames))
    };
}

export function deriveApiFieldKey(originalName: string): string {
    return originalName.toUpperCase().replace(/[^A-Z0-9]/g, '');
}

export function formatApiFieldConstant(
    uniqueNames: readonly string[] | UniqueFieldCollection,
    exportConstName = 'ApiApiField'
): GeneratedApiFieldCode {
    const names = Array.isArray(uniqueNames) ? uniqueNames : uniqueNames.fields;
    const fieldEntries = names
        .map(name => `  ${deriveApiFieldKey(name)}: "${name}",`)
        .join('\n');

    return `// Auto-generated by routesync. Do not edit manually.\n\nexport const ${exportConstName} = {\n${fieldEntries}\n} as const\n`;
}

export function buildApiFieldArtifact(
    code: GeneratedApiFieldCode,
    metadataOrProducer: ArtifactMetadata | string
): GeneratedApiFieldArtifact {
    const metadata: ArtifactMetadata = typeof metadataOrProducer === 'string'
        ? {
            hash: 'api-field-hash',
            producer: metadataOrProducer,
            dependencies: ['RequestTypes'],
            timestamp: Date.now(),
            revision: '1.0.0'
        }
        : metadataOrProducer;

    return {
        typeId: 'GeneratedApiField',
        code,
        metadata
    };
}