/**
 * api-field-domain.ts
 *
 * Flow-Based Type Design & Pure Operations module for ApiFieldGeneratorPass.
 *
 * Pipeline Stage Transformations:
 *   RequestTypesArtifact
 *          ↓ (extractFieldNames)
 *   ExtractedFieldNames (FieldCollection<string>)
 *          ↓ (deduplicateFieldNames)
 *   UniqueFieldCollection (FieldCollection<string>)
 *          ↓ (formatApiFieldConstant)
 *   GeneratedApiFieldCode (string)
 *          ↓ (buildApiFieldArtifact)
 *   GeneratedApiFieldArtifact
 *
 * @module compiler/passes
 */

import type { RequestTypesArtifact } from '../artifacts/RequestTypesArtifact';
import type { GeneratedApiFieldArtifact } from '../artifacts/GeneratedApiFieldArtifact';

// ============================================================================
// 1. DOMAIN TYPE VOCABULARY
// ============================================================================

/**
 * Extracted API field representation
 */
export interface ExtractedApiField {
    readonly originalName: string;
}

/**
 * Derived API field with computed const key
 * Demonstrates subtyping ("is-a" relationship: DerivedApiField extends ExtractedApiField)
 */
export interface DerivedApiField extends ExtractedApiField {
    readonly derivedKey: string;
}

/**
 * Reusable generic field collection contract
 */
export interface FieldCollection<TField = string> {
    readonly fields: readonly TField[];
}

/**
 * Extracted raw field names collection
 */
export type ExtractedFieldNames = FieldCollection<string>;

/**
 * Collection of unique field names maintaining first-appearance insertion order
 */
export type UniqueFieldCollection = FieldCollection<string>;

/**
 * Branded string container representing formatted TypeScript source code
 */
export type GeneratedApiFieldCode = string;

// ============================================================================
// 2. PURE STAGE OPERATIONS (FLOW PIPELINE)
// ============================================================================

/**
 * Stage 1: Extract all original field names across request types and actions.
 *
 * @param artifact - Input RequestTypesArtifact
 * @returns Array of extracted original field names in traversal order
 */
export function extractFieldNames(artifact: RequestTypesArtifact): readonly string[] {
    const requestTypes = artifact.requestTypes || [];
    const extractedNames: string[] = [];

    for (const rt of requestTypes) {
        for (const action of rt.actions || []) {
            for (const field of action.fields || []) {
                if (field.originalName) {
                    extractedNames.push(field.originalName);
                }
            }
        }
    }

    return extractedNames;
}

/**
 * Stage 2: Deduplicate field names while preserving first appearance insertion order.
 *
 * @param rawNames - Collection of raw field names
 * @returns UniqueFieldCollection containing deduplicated field names
 */
export function deduplicateFieldNames(rawNames: readonly string[]): UniqueFieldCollection {
    const seenNames = new Set<string>();
    const uniqueFields: string[] = [];

    for (const name of rawNames) {
        if (seenNames.has(name)) {
            continue;
        }
        seenNames.add(name);
        uniqueFields.push(name);
    }

    return { fields: uniqueFields };
}

/**
 * Stage 3A: Derive const key name from original field name.
 * Converts to uppercase and strips all underscores (e.g. 'redirect_to' -> 'REDIRECTTO').
 *
 * @param originalName - Field original name
 * @returns Derived const property key
 */
export function deriveApiFieldKey(originalName: string): string {
    return originalName.toUpperCase().replace(/_/g, '');
}

/**
 * Stage 3B: Format the unique field collection into TypeScript source code (`ApiApiField` const).
 *
 * @param collection - UniqueFieldCollection
 * @returns Formatted GeneratedApiFieldCode
 */
export function formatApiFieldConstant(collection: UniqueFieldCollection): GeneratedApiFieldCode {
    let code = '// Auto-generated by routesync. Do not edit manually.\n\n';
    code += 'export const ApiApiField = {\n';

    for (const name of collection.fields) {
        const key = deriveApiFieldKey(name);
        code += `  ${key}: "${name}",\n`;
    }

    code += '} as const\n';
    return code;
}

/**
 * Stage 4: Package generated TypeScript code into a GeneratedApiFieldArtifact with metadata.
 *
 * @param code - GeneratedApiFieldCode
 * @param producerName - Pass producer name
 * @returns Complete GeneratedApiFieldArtifact
 */
export function buildApiFieldArtifact(
    code: GeneratedApiFieldCode,
    producerName: string
): GeneratedApiFieldArtifact {
    return {
        typeId: 'GeneratedApiField',
        code,
        metadata: {
            hash: 'api-field-hash',
            producer: producerName,
            dependencies: ['RequestTypes'],
            timestamp: Date.now(),
            revision: '1.0.0'
        }
    };
}
