/**
 * ApiFieldGeneratorPass.ts
 *
 * Compiler pass that collects field names across RequestTypes and generates contracts/api-field.ts.
 * 
 * @module compiler/passes
 */

import type { CompilerPass } from './CompilerPass';
import type { PassDescriptor, PassDependency } from './PassDescriptor';
import { ArtifactKeyWitness, type ResolveArtifacts } from './ArtifactKeyWitness';
import type { RequestTypesArtifact } from '../artifacts/RequestTypesArtifact';
import type { GeneratedApiFieldArtifact } from '../artifacts/GeneratedApiFieldArtifact';

export class ApiFieldGeneratorPass
    implements CompilerPass<readonly ['RequestTypes'], readonly ['GeneratedApiField']> {

    public readonly name = 'ApiFieldGenerator';

    public readonly inputWitnesses = [
        new ArtifactKeyWitness('RequestTypes')
    ] as const;

    public readonly outputKeys = ['GeneratedApiField'] as const;

    public readonly descriptor: PassDescriptor<
        readonly ['RequestTypes'],
        readonly ['GeneratedApiField']
    > = {
            consumes: ['RequestTypes'],
            produces: ['GeneratedApiField']
        };

    public readonly requires: readonly PassDependency<'RequestTypes'>[] = [
        {
            artifact: 'RequestTypes',
            producer: undefined
        }
    ];

    public readonly producesPass: readonly string[] = [];

    public run(
        inputs: ResolveArtifacts<readonly ['RequestTypes']>
    ): ResolveArtifacts<readonly ['GeneratedApiField']> {
        const [requestTypesArtifact] = inputs;
        const requestTypes = requestTypesArtifact.requestTypes || [];

        const seenNames = new Set<string>();
        const fieldsInOrder: string[] = [];

        for (const rt of requestTypes) {
            for (const action of rt.actions || []) {
                for (const field of action.fields || []) {
                    const name = field.originalName;
                    if (name && !seenNames.has(name)) {
                        seenNames.add(name);
                        fieldsInOrder.push(name);
                    }
                }
            }
        }

        let code = '// Auto-generated by routesync. Do not edit manually.\n\n';
        code += 'export const ApiApiField = {\n';
        for (const name of fieldsInOrder) {
            const key = name.toUpperCase().replace(/_/g, '');
            code += `  ${key}: "${name}",\n`;
        }
        code += '} as const\n';

        const artifact: GeneratedApiFieldArtifact = {
            typeId: 'GeneratedApiField',
            code,
            metadata: {
                hash: 'api-field-hash',
                producer: this.name,
                dependencies: ['RequestTypes'],
                timestamp: Date.now(),
                revision: '1.0.0'
            }
        };

        return [artifact];
    }
}
