/**
 * fileFormatters.ts
 *
 * File templates and formatting helpers for TypeScriptWriter.
 *
 * @module cli/generators/writer
 */

import type { CompilerOutput } from '../CompilerBridge';

export function formatGeneratedFile(output: CompilerOutput): string {
    const lines = [
        '/**',
        ' * Generated TypeScript types',
        ' * @generated by RouteSync CompilerBridge',
        ` * @timestamp ${new Date().toISOString()}`,
        ' * DO NOT EDIT - This file is auto-generated',
        ' */',
        '',
        '// Imports',
        ...output.imports.map(imp => imp),
        '',
        '// Type definitions',
        output.code,
        '',
        '// Interfaces',
        ...output.interfaces.map(iface => iface),
        ''
    ];

    return lines.join('\n');
}

export function formatIndexFile(_output: CompilerOutput): string {
    const lines = [
        '/**',
        ' * Type exports',
        ' * @generated by RouteSync CompilerBridge',
        ' */',
        '',
        '// Re-export all types',
        "export * from './generated'",
        ''
    ];

    return lines.join('\n');
}

export function formatMappersIndex(): string {
    const lines = [
        '/**',
        ' * Response mappers',
        ' * @generated by RouteSync CompilerBridge',
        ' */',
        '',
        '// Mappers will be generated here',
        'export const mappers = {}',
        ''
    ];

    return lines.join('\n');
}

export function formatRootIndex(): string {
    const lines = [
        '/**',
        ' * RouteSync Generated API',
        ' * @generated by RouteSync CompilerBridge',
        ' */',
        '',
        '// Export all types',
        "export * from './types'",
        '',
        '// Export all mappers',
        "export * from './mappers'",
        ''
    ];

    return lines.join('\n');
}
