import { describe, test, expect } from 'vitest'
import {
    extractFieldNames,
    deduplicateFieldNames,
    deriveApiFieldKey,
    formatApiFieldConstant,
    buildApiFieldArtifact
} from '../api-field-domain'
import type { RequestTypesArtifact } from '../../artifacts/RequestTypesArtifact'
import { PrimitiveKind, PrimitiveType } from '../../types/SemanticType'

function createMockRequestTypesArtifact(): RequestTypesArtifact {
    return {
        typeId: 'RequestTypes',
        metadata: {
            hash: 'test-hash',
            producer: 'test',
            dependencies: [],
            timestamp: Date.now(),
            revision: '1.0.0'
        },
        requestTypes: [
            {
                resourceName: 'auth',
                formTypeName: 'AuthForm',
                actions: [
                    {
                        name: 'create',
                        fields: [
                            {
                                originalName: 'email',
                                transformedName: 'email',
                                type: new PrimitiveType(PrimitiveKind.STRING),
                                required: true,
                                nullable: false
                            },
                            {
                                originalName: 'password',
                                transformedName: 'password',
                                type: new PrimitiveType(PrimitiveKind.STRING),
                                required: true,
                                nullable: false
                            }
                        ]
                    }
                ]
            },
            {
                resourceName: 'profile',
                formTypeName: 'ProfileForm',
                actions: [
                    {
                        name: 'update',
                        fields: [
                            {
                                originalName: 'email', // Duplicate field across resources
                                transformedName: 'email',
                                type: new PrimitiveType(PrimitiveKind.STRING),
                                required: false,
                                nullable: true
                            },
                            {
                                originalName: 'redirect_to', // Field with underscores
                                transformedName: 'redirectTo',
                                type: new PrimitiveType(PrimitiveKind.STRING),
                                required: false,
                                nullable: true
                            }
                        ]
                    }
                ]
            }
        ]
    }
}

describe('ApiField Domain Stage-by-Stage Flow Boundary Tests', () => {
    test('Stage 1: extractFieldNames should extract all field originalNames in order', () => {
        const inputArtifact = createMockRequestTypesArtifact()
        const extracted = extractFieldNames(inputArtifact)

        expect(extracted).toEqual(['email', 'password', 'email', 'redirect_to'])
    })

    test('Stage 2: deduplicateFieldNames should preserve first appearance insertion order and remove duplicates', () => {
        const rawNames = ['email', 'password', 'email', 'redirect_to']
        const uniqueCollection = deduplicateFieldNames(rawNames)

        expect(uniqueCollection.fields).toEqual(['email', 'password', 'redirect_to'])
    })

    test('Stage 3A: deriveApiFieldKey should derive key by converting to uppercase and stripping underscores', () => {
        expect(deriveApiFieldKey('email')).toBe('EMAIL')
        expect(deriveApiFieldKey('redirect_to')).toBe('REDIRECTTO')
        expect(deriveApiFieldKey('user_first_name')).toBe('USERFIRSTNAME')
    })

    test('Stage 3B: formatApiFieldConstant should format valid TypeScript ApiApiField const block', () => {
        const collection = { fields: ['email', 'redirect_to'] }
        const code = formatApiFieldConstant(collection)

        expect(code).toContain('// Auto-generated by routesync. Do not edit manually.\n\n')
        expect(code).toContain('export const ApiApiField = {\n')
        expect(code).toContain('  EMAIL: "email",\n')
        expect(code).toContain('  REDIRECTTO: "redirect_to",\n')
        expect(code).toContain('} as const\n')
    })

    test('Stage 4: buildApiFieldArtifact should construct GeneratedApiFieldArtifact with metadata', () => {
        const code = formatApiFieldConstant({ fields: ['email'] })
        const artifact = buildApiFieldArtifact(code, 'ApiFieldGenerator')

        expect(artifact.typeId).toBe('GeneratedApiField')
        expect(artifact.code).toBe(code)
        expect(artifact.metadata.producer).toBe('ApiFieldGenerator')
        expect(artifact.metadata.dependencies).toEqual(['RequestTypes'])
    })

    test('End-to-End Pipeline Stage Flow: input -> extract -> dedupe -> format -> artifact', () => {
        const inputArtifact = createMockRequestTypesArtifact()

        // Trace pipeline step by step
        const extracted = extractFieldNames(inputArtifact)
        const unique = deduplicateFieldNames(extracted)
        const code = formatApiFieldConstant(unique)
        const artifact = buildApiFieldArtifact(code, 'ApiFieldGenerator')

        expect(artifact.code).toContain('EMAIL: "email"')
        expect(artifact.code).toContain('PASSWORD: "password"')
        expect(artifact.code).toContain('REDIRECTTO: "redirect_to"')
    })
})
